import {test} from 'node:test';import assert from 'node:assert/strict';import {createCoordinator} from '../../scripts/exploration/coordinator.mjs';import {createLedger} from '../../scripts/exploration/ledger.mjs';import {chooseNext} from '../../scripts/exploration/policy.mjs';
function fixture(results){let data={sessions:{},activities:{},clocks:{}},now=0,calls=0,hp=1;const healer={actorUUID:'H',medicine:{rank:1,mod:8},slugs:[],assuranceSkills:[],items:[],pool:{poolUUID:'H',ready:true},hp:{value:10,max:10},focus:{value:0,max:0}},patient={...healer,actorUUID:'P',medicine:{rank:0},pool:{poolUUID:'P',ready:true},hp:{value:hp,max:20},modeOfBeing:'living',cooldownExpiresAt:0};
 const ledger=createLedger({read:async()=>data,write:async s=>{data=s},isAuthority:()=>true});const capabilities={snapshot:async()=>[healer,{...patient,hp:{value:hp,max:20}}]};const provider={id:'treat-wounds',begin:async()=>({status:'started'}),complete:async()=>{const amount=results[calls++];if(amount===null)return {status:'uncertain',reason:'owner-lost'};hp=Math.min(20,hp+amount);return {status:'confirmed',proof:{checkIds:[`C${calls}`],receiptIds:[`R${calls}`]}}}};
 const clock={advanceTo:async c=>{now=c.to;return {status:'confirmed'}}};const c=createCoordinator({ledger,capabilities,providers:[provider],clock,policy:chooseNext,isAuthority:()=>true,now:()=>now,ownerOperations:{createActivityContext:async()=>({})}});return {c,ledger,calls:()=>calls,hp:()=>hp};}
test('real failed result followed by actual healing drives target completion',async()=>{const f=fixture([0,19]);const s=await f.c.start({id:'S',actorUUIDs:['H','P'],goalsByPool:[{poolUUID:'P',targetHP:20}],autoRun:false});for(let i=0;i<4;i++)await f.c.step(s.id);const snap=await f.c.snapshot(s.id);assert.equal(f.hp(),20);assert.equal(f.calls(),2);assert.equal(snap.session.cursorAt,4200);assert.equal(snap.session.status,'complete')});
test('unknown result stops and resume refuses any native replay',async()=>{const f=fixture([null]);const s=await f.c.start({id:'S',actorUUIDs:['H','P'],goalsByPool:[{poolUUID:'P',targetHP:20}],autoRun:false});await f.c.step(s.id);await assert.rejects(f.c.resume(s.id),/unresolved/);assert.equal(f.calls(),1)});
test('new session cannot bypass unresolved native evidence for the same actors or pools',async()=>{const f=fixture([null]);const s=await f.c.start({id:'S',actorUUIDs:['H','P'],autoRun:false});await f.c.step(s.id);await assert.rejects(f.c.start({id:'B',actorUUIDs:['H','P'],autoRun:false}),/unresolved/);assert.equal(f.calls(),1)});
test('stop cancels only activities which have not begun a native execution',async()=>{const f=fixture([]);const s=await f.c.start({id:'S',actorUUIDs:['H','P'],autoRun:false});const a=await f.c.addActivity(s.id,{providerId:'treat-wounds',actorUUID:'H',patientUUIDs:['P'],hpPoolUUIDs:['P'],startedAt:0,endsAt:600,options:{}});await f.c.stop(s.id);assert.equal((await f.ledger.getActivity(a.id)).state,'cancelled')});
test('activity count budget still allows the already started last activity to finish',async()=>{const f=fixture([19]);const s=await f.c.start({id:'S',actorUUIDs:['H','P'],maxActivities:1,autoRun:false});const a=await f.c.addActivity(s.id,{providerId:'treat-wounds',actorUUID:'H',patientUUIDs:['P'],hpPoolUUIDs:['P'],startedAt:0,endsAt:600,options:{}});await f.c.step(s.id);assert.equal((await f.ledger.getActivity(a.id)).state,'confirmed');assert.equal(f.calls(),1)});
test('configured time budget may exceed the two-hour default',async()=>{const f=fixture([]);const s=await f.c.start({id:'S',actorUUIDs:['H','P'],budgetSeconds:9000,autoRun:false});assert.equal(s.budgetEndsAt,9000)});
test('extension cannot exceed the configured activity count',async()=>{
 let data={sessions:{},activities:{},clocks:{}},at=0;
 const ledger=createLedger({read:async()=>data,write:async s=>{data=s},isAuthority:()=>true});
 const actor={actorUUID:'H',pool:{poolUUID:'P',ready:true},hp:{value:1,max:20},focus:{value:0,max:0}};
 const c=createCoordinator({ledger,capabilities:{snapshot:async()=>[actor]},providers:[{id:'treat-wounds',begin:async()=>({status:'started'}),complete:async()=>({status:'confirmed',effectiveOutcome:'success'})}],clock:{advanceTo:async p=>{at=p.to;return {status:'confirmed'}}},policy:chooseNext,isAuthority:()=>true,now:()=>at,ownerOperations:{createActivityContext:async()=>({})}});
 const s=await c.start({id:'S',actorUUIDs:['H'],maxActivities:1,extendTreatment:true,autoRun:false});await c.addActivity(s.id,{providerId:'treat-wounds',actorUUID:'H',patientUUIDs:['H'],hpPoolUUIDs:['P'],startedAt:0,endsAt:600,options:{}});await c.step(s.id);assert.equal((await ledger.snapshot(s.id)).activities.length,1);
});
