import {test} from 'node:test';import assert from 'node:assert/strict';
import {createLedger} from '../../scripts/exploration/ledger.mjs';
import {createCapabilities} from '../../scripts/exploration/capabilities.mjs';
import {chooseNext,recoveryProposals} from '../../scripts/exploration/policy.mjs';
import {createCoordinator} from '../../scripts/exploration/coordinator.mjs';
import {createTreatmentProvider} from '../../scripts/exploration/treatment.mjs';
import {createRefocusProvider} from '../../scripts/exploration/refocus.mjs';
import {createManualEvents} from '../../scripts/exploration/manual-events.mjs';
import {createClock} from '../../scripts/exploration/clock.mjs';
import {createExplorationOwnerOperations} from '../../scripts/exploration/owner-operations.mjs';
const M='pf2e-third-party-automation';
const healer={actorUUID:'Actor.H',slugs:[],items:[],assuranceSkills:[],medicine:{rank:2,mod:12},wardCapacity:2,focus:{value:0,max:0},pool:{poolUUID:'Actor.H',ready:true},hp:{value:20,max:20}};
const patient=(uuid='Actor.P',modeOfBeing='living')=>({...healer,actorUUID:uuid,medicine:{rank:0},pool:{poolUUID:uuid,ready:true},hp:{value:1,max:20},modeOfBeing});
function storage(initial={sessions:{},activities:{},clocks:{}}){let data=structuredClone(initial);return createLedger({read:async()=>structuredClone(data),write:async s=>{data=structuredClone(s)},isAuthority:()=>true})}
function coordinator(ledger,ownerOperations={},result={status:'confirmed'},actors=[healer,patient()]){let at=0,calls=0;return {api:createCoordinator({ledger,capabilities:{snapshot:async uuids=>actors.filter(a=>uuids.includes(a.actorUUID))},providers:[{id:'treat-wounds',begin:async()=>({status:'started'}),complete:async()=>{calls++;return result}}],clock:{advanceTo:async p=>{at=p.to;return {status:'confirmed'}},reconcile:async c=>({status:c.state==='confirmed'?'confirmed':'uncertain'})},policy:chooseNext,isAuthority:()=>true,now:()=>at,ownerOperations:{createActivityContext:async()=>({}),...ownerOperations}}),calls:()=>calls}}
const input={id:'A',providerId:'treat-wounds',actorUUID:'Actor.H',patientUUIDs:['Actor.P'],hpPoolUUIDs:['Actor.P'],startedAt:0,endsAt:600,options:{}};
test('reconstructed coordinator discovers a previous GM session and pauses nonempty interrupted work without executing it',async()=>{
 const ledger=storage(),old=coordinator(ledger);await old.api.start({id:'S',actorUUIDs:['Actor.H','Actor.P'],autoRun:false});await old.api.addActivity('S',input);
 const fresh=coordinator(ledger);const s=await fresh.api.restore(null);assert.equal(s.id,'S');assert.equal(s.status,'paused');assert.equal((await ledger.getActivity('A')).state,'uncertain');assert.equal(fresh.calls(),0);await assert.rejects(fresh.api.resume('S',{autoRun:false}),/unresolved/);
});
test('saved owner completion reconciles an interrupted activity; explicit reviewed closure retains unknown clock without replay',async()=>{
 const ledger=storage(),old=coordinator(ledger);await old.api.start({id:'S',actorUUIDs:['Actor.H','Actor.P'],autoRun:false});await old.api.addActivity('S',input);await ledger.transitionActivity('A',{expected:['started'],patch:{state:'completing'}});
 const fresh=coordinator(ledger,{reconcile:async()=>({status:'confirmed',proof:{useId:'A',receiptIds:['R'],poolReceipts:[{actorUUID:'Actor.P',noChange:true,receiptId:'R'}]}})});await fresh.api.restore(null);await fresh.api.reconcile('S');assert.equal((await ledger.getActivity('A')).state,'confirmed');assert.equal(fresh.calls(),0);
 await ledger.upsertClockCommit({id:'C',sessionId:'S',gmId:'OLD',from:0,to:600,state:'uncertain'});await fresh.api.review('S',{note:'GM inspected saved events; close this attempt',userId:'NEW'});assert.equal((await ledger.getClockCommit('C')).state,'uncertain');assert.ok((await ledger.getClockCommit('C')).review);assert.equal((await ledger.getSession('S')).status,'closed');await fresh.api.start({id:'NEXT',actorUUIDs:['Actor.H','Actor.P'],autoRun:false});assert.equal(fresh.calls(),0);
});
test('a stale GM preference cannot hide a newer interrupted world session',async()=>{const ledger=storage();await ledger.createSession({id:'OLD',actorUUIDs:['Actor.H'],startedAt:-600,cursorAt:-600,budgetEndsAt:600,status:'paused'});const f=coordinator(ledger);await f.api.start({id:'NEW',actorUUIDs:['Actor.H','Actor.P'],autoRun:false});await f.api.addActivity('NEW',input);await ledger.updateSession('NEW',{status:'paused'});const fresh=coordinator(ledger);assert.equal((await fresh.api.restore('OLD')).id,'NEW');});
test('manual receipt, duplicate enrollment and source order survive recorder reconstruction',async()=>{
 const ledger=storage({sessions:{S:{id:'S',status:'recording',actorUUIDs:['Actor.H','Actor.P'],activityIds:[]}},activities:{},clocks:{}}),messages=new Map(),handlers=new Map();const game={time:{worldTime:0},messages},Hooks={on:(n,f)=>{handlers.set(n,f);return n},off(){}};const opts={game,Hooks,ledger,isAuthority:()=>true,sessionId:()=> 'S'};
 const old=createManualEvents(opts);old.start();await old.observe({id:'W',actorUUID:'Actor.H',patientUUIDs:['Actor.P'],kind:'treatment',resultIds:['D'],missing:['native-application-receipt']});old.stop();
 const source={id:'D',rolls:[{_evaluated:true}]};messages.set('D',source);const fresh=createManualEvents(opts);fresh.start();const receipt={id:'R',speaker:{actor:'P'},flags:{pf2e:{context:{type:'damage-taken',options:[`${M}:source:D:0`]},appliedDamage:null}}};messages.set('R',receipt);handlers.get('createChatMessage')(receipt);for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));
 assert.deepEqual((await ledger.getActivity('manual:W')).proof.receiptIds,['R']);await fresh.observe({id:'W',actorUUID:'Actor.H',kind:'treatment'});await fresh.observe({id:'NEXT',actorUUID:'Actor.H',patientUUIDs:['Actor.P'],kind:'activity',durationSeconds:6});assert.equal((await ledger.getActivity('manual:NEXT')).order,1);assert.equal((await ledger.snapshot('S')).activities.length,2);
});
test('unselected treatments and messages authored without ownership cannot enroll in a party recording',async()=>{
 const ledger=storage({sessions:{S:{id:'S',status:'recording',actorUUIDs:['Actor.H','Actor.P'],activityIds:[]}},activities:{},clocks:{}}),messages=new Map(),author={id:'USER'},actor={id:'H',uuid:'Actor.H',testUserPermission:()=>false};const game={time:{worldTime:0},messages,users:new Map([['USER',author]])};const r=createManualEvents({game,ledger,fromUuid:async()=>actor,isAuthority:()=>true,sessionId:()=> 'S'});
 await r.observe({id:'UNRELATED',actorUUID:'Actor.OTHER',patientUUIDs:['Actor.P'],kind:'treatment'});messages.set('FORGED',{id:'FORGED',author,speaker:{actor:'H'}});await r.observe({id:'FORGED',actorUUID:'Actor.H',patientUUIDs:['Actor.P'],kind:'treatment',source:{type:'workbench'}});assert.equal((await ledger.snapshot('S')).activities.length,0);
});
test('copying an owned native check cannot enroll the same invocation a second time',async()=>{const ledger=storage({sessions:{S:{id:'S',status:'recording',actorUUIDs:['Actor.H','Actor.P'],activityIds:[]}},activities:{},clocks:{}}),user={id:'P'},actor={id:'H',uuid:'Actor.H',testUserPermission:()=>true},messages=new Map(),r=createManualEvents({game:{time:{worldTime:0},messages,users:new Map([['P',user]])},ledger,fromUuid:async()=>actor,isAuthority:()=>true,sessionId:()=> 'S'});for(const id of ['C','COPY']){messages.set(id,{id,author:user,speaker:{actor:'H'},rolls:[{_evaluated:true}],flags:{[M]:{explorationManualNative:{useId:'N',tag:'exploration-manual:N',patientUUID:'Actor.P'}},pf2e:{context:{origin:{actor:'Actor.H'},options:['exploration-manual:N'],type:'skill-check'}}}});await r.observe({id,actorUUID:'Actor.H',patientUUIDs:['Actor.P'],kind:'treatment',useId:'N',source:{type:'native-action',tag:'exploration-manual:N'}})}assert.equal((await ledger.snapshot('S')).activities.length,1);});
test('negative epoch preserves absent and actual negative immunity when selecting the first legal checkpoint',async()=>{
 const actor={uuid:'Actor.P',modeOfBeing:'living',system:{attributes:{hp:{value:1,max:20}}},items:[]};const game={time:{worldTime:-10000}};const c=createCapabilities({game,fromUuid:async()=>actor,hpPools:{discover:()=>({poolUUID:actor.uuid,ready:true})}});const p={...patient(),...await c.discover(actor.uuid)};const session={goalsByPool:[{poolUUID:'Actor.P',targetHP:20}],budgetEndsAt:-2800};let proposals=recoveryProposals({actors:[healer,p],activities:[],session,now:-10000,providerIds:['treat-wounds']});assert.equal(chooseNext({snapshot:{},proposals,session,now:-10000}).checkpointAt,-9400);
 actor.items=[{type:'effect',sourceId:'Compendium.pf2e.feat-effects.Item.Lb4q2bBAgxamtix5',system:{start:{value:-13200},duration:{value:1,unit:'hours'}}}];assert.equal((await c.discover(actor.uuid)).cooldownExpiresAt,-9600);
});
test('unadapted improved Refocus is explicitly blocked before a ten-minute baseline can be proposed',async()=>{
 const actor={uuid:'Actor.H',system:{attributes:{hp:{value:20,max:20}},resources:{focus:{value:0,max:3}}},items:[{type:'feat',slug:'meditative-focus'}]};const c=createCapabilities({game:{time:{worldTime:0}},fromUuid:async()=>actor,hpPools:{discover:()=>({poolUUID:actor.uuid,ready:true})}}),h={...healer,...await c.discover(actor.uuid)};
 const proposals=recoveryProposals({actors:[h],activities:[],session:{requireFullFocus:true,goalsByPool:[]},now:0,providerIds:['refocus']});assert.deepEqual(proposals,[]);const provider=createRefocusProvider({capabilities:c});assert.equal((await provider.begin({actorUUID:actor.uuid,options:{}},{})).reason,'refocus-recovery-unadapted');
});
test('Stitch Flesh adds undead, rejects constructs at proposal and completion even if eligibility changes',async()=>{
 const h={...healer,slugs:['stitch-flesh']};for(const mode of ['living','undead','construct']){const p=patient('Actor.P',mode),proposals=recoveryProposals({actors:[h,p],activities:[],session:{goalsByPool:[{poolUUID:'Actor.P',targetHP:20}]},now:0,providerIds:['treat-wounds']});assert.equal(proposals.length>0,mode!=='construct')}
 let p=patient(),calls=0;const provider=createTreatmentProvider({capabilities:{discover:async()=>h,snapshot:async()=>[p]},ownerOperations:{runActivityWithOwner:async()=>{calls++;return {status:'confirmed'}}},nativeTreatment:{}});assert.equal((await provider.begin(input)).status,'started');p=patient('Actor.P','construct');assert.equal((await provider.complete(input,{})).status,'blocked');assert.equal(calls,0);
});
test('extension rechecks a patient that becomes an illegal construct before the original roll is applied again',async()=>{
 let p=patient(),calls=0;const original={...input,state:'confirmed',effectiveOutcome:'success',results:[{patientUUID:'Actor.P',effectiveOutcome:'success'}]};const provider=createTreatmentProvider({capabilities:{discover:async()=>({...healer,slugs:['stitch-flesh']}),snapshot:async()=>[p]},ledger:{getActivity:async()=>original},ownerOperations:{runActivityWithOwner:async()=>{calls++;return {status:'confirmed'}}},nativeTreatment:{}});const a={...input,id:'E',options:{extensionOf:'A'}};assert.equal((await provider.begin(a)).status,'started');p=patient('Actor.P','construct');assert.equal((await provider.complete(a,{})).status,'blocked');assert.equal(calls,0);
});
test('a refused special Refocus identifies its unsupported rule in the stopped session',async()=>{const h={...healer,focus:{value:0,max:3},refocusUnsupported:['meditative-focus']},ledger=storage(),f=coordinator(ledger,{}, {},[h]);await f.api.start({id:'S',actorUUIDs:['Actor.H'],requireFullFocus:true,autoRun:false});await f.api.step('S');assert.equal((await ledger.getSession('S')).stopReason,'refocus-recovery-unadapted');});
for(const reverse of [false,true])test(`mixed Ward outcomes extend only successful patients regardless of ordering ${reverse}`,async()=>{
 const results=[{patientUUID:'Actor.P',effectiveOutcome:'failure',proof:{}},{patientUUID:'Actor.Q',effectiveOutcome:'success',rolledHealing:9,proof:{resultIds:['D']}}];if(reverse)results.reverse();const ledger=storage(),actors=[healer,patient('Actor.P'),patient('Actor.Q')],f=coordinator(ledger,{}, {status:'confirmed',effectiveOutcome:results[0].effectiveOutcome,results},actors);
 await f.api.start({id:'S',actorUUIDs:actors.map(a=>a.actorUUID),autoRun:false,extendTreatment:true,maxActivities:2});await f.api.addActivity('S',{...input,patientUUIDs:['Actor.P','Actor.Q'],hpPoolUUIDs:['Actor.P','Actor.Q']});await f.api.step('S');const extension=(await ledger.snapshot('S')).activities.find(a=>a.options.extensionOf==='A');assert.ok(extension);assert.deepEqual(extension.patientUUIDs,['Actor.Q']);
});
test('reconciliation accepts exact persisted clock/native/effect completion, never current clock equality alone',async()=>{
 const ledger=storage();await ledger.createSession({id:'S',startedAt:0,budgetEndsAt:7200});const commit={id:'C',sessionId:'S',gmId:'OLD',from:0,to:600,state:'uncertain',nativeResolved:true,effectsSettled:true,evidence:[{worldTime:600,dt:600,userId:'OLD',options:{pf2eThirdPartyAutomation:{exploration:{sessionId:'S',checkpointId:'C',gmId:'OLD',expectedFrom:0,expectedTo:600}}}}]};await ledger.upsertClockCommit(commit);const clock=createClock({game:{time:{worldTime:600}},ledger,isAuthority:()=>true});assert.equal((await clock.reconcile(commit)).status,'confirmed');await ledger.upsertClockCommit({...commit,id:'NO_PROOF',evidence:[]});assert.equal((await clock.reconcile({...commit,id:'NO_PROOF'})).status,'uncertain');
});
test('owner reconciliation reads an exact saved native completion and refuses a mismatching operation',async()=>{
 const actor={uuid:'Actor.H',flags:{[M]:{explorationExecutions:{A:{activityId:'A',actorUUID:'Actor.H',operationId:'treat-wounds',state:'done',result:{status:'confirmed',proof:{useId:'A',checkIds:[],resultIds:[],receiptIds:[],poolReceipts:[]}}}}}}},user={id:'NEW',isGM:true};const owner=createExplorationOwnerOperations({game:{user,users:{activeGM:user},messages:new Map()},fromUuid:async()=>actor});assert.equal((await owner.reconcile(input)).status,'confirmed');actor.flags[M].explorationExecutions.A.operationId='focus-healing';assert.equal((await owner.reconcile(input)).status,'uncertain');
});
