import {test} from 'node:test';
import assert from 'node:assert/strict';
import {recoveryProposals,chooseNext} from '../../scripts/exploration/policy.mjs';
import {wardCapacity} from '../../scripts/exploration/capabilities.mjs';

function fixture({medicineRank=2,natureRank=4,ward=true,natural=true,assuranceSkills=[],count=10}={}){
 const healer={actorUUID:'H',medicine:{rank:medicineRank},nature:{rank:natureRank},slugs:[...natural?['natural-medicine']:[],...ward?['ward-medic']:[],'risky-surgery'],assuranceSkills,items:[],focus:{value:0,max:0},pool:{poolUUID:'H',ready:true},hp:{value:100,max:100},modeOfBeing:'living',wardCapacity:wardCapacity({wardMedic:ward,medicineRank}),continualRecovery:true};
 const patients=Array.from({length:count},(_,i)=>({actorUUID:'P'+String(i).padStart(2,'0'),medicine:{rank:0},nature:{rank:0},slugs:[],assuranceSkills:[],items:[],focus:{value:0,max:0},pool:{poolUUID:'Pool'+i,ready:true},hp:{value:i+1,max:100},modeOfBeing:'living'}));
 const session={goalsByPool:patients.map(p=>({poolUUID:p.pool.poolUUID,targetHP:100})),treatmentRank:'trained',useAssurance:true,riskySurgery:true,budgetEndsAt:10000};
 return {healer,patients,session};
}
function proposals(f,{now=100,activities=[],providerIds=['treat-wounds']}={}){return recoveryProposals({actors:[f.healer,...f.patients],activities,session:f.session,now,providerIds}).filter(p=>p.options.skill==='nature')}
const group=rows=>rows.find(p=>p.patientUUIDs.length>1);
for(const [medicineRank,capacity]of [[1,1],[2,2],[3,4],[4,8]])test('Nature legendary uses prepared Medicine Ward capacity '+capacity,()=>{const f=fixture({medicineRank});const rows=proposals(f);assert.equal(rows.filter(p=>p.patientUUIDs.length===1).length,10);assert.equal(group(rows)?.patientUUIDs.length??1,capacity)});
for(const option of [{ward:false},{natural:false},{natureRank:0}])test('Nature group requires its own skill/source and Ward capacity '+JSON.stringify(option),()=>{const rows=proposals(fixture(option));assert.equal(group(rows),undefined);if(option.natural===false||option.natureRank===0)assert.equal(rows.length,0)});
test('group selects current-ready living unique pools by deficit then UUID',()=>{const f=fixture({medicineRank:3,count:7});f.patients[1].pool.poolUUID=f.patients[0].pool.poolUUID;f.patients[2].cooldownExpiresAt=101;f.patients[3].modeOfBeing='undead';f.patients[4].hp.value=f.patients[5].hp.value;f.patients.reverse();const p=group(proposals(f));assert.ok(p);assert.deepEqual(p.patientUUIDs,['P00','P04','P05','P06']);assert.equal(new Set(p.hpPoolUUIDs).size,4);assert.equal(p.earliestStart,100);assert.ok(proposals(f).some(p=>p.patientUUIDs[0]==='P02'&&p.earliestStart===101))});
test('later Continual Recovery does not erase an existing ordinary immunity',()=>{const f=fixture({count:3});f.patients[0].cooldownExpiresAt=3600;const p=group(proposals(f));assert.ok(p);assert.deepEqual(p.patientUUIDs,['P01','P02']);assert.equal(proposals(f).find(p=>p.patientUUIDs[0]==='P00').earliestStart,3600)});
for(const [assuranceSkills,expected]of [[['medicine'],false],[['nature'],true]])test('group uses Nature Assurance only '+assuranceSkills.join(),()=>{const f=fixture({assuranceSkills});const p=group(proposals(f));assert.ok(p);assert.equal(p.options.assurance,expected);assert.equal(p.options.riskySurgery,false);assert.equal(p.expectedDamage,0);assert.equal(p.durationSeconds,600);assert.equal(p.options.continualRecovery,true)});
test('group DC remains limited by Nature proficiency',()=>{const f=fixture({medicineRank:4,natureRank:1});f.session.treatmentRank='expert';assert.deepEqual(proposals(f),[]);f.session.treatmentRank='trained';const p=group(proposals(f));assert.ok(p);assert.equal(p.options.rank,'trained');assert.equal(p.patientUUIDs.length,8)});
test('missing provider and unsupported context do not gain group proposals',()=>{const f=fixture();assert.deepEqual(proposals(f,{providerIds:[]}),[]);f.healer.unsupported=['mortal-healing'];assert.deepEqual(proposals(f),[])});
test('chosen Nature group keeps existing actor/patient/pool and budget exclusions',()=>{const f=fixture(),p=group(proposals(f));assert.ok(p);const select=(active,budgetEndsAt=10000)=>chooseNext({snapshot:{activities:active},proposals:[p],session:{budgetEndsAt},now:100});assert.equal(select([]).checkpointAt,700);assert.equal(select([],699).activities.length,0);const busy={state:'started',actorUUID:'Other',providerId:'treat-wounds',patientUUIDs:[p.patientUUIDs[0]],hpPoolUUIDs:[p.hpPoolUUIDs[0]],endsAt:700};assert.equal(select([busy]).activities.length,0)});
