import test from 'node:test';
import assert from 'node:assert/strict';
import {selectTreatmentRank} from '../../scripts/exploration/efficiency.mjs';
import {recoveryProposals,chooseNext} from '../../scripts/exploration/policy.mjs';
const ranks=['trained','expert','master','legendary'],dcs=[15,20,30,40];
function fixture({rank=1,risky=false,assurance=false,outcomes=[2],skill='medicine'}={}){
 const selection={riskySurgery:risky,assurance,ready:true,sourceVersion:'8.5.1',modifier:999,source:{actorUUID:'Actor.H',skill,ruleSources:['Item.Rules']},reason:null,outcomesByRank:ranks.slice(0,rank).map((r,i)=>({rank:r,dc:dcs[i],cases:Array.from({length:assurance?1:20},(_,n)=>({weight:assurance?1:0.05,outcome:outcomes[n%outcomes.length]}))}))};
 const healer={actorUUID:'Actor.H',medicine:{rank},nature:{rank},slugs:['risky-surgery'],riskySurgery:true,assuranceSkills:[skill],treatmentEstimate:{[skill]:{ready:false,selections:[selection]}},pool:{ready:true,poolUUID:'Actor.H'},hp:{value:100,max:100,temp:0},modeOfBeing:'living',items:[],focus:{value:0,max:0},wardCapacity:2};
 const patient={actorUUID:'Actor.P',pool:{ready:true,poolUUID:'Actor.P'},hp:{value:17,max:100,temp:0},healingExpectationReady:true,damageExpectationReady:true,modeOfBeing:'living',slugs:[],assuranceSkills:[],items:[],focus:{value:0,max:0}};
 const options={skill,treatmentRank:'auto',riskySurgery:risky,assurance};return {healer,patient,selection,options};
}
const estimate=(f,patients=[f.patient],deficit=p=>p.hp.max-p.hp.value)=>selectTreatmentRank(f.healer,patients,f.options,deficit);
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8, a+' != '+b);
for(const [outcome,net,damage]of [[0,-9,9],[1,-4.5,4.5],[2,4.5,4.5],[3,13.5,4.5]])test('Risky complete discrete branch '+outcome,()=>{const f=fixture({risky:true,outcomes:[outcome]});const r=estimate(f);close(r.expectedNetHealing,net);close(r.expectedHPDamage,damage);assert.equal(r.estimate,'verified-prepared-native-context')});
test('prepared cases govern outcomes without adding Risky or modifier twice',()=>{const f=fixture({risky:true,outcomes:[1,2]});close(estimate(f).expectedNetHealing,0);assert.equal(estimate(f).estimateSource.skill,'medicine')});
test('Assurance consumes single prepared outcome without natural-die adjustment and still pays Risky',()=>{const f=fixture({risky:true,assurance:true,outcomes:[2]});close(estimate(f).expectedNetHealing,4.5);close(estimate(f).expectedHPDamage,4.5);f.healer.assuranceSkills=['nature'];assert.equal(estimate(f).estimate,'fixed-dc-unverified-context')});
test('cut adds healing room; target clips after healing; explicit fixed rank is never replaced',()=>{const f=fixture({rank:2,risky:true});f.patient.hp.value=90;const r=estimate(f,[f.patient],()=>1);assert.equal(r.rank,'expert');close(r.expectedNetHealing,1);close(r.expectedHPDamage,4.5);f.options.treatmentRank='trained';const fixed=estimate(f,[f.patient],()=>1);assert.equal(fixed.rank,'trained');assert.equal(fixed.estimate,'fixed-selected-dc');let exact=0;for(let cut=1;cut<=8;cut++)for(let a=1;a<=8;a++)for(let b=1;b<=8;b++)exact+=(Math.min(91,90-cut+a+b)-90)/512;close(fixed.expectedNetHealing,exact)});
test('distinct pools pay separately and duplicate pool does not double benefit or damage',()=>{const f=fixture({risky:true});const other={...f.patient,actorUUID:'Actor.Q',pool:{ready:true,poolUUID:'Actor.Q'}};const duplicate={...f.patient,actorUUID:'Actor.X'};close(estimate(f,[f.patient,other,duplicate]).expectedNetHealing,9);close(estimate(f,[f.patient,other,duplicate]).expectedHPDamage,9)});
test('ordinary critical failure caps actual damage at remaining HP',()=>{const f=fixture({outcomes:[0]});f.patient.hp.value=2;const r=estimate(f);close(r.expectedNetHealing,-15/8);close(r.expectedHPDamage,15/8)});
test('Medic bonus uses receiving-ready model and exact rank bonus',()=>{const f=fixture({rank:2,assurance:true});f.healer.slugs.push('medic-dedication');f.options.treatmentRank='expert';close(estimate(f).expectedNetHealing,24);f.patient.healingExpectationReady=false;assert.match(estimate(f).estimateReason,/healing/) });
for(const mutate of [f=>f.patient.damageExpectationReady=false,f=>f.patient.hp.temp=1,f=>f.patient.hp.value=16,f=>f.patient.pool.poolUUID='Actor.H',f=>f.healer.riskySurgery=false,f=>f.options.skill='nature'])test('unproved Risky model retains fixed DC '+mutate.toString(),()=>{const f=fixture({risky:true});mutate(f);const r=estimate(f);assert.equal(r.estimate,'fixed-dc-unverified-context');assert.ok(r.estimateReason);assert.equal(r.expectedHPDamage,null)});
for(const mutate of [s=>s.sourceVersion='other',s=>s.source.actorUUID='Actor.X',s=>s.source.skill='nature',s=>s.outcomesByRank[0].dc=16,s=>s.outcomesByRank[0].cases.pop(),s=>s.outcomesByRank[0].cases[0].weight=1,s=>s.outcomesByRank[0].cases[0].outcome=4,s=>s.outcomesByRank.push(s.outcomesByRank[0]),s=>s.source=null])test('malformed prepared evidence falls back '+mutate.toString(),()=>{const f=fixture();mutate(f.selection);const r=estimate(f);assert.equal(r.estimate,'fixed-dc-unverified-context');assert.ok(r.estimateReason)});
test('unavailable reason is retained and absent selection cannot escape through legacy ready',()=>{const f=fixture();f.healer.treatmentEstimate.medicine.ready=true;f.healer.treatmentEstimate.medicine.modifier=99;f.selection.ready=false;f.selection.reason='unknown-predicate';assert.equal(estimate(f).estimateReason,'unknown-predicate');f.healer.treatmentEstimate.medicine.selections=[];assert.equal(estimate(f).estimate,'fixed-dc-unverified-context')});
test('invalid fixed rank never becomes an executable candidate',()=>{const f=fixture();f.options.treatmentRank='typo';assert.equal(estimate(f),null)});
test('patient model errors do not produce NaN estimated scores',()=>{const f=fixture();f.patient.hp.value=NaN;const r=estimate(f);assert.equal(r.estimate,'fixed-dc-unverified-context');assert.ok(Number.isFinite(r.expectedNetHealing))});
test('selection and patient inputs remain unchanged and estimator never calls random or Roll',()=>{const f=fixture({risky:true}),before=structuredClone(f),random=Math.random,roll=globalThis.Roll;Math.random=()=>{throw Error('RNG')};globalThis.Roll=class{constructor(){throw Error('Roll')}};try{estimate(f)}finally{Math.random=random;globalThis.Roll=roll}assert.deepEqual(f,before)});
test('policy uses net once and exposes actual estimated damage including ordinary critical failure',()=>{const f=fixture({risky:true}),g={...f.patient,actorUUID:'Actor.Q',pool:{ready:true,poolUUID:'Actor.Q'}};const session={treatmentRank:'auto',riskySurgery:true,goalsByPool:[f.patient,g].map(p=>({poolUUID:p.pool.poolUUID,targetHP:100})),budgetEndsAt:1000};const rows=recoveryProposals({actors:[f.healer,f.patient,g],activities:[],session,now:0,providerIds:['treat-wounds']});const group=rows.find(p=>p.patientUUIDs.length===2);close(group.expectedNetHealing,9);close(group.expectedDamage,9);assert.equal(group.options.estimateSource.skill,'medicine');assert.equal(chooseNext({snapshot:{activities:[]},proposals:[group],session,now:0}).activities.length,1);
 const ordinary=fixture({outcomes:[0]});const proposals=recoveryProposals({actors:[ordinary.healer,ordinary.patient],activities:[],session:{...session,riskySurgery:false,goalsByPool:[{poolUUID:'Actor.P',targetHP:100}]},now:0,providerIds:['treat-wounds']});close(proposals[0].expectedDamage,4.5);
});

for(const same of ['actor','pool'])test('new origin-only prepared context does not prove ordinary self treatment '+same,()=>{const f=fixture();if(same==='actor')f.patient.actorUUID=f.healer.actorUUID;else f.patient.pool.poolUUID=f.healer.pool.poolUUID;const r=estimate(f);assert.equal(r.estimate,'fixed-dc-unverified-context');assert.match(r.estimateReason,/self|capacity/) });
test('malformed rule sources are not presented as native evidence',()=>{const f=fixture();f.selection.source.ruleSources=[null];assert.equal(estimate(f).estimate,'fixed-dc-unverified-context')});
test('healing-only prepared table needs no damage model, but one unsafe legal rank prevents optimization',()=>{const f=fixture({rank:2});f.patient.damageExpectationReady=false;f.patient.hp.temp=3;assert.equal(estimate(f).estimate,'verified-prepared-native-context');f.selection.outcomesByRank[1].cases[0].outcome=0;assert.equal(estimate(f).estimate,'fixed-dc-unverified-context')});
test('same patient pool with inconsistent snapshots is not an exact estimate',()=>{const f=fixture();const other={...f.patient,actorUUID:'Actor.X',hp:{...f.patient.hp,value:80}};assert.equal(estimate(f,[f.patient,other]).estimate,'fixed-dc-unverified-context')});
