/**
 * PF2e Action Display Names
 * Maps action slugs to their display names
 */

export const PF2E_ACTION_DISPLAY_NAMES = {
  'follow-the-expert': '跟随专家',
  seek: '搜索',
  'sense-direction': '辨别方向',
  'sense-motive': '察言观色',
  balance: '保持平衡',
  'tumble-through': '翻滚',
  'maneuver-in-flight': '空中机动',
  squeeze: '挤入',
  'recall-knowledge': '回忆知识',
  'decipher-writing': '解译文书',
  'identify-magic': '辨识魔法',
  'learn-spell': '学习法术',
  'borrow-an-arcane-spell': '借阅奥术法术',
  climb: '攀爬',
  'force-open': '破拆',
  grapple: '擒拿',
  'high-jump': '跳高',
  'long-jump': '跳远',
  shove: '推撞',
  swim: '游泳',
  trip: '摔绊',
  disarm: '卸武',
  reposition: '移位',
  repair: '修理',
  craft: '制作',
  'identify-alchemy': '辨识炼金术',
  'create-a-diversion': '分神',
  impersonate: '乔装',
  lie: '说谎',
  feint: '虚招',
  'gather-information': '搜集信息',
  'make-an-impression': '建立印象',
  request: '请求',
  coerce: '胁迫',
  demoralize: '挫败士气',
  'administer-first-aid': '急救',
  'treat-disease': '治疗疾病',
  'treat-poison': '治疗中毒',
  'treat-wounds': '治疗伤势',
  'command-an-animal': '指挥动物',
  perform: '表演出演',
  'create-forgery': '伪造文书',
  subsist: '维求生生',
  'conceal-an-object': '隐藏物件',
  'avoid-notice': '避人耳目',
  hide: '躲藏',
  sneak: '潜行',
  track: '追踪',
  'cover-tracks': '掩盖行踪',
  'palm-an-object': '手上功夫',
  steal: '盗窃',
  'pick-a-lock': '撬开锁锁',
  'disable-device': '解除装置',
  'access-infosphere': '接入信息网',
  hack: '入侵',
  'operate-device': '操作装置',
  drive: '驾驶',
  navigate: '导航',
  'plot-course': '规划航线',
  'run-over': '碾压',
  stop: '停止',
  stunt: '特技',
  'take-control': '接管',
};

/**
 * PF2e Action Variants
 * Maps action slugs to their available variants with display names
 */
export const PF2E_ACTION_VARIANTS = {
  'create-a-diversion': [
    { slug: 'distracting-words', name: '令人分心的话语' },
    { slug: 'gesture', name: '手势' },
    { slug: 'trick', name: '花招' },
  ],
  perform: [
    { slug: 'acting', name: '戏剧' },
    { slug: 'comedy', name: '喜剧' },
    { slug: 'dance', name: '舞蹈' },
    { slug: 'keyboards', name: '键盘乐' },
    { slug: 'oratory', name: '演说' },
    { slug: 'percussion', name: '打击乐' },
    { slug: 'singing', name: '歌唱' },
    { slug: 'strings', name: '弦乐' },
    { slug: 'winds', name: '吹奏乐' },
  ],
  'administer-first-aid': [
    { slug: 'stabilize', name: '稳定伤势' },
    { slug: 'stop-bleeding', name: '止血' },
  ],
  // sf2e-anachronism variants
  drive: [
    { slug: 'drive1', name: '驾驶（1动作）' },
    { slug: 'drive2', name: '驾驶（2动作）' },
    { slug: 'drive3', name: '驾驶（3动作）' },
  ],
  stunt: [
    { slug: 'back-off', name: '后撤' },
    { slug: 'barrel-roll', name: '桶滚翻' },
    { slug: 'drift', name: '漂移' },
    { slug: 'evade', name: '规避' },
    { slug: 'flip-and-burn', name: '翻转燃烧' },
    { slug: 'flyby', name: '掠过' },
    { slug: 'turn-in-place', name: '原地转向' },
  ],
};
