import test from 'node:test';
import assert from 'node:assert/strict';
import {createDisruptPreyExecutor} from '../scripts/disrupt-prey-executor.mjs';
import {rollDisruptPreyAttack} from '../scripts/disrupt-prey-strike.mjs';
import {DISRUPT_PREY_SOURCE} from '../scripts/disrupt-prey-rules.mjs';
const ID='pf2e-third-party-automation',clone=x=>structuredClone(x),tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture({lostReply=false,stage='attack'}={}){
 const hooks=new Map(),windows=[];let sequence=0,evaluations=0,requests=0,ownerTask;
 const Hooks={on(event,fn){const id=++sequence;hooks.set(id,{event,fn});return id},off(_event,id){hooks.delete(id)},call(event,...args){for(const h of [...hooks.values()])if(h.event===event)h.fn(...args)}};
 const gm={id:'gm',isGM:true,active:true,settings:{}},user={id:'owner',isGM:false,active:true,settings:{}},users=new Map([[gm.id,gm],[user.id,user]]);users.activeGM=gm;
 const actor={id:'pc',uuid:'Actor.pc',type:'character',flags:{},items:new Map(),system:{actions:[]},synthetics:{tokenMarks:new Map()},getReach:()=>5,testUserPermission:u=>u===user||u===gm,async update(changes){for(const [path,value]of Object.entries(changes)){let at=this;const keys=path.split('.');for(const k of keys.slice(0,-1))at=at[k]??={};at[keys.at(-1)]=clone(value)}Hooks.call('updateActor',this,changes)}};
 const enemy={id:'enemy',uuid:'Actor.enemy'},scene={id:'s',tokens:new Map()},token=a=>{const t={id:a.id,uuid:`Scene.s.Token.${a.id}`,documentName:'Token',actor:a,parent:scene};t.object={document:t,distanceTo:()=>5};scene.tokens.set(t.id,t);return t},origin=token(actor),target=token(enemy);
 const feat={id:'feat',type:'feat',sourceId:DISRUPT_PREY_SOURCE,actor},item={id:'sword',uuid:actor.uuid+'.Item.sword',type:'weapon',actor,isMelee:true,isRanged:false};actor.items.set(feat.id,feat);actor.items.set(item.id,item);actor.synthetics.tokenMarks.set(target.uuid,['hunted-prey']);
 const claim={nonce:'nonce',eventId:'event',claimKey:'claim',actorUuid:actor.uuid,actorId:actor.id,tokenUuid:origin.uuid,targetUuid:target.uuid,targetTokenUuid:target.uuid,targetActorUuid:enemy.uuid,targetActorId:enemy.id,weaponKey:item.uuid+'#base',itemUuid:item.uuid,userId:user.id,epoch:'epoch',map:0,state:stage==='attack'?'claimed':'attack-rolled',...(stage==='damage'?{checkId:'original-check',degree:2}:{})};
 const event={eventId:claim.eventId,nonce:claim.nonce,actorUuid:actor.uuid,tokenUuid:origin.uuid,sourceActorUuid:enemy.uuid,sourceTokenUuid:target.uuid,userId:user.id,weaponKey:claim.weaponKey,map:0,status:'choosing',stage:claim.state};actor.flags[ID]={disruptPrey:{events:[event],reactions:[clone(claim)]}};
 const messages=new Map(),docs=new Map([actor,item,origin,target,enemy].map(d=>[d.uuid,d])),game={user,users,actors:new Map([[actor.id,actor],[enemy.id,enemy]]),scenes:new Map([[scene.id,scene]]),messages};
 const createMessage=async data=>{const message={...data,author:users.get(data.author),id:'card'+(messages.size+1),actor,isCheckRoll:data.flags.pf2e.context.type==='attack-roll',isDamageRoll:data.flags.pf2e.context.type==='damage-roll',rolls:data.rolls};messages.set(message.id,message);Hooks.call('createChatMessage',message);return message};
 const check={_evaluated:true,total:21,options:{degreeOfSuccess:2},toJSON(){return {evaluated:true,total:this.total,options:this.options}}};
 const strike={type:'strike',ready:true,item,variants:[{async roll(options){let finish;const pending=new Promise(resolve=>finish=resolve),app={context:{options:options.options},resolve:value=>finish(value),close(){this.resolve(false)}};windows.push(app);Hooks.call('renderCheckModifiersDialog',app);if(!await pending)return null;evaluations++;const data={author:user.id,speaker:{actor:actor.id,scene:scene.id,token:origin.id},flavor:'<h4 class="action">Strike</h4>',rolls:[check],flags:{pf2e:{origin:{actor:actor.uuid,uuid:item.uuid,type:item.type},context:{type:'attack-roll',action:'strike',actor:actor.id,token:origin.id,target:{actor:enemy.uuid,token:target.uuid},origin:{actor:actor.uuid,token:origin.uuid},mapIncreases:0,outcome:'success',options:[...options.options,'item:melee','item:id:sword']}}}};await options.callback(check,'success',{toObject:()=>data});return check}}]};actor.system.actions=[strike];
 const config={game,Hooks,fromUuid:async uuid=>docs.get(uuid),timeoutMs:10,authorizeDamage:async()=>()=>{},rollAttack:args=>rollDisruptPreyAttack({...args,Hooks,createMessage})};
 const owner=createDisruptPreyExecutor(config),gmGame={...game,user:gm},executor=createDisruptPreyExecutor({...config,game:gmGame});executor.register({socket:{register(){},executeAsUser(_name,_id,payload){requests++;ownerTask=owner.ownerRoll(payload,gm);ownerTask.catch(()=>{});return lostReply?new Promise(()=>{}):ownerTask.then(value=>({ok:true,value}),error=>({ok:false,error:error.message}))}}});
 const payload={actorUuid:actor.uuid,nonce:claim.nonce,claimKey:claim.claimKey,stage,...stage==='damage'?{checkId:claim.checkId}:{}};
 const run=()=>executor.performStrike({actor,token:origin,target,user,claim,option:{key:claim.weaponKey,map:0},onAttack:async({messageId})=>{const c=actor.flags[ID].disruptPrey.reactions[0];Object.assign(c,{state:'done',checkId:messageId,degree:1});Object.assign(event,{stage:'done',status:'done'})},onDamage:async()=>{},onApplying:async()=>{},onApplied:async()=>{}});
 return {actor,item,origin,target,user,gm,game,gmGame,docs,messages,windows,hooks,Hooks,claim,payload,owner,executor,config,strike,createMessage,check,event,run,get ownerTask(){return ownerTask},get evaluations(){return evaluations},get requests(){return requests}};
}
test('Disrupt owner native window has no RPC UI deadline and still saves one accepted stage',async()=>{
 const f=fixture(),pending=f.owner.ownerRoll(f.payload,f.gm).then(value=>({value}),error=>({error}));await new Promise(resolve=>setTimeout(resolve,30));assert.equal(f.windows.length,1);assert.equal(f.evaluations,0);await f.windows[0].resolve(true);const result=await pending;if(result.error)throw result.error;assert.equal(f.messages.size,1);assert.equal(f.evaluations,1);assert.equal(f.actor.flags[ID].disruptPreyExecutions.records[0].status,'done');assert.equal(f.hooks.size,0);
});
for(const event of ['disconnect','handoff'])test(`Disrupt ${event} closes only its native window before evaluation and cannot replay`,async()=>{
 const f=fixture(),pending=f.owner.ownerRoll(f.payload,f.gm).then(value=>({value}),error=>({error}));await tick();const app=f.windows[0];assert.ok(app);if(event==='disconnect')f.user.active=false;else f.game.users.activeGM={id:'new',active:true,isGM:true};f.Hooks.call('userConnected',event==='disconnect'?f.user:f.gm,false);await tick();await app.resolve(true);const result=await pending;assert.ok(result.error);assert.equal(f.evaluations,0);assert.equal(f.messages.size,0);assert.equal(f.hooks.size,0);await assert.rejects(f.owner.ownerRoll(f.payload,f.gm));assert.equal(f.evaluations,0);
});

test('Disrupt exact saved attack stage wins when its owner RPC reply never arrives',async()=>{
 const f=fixture({lostReply:true});let finished=false;
 // Native failure ends after this one attack, so the GM's durable callback
 // can be checked without introducing a damage or application fixture.
 f.check.options.degreeOfSuccess=1;const native=f.strike.variants[0].roll;f.strike.variants[0].roll=async options=>native({...options,callback:async(roll,_outcome,raw)=>{const data=raw.toObject();data.flags.pf2e.context.outcome='failure';return options.callback(roll,'failure',{toObject:()=>data})}});
 const pending=f.run().then(value=>{finished=true;return {value}},error=>{finished=true;return {error}});await tick();await f.windows[0].resolve(true);await f.ownerTask;await tick();assert.equal(finished,true);const result=await pending;if(result.error)throw result.error;assert.equal(result.value.degree,1);assert.equal(f.requests,1);assert.equal(f.evaluations,1);assert.equal(f.messages.size,1);assert.equal(f.hooks.size,0);
});

function prepareDamage(f){
 const {actor,item,origin,target,claim}=f,roll={_evaluated:true,total:8,options:{degreeOfSuccess:2},toJSON(){return {evaluated:true,total:this.total}}},pf={origin:{actor:actor.uuid,uuid:item.uuid,type:item.type},context:{type:'attack-roll',action:'strike',actor:actor.id,token:origin.id,target:{actor:target.actor.uuid,token:target.uuid},origin:{actor:actor.uuid,token:origin.uuid},mapIncreases:0,outcome:'success',options:['item:melee','item:id:sword','action:reaction','action:disrupt-prey',`${ID}:disrupt-attack:${claim.nonce}`]}};
 const attack={id:claim.checkId,actor,author:f.user,speaker:{actor:actor.id,scene:'s',token:origin.id},isCheckRoll:true,rolls:[roll],flags:{pf2e:pf,[ID]:{disruptPreyReaction:{nonce:claim.nonce,claimKey:claim.claimKey,actorUuid:actor.uuid,weaponKey:claim.weaponKey}}}};f.messages.set(attack.id,attack);
 f.strike.damage=async options=>{let finish;const pending=new Promise(resolve=>finish=resolve),app={context:{options:options.options},resolve:value=>finish(value),close(){this.resolve(false)}};f.windows.push(app);f.Hooks.call('renderDamageModifierDialog',app);if(!await pending)return null;await f.createMessage({author:f.user.id,speaker:clone(attack.speaker),rolls:[roll],flags:{pf2e:{origin:clone(pf.origin),strike:{actor:actor.uuid,damaging:true},context:{...clone(pf.context),type:'damage-roll',sourceType:'attack',options:[...options.options,'item:melee','item:id:sword']}}}});return roll};
 return attack;
}
test('a Disrupt damage window waits beyond the old timeout and keeps its exact hit stage',async()=>{
 const f=fixture({stage:'damage'});prepareDamage(f);const pending=f.owner.ownerRoll(f.payload,f.gm).then(value=>({value}),error=>({error}));await new Promise(resolve=>setTimeout(resolve,30));assert.equal(f.messages.size,1);assert.equal(f.windows.length,1);await f.windows[0].resolve(true);const result=await pending;if(result.error)throw result.error;assert.equal(f.messages.size,2);assert.equal(f.actor.flags[ID].disruptPreyExecutions.records[0].stage,'damage');assert.equal(f.actor.flags[ID].disruptPreyExecutions.records[0].status,'done');assert.equal(f.hooks.size,0);
});
for(const invalid of ['disconnect','handoff','deleted-attack'])test(`a Disrupt damage window closes on ${invalid} without publishing or authorizing another stage`,async()=>{
 const f=fixture({stage:'damage'}),attack=prepareDamage(f),pending=f.owner.ownerRoll(f.payload,f.gm).then(value=>({value}),error=>({error}));await tick();assert.equal(f.windows.length,1);if(invalid==='disconnect')f.user.active=false;else if(invalid==='handoff')f.game.users.activeGM={id:'new',active:true,isGM:true};else f.messages.delete(attack.id);f.Hooks.call(invalid==='deleted-attack'?'deleteChatMessage':'userConnected',invalid==='deleted-attack'?attack:f.user,false);await f.windows[0].resolve(true);const result=await pending;assert.ok(result.error);assert.equal(f.messages.size,invalid==='deleted-attack'?0:1);assert.equal(f.hooks.size,0);assert.equal(f.actor.flags[ID].disruptPreyExecutions.records[0].status,'uncertain');
});
