import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {createMedicActions} from '../scripts/medic-actions.mjs';
const M='pf2e-third-party-automation';
function doc(data){return Object.assign(data,{async update(changes){for(const [path,value]of Object.entries(changes)){const keys=path.split('.');let at=this;for(const key of keys.slice(0,-1))at=at[key]??={};at[keys.at(-1)]=structuredClone(value);}return this;}});}
function fixture({degree=2,branch='treat-condition',rollMutation=()=>{},facts={dc:21,restricted:false,continuous:false}}={}){
 const gm={id:'gm',isGM:true,active:true},owner={id:'owner',active:true},users=new Map([[gm.id,gm],[owner.id,owner]]);users.activeGM=gm;
 const feat=(id,source)=>doc({id,uuid:`Actor.healer.Item.${id}`,type:'feat',_stats:{compendiumSource:`Compendium.pf2e.feats-srd.Item.${source}`},system:{traits:{value:[]}}});
 const treat=feat('treat','rfnEcjxIFqwlJwJT'),visit=feat('visit','1fBHZpM3Z3MQtzvi'),bm=feat('bm','wYerMk6F1RZb0Fwt');
 const actor=doc({id:'healer',uuid:'Actor.healer',type:'character',items:new Map(),flags:{},handsFree:1,system:{attributes:{},movement:{speeds:{land:{value:25}}}},testUserPermission:u=>u===owner||u===gm});
 for(const item of [treat,visit,bm,{id:'kit',type:'equipment',_stats:{compendiumSource:'Compendium.pf2e.equipment-srd.Item.s1vB3HdXjMigYAnY'},system:{quantity:1,equipped:{carryType:'worn'}}}]){item.actor=actor;actor.items.set(item.id,item);}
 const patient=doc({id:'patient',uuid:'Actor.patient',type:'character',items:new Map(),flags:{}});
 const condition=doc({id:'condition',uuid:'Actor.patient.Item.condition',actor:patient,type:'condition',slug:'clumsy',system:{value:{value:2}},async delete(){patient.items.delete(this.id);}});patient.items.set(condition.id,condition);
 const scene={id:'scene',tokens:new Map()};
 const healer={id:'h',uuid:'Scene.scene.Token.h',documentName:'Token',actor,parent:scene,x:0,y:0};
 const target={id:'t',uuid:'Scene.scene.Token.t',documentName:'Token',actor:patient,parent:healer.parent,x:100,y:0};
 scene.tokens.set(healer.id,healer);scene.tokens.set(target.id,target);
 actor.getActiveTokens=()=>[{document:healer}];
 const game={user:gm,users,scenes:new Map([[scene.id,scene]]),messages:new Map(),combat:{id:'fight',started:true,round:1,turn:0,combatant:{actor}},modules:new Map()};
 const records={rolls:0,delegated:[],commits:[],nativeClients:[],requests:[]};
 const entities=new Map([actor,patient,healer,target,treat,visit,condition].map(x=>[x.uuid,x]));
 const deps={game,fromUuid:async uuid=>entities.get(uuid),choose:async({choices})=>choices.find(c=>c.value===branch)?.value??choices[0]?.value,requestFacts:async()=>facts,distance:()=>5,commitActivity:async x=>records.commits.push(x.cost),delegateTreatment:async x=>{
  records.delegated.push([x.branch,x.actor.uuid,x.target.uuid,x.user.id]);
  const proof={nonce:x.continuation.nonce,cardId:x.message.id,actorUuid:actor.uuid,targetUuid:target.uuid,branch:x.branch,checkKind:'statistic',checkId:'delegated-check'};
  const check=doc({id:'delegated-check',author:owner,speaker:{actor:actor.id},rolls:[{total:25,options:{degreeOfSuccess:2}}],flags:{pf2e:{context:{type:'skill-check',outcome:'success',options:[`${M}:medic-${x.branch==='battle-medicine'?'workbench':'native'}:${proof.nonce}`],target:{actor:patient.uuid,token:target.uuid}}},[M]:{[x.branch==='battle-medicine'?'medicWorkbench':'medicNative']:proof}}});game.messages.set(check.id,check);
  const result=doc({id:'delegated-result',author:owner,speaker:{actor:actor.id},flags:{treat_wounds_battle_medicine:{id:target.id,healerId:actor.id,dos:2,healing:8},[M]:{medicWorkbench:proof}}});game.messages.set(result.id,result);
  return {status:'delegated',checkId:check.id,...x.branch==='battle-medicine'?{resultId:result.id}:{}};
 },rollCheck:async({nonce,dc})=>{
  records.rolls++;await rollMutation({condition,game,actor,target});
  const roll={total:25,options:{degreeOfSuccess:degree}};
  const check=doc({id:`check${records.rolls}`,uuid:`ChatMessage.check${records.rolls}`,speaker:{actor:actor.id},author:owner,rolls:[roll],flags:{pf2e:{context:{type:'skill-check',options:[`${M}:medic:${nonce}`],dc:{value:dc},outcome:['criticalFailure','failure','success','criticalSuccess'][degree],target:{actor:patient.uuid,token:target.uuid}}}}});game.messages.set(check.id,check);return {roll,message:check};
 }};
 const ownerGame={...game,user:owner},clientHandlers=new WeakMap();
 function create(client=game){
  const handlers=new Map();clientHandlers.set(client,handlers);
  const api=createMedicActions({...deps,game:client,rollCheck:deps.rollCheck?async args=>{records.nativeClients.push(client.user.id);return deps.rollCheck(args);}:undefined,delegateTreatment:async args=>{records.nativeClients.push(client.user.id);return deps.delegateTreatment(args);}});
  api.register({Hooks:{on(_event,fn){return fn;},off(){}},socket:{register(name,fn){handlers.set(name,fn);},async executeAsUser(name,userId,payload){records.requests.push({name,userId,payload});assert.equal(userId,owner.id);create(ownerGame);const handler=clientHandlers.get(ownerGame).get(name);assert.equal(typeof handler,'function');return handler.call({socketdata:{userId:client.user.id}},payload);}}});
  return api;
 }
 const api=create();
 function message(item=treat,id='use',nonce=id){const m=doc({id,uuid:`ChatMessage.${id}`,author:owner,speaker:{actor:actor.id,scene:'scene',token:'h'},flags:{pf2e:{origin:{uuid:item.uuid,type:'feat'}},[M]:{usageInput:{actualUse:true,targetUuids:[target.uuid]},medicInput:{nonce}}}});game.messages.set(id,m);return m;}
 const context=(m=message(),item=treat)=>({actor,item,message:m,user:owner,action:item===visit?'medic:doctors-visitation':'medic:treat-condition'});
 const callOwner=async(payload,requester=gm)=>{create(ownerGame);const handler=clientHandlers.get(ownerGame).get('medic:execute');assert.equal(typeof handler,'function');return handler.call({socketdata:{userId:requester.id}},payload);};
 return {api,create,callOwner,deps,game,ownerGame,actor,patient,condition,healer,target,treat,visit,records,message,context,owner,gm};
}
for(const [degree,want] of [[0,3],[1,2],[2,1],[3,null]])test(`applies native degree ${degree} to the selected embedded condition only`,async()=>{const f=fixture({degree});await f.api.executeUsage(f.context());assert.equal(f.patient.items.get('condition')?.system.value.value??null,want);assert.equal(f.records.rolls,1);});
test('two clients/recreated provider cannot replay one original card or cloned nonce',async()=>{const f=fixture();const ctx=f.context();await Promise.all([f.api.executeUsage(ctx),f.create().executeUsage(ctx)]);assert.equal(f.condition.system.value.value,1);assert.equal(f.records.rolls,1);await assert.rejects(()=>f.api.executeUsage(f.context(f.message(f.treat,'copy','use'))));assert.equal(f.records.rolls,1);});
test('condition changed during native dialog is not overwritten',async()=>{const f=fixture({rollMutation:({condition})=>condition.system.value.value=4});await assert.rejects(()=>f.api.executeUsage(f.context()));assert.equal(f.condition.system.value.value,4);});
test('a condition granted by a source during the native roll is not detached or reduced',async()=>{const f=fixture({rollMutation:({condition})=>{condition.flags={pf2e:{grantedBy:{id:'source-effect'}}};}});await assert.rejects(()=>f.api.executeUsage(f.context()));assert.equal(f.condition.system.value.value,2);assert.deepEqual(f.condition.flags.pf2e.grantedBy,{id:'source-effect'});assert.equal(f.patient.items.get('condition'),f.condition);});
test('rerolled native receipt is rejected',async()=>{const f=fixture();const original=f.deps.rollCheck;f.deps.rollCheck=async a=>{const r=await original(a);r.message.flags.pf2e.context.isReroll=true;return r;};await assert.rejects(()=>f.create().executeUsage(f.context()));assert.equal(f.condition.system.value.value,2);});
for(const [name,change]of [['non-owner',f=>f.owner.active=false],['draft/send',f=>f.ctx.message.flags[M].usageInput.actualUse=false],['foreign actor',f=>f.ctx.message.speaker.actor='other'],['inactive GM',f=>f.game.users.activeGM={id:'elsewhere'}]])test(`rejects ${name} before rolling`,async()=>{const f=fixture();f.ctx=f.context();change(f);await assert.rejects(()=>f.api.executeUsage(f.ctx));assert.equal(f.records.rolls,0);});
for(const [branch,cost]of [['battle-medicine',1],['treat-poison',1],['administer-first-aid',2],['treat-condition',2]])test(`Visitation ${branch} commits ${cost} actions once and waits for the owner's movement confirmation`,async()=>{const f=fixture({branch});const m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));assert.deepEqual(f.records.commits,[cost]);assert.equal(f.records.rolls,0);await assert.rejects(()=>f.api.continueUsage(m,f.owner));await f.api.continueUsage(m,f.owner,{movementConfirmed:true});await f.api.continueUsage(m,f.owner,{movementConfirmed:true});assert.equal(f.records.rolls,branch==='treat-condition'?1:0);assert.equal(f.records.delegated.length,branch==='treat-condition'?0:1);if(branch!=='treat-condition')assert.deepEqual(f.records.delegated[0],[branch,'Actor.healer','Scene.scene.Token.t','owner']);});
test('cancel after movement keeps flourish committed and rejects a second Visitation in the turn',async()=>{const f=fixture();const m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));await f.api.continueUsage(m,f.owner,{cancel:true});await assert.rejects(()=>f.api.executeUsage(f.context(f.message(f.visit,'second'),f.visit)));assert.equal(f.records.rolls,0);assert.deepEqual(f.records.commits,[2]);});
test('movement confirmation validates current tools without poisoning a retry',async()=>{const f=fixture(),m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));f.actor.handsFree=0;await assert.rejects(()=>f.api.continueUsage(m,f.owner,{movementConfirmed:true}));assert.equal(f.records.rolls,0);assert.equal(m.flags[M].medic.status,'movement');f.actor.handsFree=1;await f.api.continueUsage(m,f.owner,{movementConfirmed:true});assert.equal(f.records.rolls,1);});
for(const branch of ['battle-medicine','treat-poison','administer-first-aid','treat-condition'])test(`Visitation ${branch} settles for its original patient without measuring the GM-adjudicated movement`,async()=>{
 const f=fixture({branch}),m=f.message(f.visit);let measurements=0;delete f.deps.distance;
 f.healer.object={distanceTo(){measurements++;return 60;}};f.target.object={document:f.target};
 const api=f.create();await api.executeUsage(f.context(m,f.visit));await api.continueUsage(m,f.owner,{movementConfirmed:true});
 assert.equal(m.flags[M].medic.status,'done');assert.equal(measurements,0);
 assert.equal(m.flags[M].medic.targetUuid,'Scene.scene.Token.t');assert.equal(m.flags[M].medicExecution.targetUuid,'Scene.scene.Token.t');
 assert.equal(f.records.rolls,branch==='treat-condition'?1:0);assert.equal(f.records.delegated.length,branch==='treat-condition'?0:1);
});
for(const distance of [60,undefined])test(`Treat Condition settles when native geometry reports ${distance} without measuring adjacency`,async()=>{
 const f=fixture(),m=f.message();let measurements=0;delete f.deps.distance;
 f.healer.object={distanceTo(){measurements++;return distance;}};f.target.object={document:f.target};
 await f.create().executeUsage(f.context(m));assert.equal(m.flags[M].medic.status,'done');assert.equal(f.condition.system.value.value,1);assert.equal(measurements,0);
 assert.equal(f.game.messages.get('check1').flags.pf2e.context.dc.value,21);assert.deepEqual(f.records.commits,[2]);
});
test('Treat Condition applies its native result when the original patient moves during the roll',async()=>{
 let distance=5;const f=fixture({rollMutation:()=>{distance=60;}}),m=f.message();delete f.deps.distance;
 f.healer.object={distanceTo:()=>distance};f.target.object={document:f.target};
 const api=f.create();await api.executeUsage(f.context(m));assert.equal(m.flags[M].medic.status,'done');assert.equal(f.condition.system.value.value,1);
 await api.executeUsage(f.context(m));assert.equal(f.records.rolls,1);assert.deepEqual(f.records.commits,[2]);
});
test('movement confirmation still expires with its committed turn',async()=>{const f=fixture(),m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));f.game.combat.round=2;await assert.rejects(()=>f.api.continueUsage(m,f.owner,{movementConfirmed:true}));assert.equal(f.records.rolls,0);});
test('medical settlement still requires the original patient in the source scene',async()=>{const f=fixture(),m=f.message();f.target.parent={id:'other-scene'};await assert.rejects(()=>f.api.executeUsage(f.context(m)));assert.equal(f.records.rolls,0);assert.equal(f.condition.system.value.value,2);});

for(const deleted of ['healer','target','scene'])test(`Treat Condition cannot apply after its ${deleted} is deleted during the native check`,async()=>{
 const f=fixture(),m=f.message(),original=f.deps.rollCheck;
 f.deps.rollCheck=async args=>{const result=await original(args);if(deleted==='scene')f.game.scenes.clear();else{const token=f[deleted];token.parent.tokens.delete(token.id);token.object=null;}return result};
 const api=f.create();await assert.rejects(()=>api.executeUsage(f.context(m)),/场景|Token|目标/);await api.executeUsage(f.context(m));
 assert.equal(f.condition.system.value.value,2);assert.equal(f.records.rolls,1);assert.deepEqual(f.records.commits,[2]);assert.equal(m.flags[M].medic.status,'uncertain');
});
test('an old invalid movement marker does not block the original owner confirming a legal final position',async()=>{const f=fixture(),m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));Object.assign(m.flags[M].medic,{movementIds:[],movementCost:50,invalidMovement:true});await f.api.continueUsage(m,f.owner,{movementConfirmed:true});assert.equal(f.records.rolls,1);assert.equal(m.flags[M].medic.status,'done');});
test('moving tokens causes no medical message writes or movement listener registration',async()=>{const f=fixture(),api=createMedicActions(f.deps),registered=new Map(),m=f.message(f.visit);api.register({Hooks:{on(name,fn){registered.set(name,fn);return name;},off(){}}});await api.executeUsage(f.context(m,f.visit));const before=structuredClone(m.flags[M].medic);await registered.get('moveToken')?.(f.healer,{id:'move',passed:{cost:500,waypoints:[{action:'teleport'}]}},{},f.owner);assert.deepEqual(m.flags[M].medic,before);assert.equal(registered.has('moveToken'),false);});
test('repeated combat maintenance expires locally saved movement cards without reading chat history again',async()=>{const f=fixture(),m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));await f.api.maintain();const values=f.game.messages.values.bind(f.game.messages);let reads=0;f.game.messages.values=()=>{reads++;return values();};f.game.combat.round=2;await f.api.maintain();await f.api.maintain();await f.api.maintain();assert.equal(m.flags[M].medic.status,'cancelled');assert.equal(reads,0);});
test('movement-card index accepts external create/update events and forgets deleted cards without rescanning history',async()=>{const f=fixture(),handlers=new Map(),api=createMedicActions(f.deps);api.register({Hooks:{on(name,fn){handlers.set(name,fn);return name;},off(){}}});await api.maintain();const values=f.game.messages.values.bind(f.game.messages);let reads=0;f.game.messages.values=()=>{reads++;return values();};
 const created=f.message(f.visit,'external-created');created.flags[M].medic={status:'movement',turn:'fight:0:0'};handlers.get('createChatMessage')?.(created);await api.maintain();assert.equal(created.flags[M].medic.status,'cancelled');
 const updated=f.message(f.visit,'external-updated');updated.flags[M].medic={status:'committed',turn:'fight:0:0'};handlers.get('createChatMessage')?.(updated);updated.flags[M].medic.status='movement';handlers.get('updateChatMessage')?.(updated);await api.maintain();assert.equal(updated.flags[M].medic.status,'cancelled');
 const removed=f.message(f.visit,'external-deleted');removed.flags[M].medic={status:'movement',turn:'fight:0:0'};handlers.get('createChatMessage')?.(removed);f.game.messages.delete(removed.id);handlers.get('deleteChatMessage')?.(removed);await api.maintain();assert.equal(removed.flags[M].medic.status,'movement');assert.equal(reads,0);
});
test('a full copied finished card cannot impersonate its original durable receipt',async()=>{const f=fixture();const original=f.message();await f.api.executeUsage(f.context(original));const copy=f.message(f.treat,'copy','use');copy.flags[M].medic=structuredClone(original.flags[M].medic);await assert.rejects(()=>f.api.executeUsage(f.context(copy)));assert.equal(f.records.rolls,1);});
test('a check reconstructed by native ChatMessage creation retains its valid result',async()=>{const f=fixture();const original=f.deps.rollCheck;f.deps.rollCheck=async args=>{const r=await original(args);r.message.rolls=[structuredClone(r.roll)];return r;};await f.create().executeUsage(f.context());assert.equal(f.condition.system.value.value,1);});
test('inconsistent native outcome and roll degree never apply a condition',async()=>{const f=fixture();const original=f.deps.rollCheck;f.deps.rollCheck=async args=>{const r=await original(args);r.message.flags.pf2e.context.outcome='criticalFailure';return r;};await assert.rejects(()=>f.create().executeUsage(f.context()));assert.equal(f.condition.system.value.value,2);});
test('another native flourish in this turn blocks Visitation',async()=>{const f=fixture();const prior=f.message(f.treat,'prior');prior.flags[M].medicObservedFlourishTurn='fight:1:0';prior.flags.pf2e.origin.rollOptions=['origin:action:slug:use-action','origin:item:trait:flourish'];await assert.rejects(()=>f.api.executeUsage(f.context(f.message(f.visit),f.visit)));assert.deepEqual(f.records.commits,[]);});
test('copying a movement card cannot steal its original continuation',async()=>{const f=fixture();const m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));const copied=f.message(f.visit,'copy','use');copied.flags[M].medic=structuredClone(m.flags[M].medic);await assert.rejects(()=>f.api.continueUsage(copied,f.owner,{movementConfirmed:true}));assert.equal(f.records.rolls,0);});
for(const branch of ['battle-medicine','treat-poison','administer-first-aid','treat-condition'])test(`Visitation ${branch} runs native UI on its author client and returns the exact result to the GM`,async()=>{const f=fixture({branch}),m=f.message(f.visit);f.game.user.targets=new Set([{uuid:'Scene.scene.Token.wrong'}]);f.owner.targets=new Set();await f.api.executeUsage(f.context(m,f.visit));await f.api.continueUsage(m,f.owner,{movementConfirmed:true});assert.deepEqual(f.records.nativeClients,['owner']);assert.equal(f.records.requests[0].name,'medic:execute');assert.equal(f.records.requests[0].userId,'owner');assert.equal(m.flags[M].medic.status,'done');assert.equal(m.flags[M].medicExecution.status,'done');assert.equal(m.flags[M].medicExecution.result.checkId,branch==='treat-condition'?'check1':'delegated-check');});
test('direct Treat Condition leaves source facts on GM and runs the native check on its original owner',async()=>{const f=fixture(),m=f.message();await f.api.executeUsage(f.context(m));assert.deepEqual(f.records.nativeClients,['owner']);assert.equal(f.condition.system.value.value,1);assert.equal(f.game.messages.get('check1').author.id,'owner');assert.equal(m.flags[M].medic.dc,undefined);});
test('a medical owner execution request from another player cannot open or roll anything',async()=>{const f=fixture({branch:'battle-medicine'}),m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));const response=await f.callOwner({messageId:m.id,nonce:'use'},f.owner);assert.equal(response.ok,false);assert.equal(f.records.nativeClients.length,0);assert.equal(f.records.rolls,0);});
test('missing owner connection fails without running a GM substitute or replaying a committed treatment',async()=>{const f=fixture(),m=f.message();await assert.rejects(()=>createMedicActions(f.deps).executeUsage(f.context(m)));assert.equal(f.records.rolls,0);await f.api.executeUsage(f.context(m));assert.equal(f.records.rolls,0);});
test('a foreign-author check returned by the native owner executor cannot apply a condition',async()=>{const f=fixture(),original=f.deps.rollCheck;f.deps.rollCheck=async args=>{const result=await original(args);result.message.author=f.gm;return result;};await assert.rejects(()=>f.create().executeUsage(f.context()));assert.equal(f.condition.system.value.value,2);});
test('a native callback with a different saved roll is rejected before the GM changes a condition',async()=>{const f=fixture(),original=f.deps.rollCheck;f.deps.rollCheck=async args=>{const result=await original(args);result.message.rolls=[{total:27,options:{degreeOfSuccess:3}}];result.message.flags.pf2e.context.outcome='criticalSuccess';return result;};await assert.rejects(()=>f.create().executeUsage(f.context()));assert.equal(f.condition.system.value.value,2);});
test('a disconnected native execution remains uncertain and never replays on the next card click',async()=>{const f=fixture(),m=f.message();f.deps.rollCheck=async()=>{f.records.rolls++;throw Error('owner disconnected');};await assert.rejects(()=>f.create().executeUsage(f.context(m)),/disconnected/);assert.equal(m.flags[M].medic.status,'uncertain');assert.equal(m.flags[M].medicExecution.status,'uncertain');await f.create().executeUsage(f.context(m));assert.equal(f.records.rolls,1);});
test('duplicate authenticated RPCs share the pending native execution and a recreated owner cannot replay it',async()=>{const f=fixture(),m=f.message();let release,opened;const gate=new Promise(resolve=>release=resolve),ready=new Promise(resolve=>opened=resolve),native=f.deps.rollCheck;f.deps.rollCheck=async args=>{opened();await gate;return native(args);};const run=f.create().executeUsage(f.context(m));await ready;const duplicate=f.callOwner({messageId:m.id,nonce:'use',dc:21});release();await run;const result=await duplicate;assert.equal(result.ok,true);assert.equal(result.value.checkId,'check1');assert.equal(f.records.rolls,1);const replay=await f.callOwner({messageId:m.id,nonce:'use',dc:21});assert.equal(replay.ok,false);assert.equal(f.records.rolls,1);});
for(const branch of ['treat-poison','administer-first-aid'])test(`delegated native ${branch} with no supplied DC completes without inventing an outcome`,async()=>{
 const f=fixture({branch}),original=f.deps.delegateTreatment,m=f.message(f.visit);
 f.deps.delegateTreatment=async args=>{const result=await original(args),check=f.game.messages.get(result.checkId);delete check.flags.pf2e.context.outcome;delete check.rolls[0].options.degreeOfSuccess;return result};
 const api=f.create();await api.executeUsage(f.context(m,f.visit));await api.continueUsage(m,f.owner,{movementConfirmed:true});assert.equal(m.flags[M].medic.status,'done');
 assert.equal(f.game.messages.get('delegated-check').flags.pf2e.context.outcome,undefined);
});
for(const field of ['nonce','targetUuid','checkId'])test(`a mismatched Workbench result ${field} cannot complete the activity`,async()=>{const f=fixture({branch:'battle-medicine'}),original=f.deps.delegateTreatment,m=f.message(f.visit);f.deps.delegateTreatment=async args=>{const result=await original(args);f.game.messages.get(result.resultId).flags[M].medicWorkbench={...f.game.messages.get(result.resultId).flags[M].medicWorkbench,[field]:'wrong'};return result;};const api=f.create();await api.executeUsage(f.context(m,f.visit));await assert.rejects(()=>api.continueUsage(m,f.owner,{movementConfirmed:true}));assert.notEqual(m.flags[M].medic.status,'done');});
test('default native Medicine clone preserves its check pipeline, pins target and avoids generic Counteract state',async()=>{const f=fixture({degree:3});const check=f.deps.rollCheck;f.actor.getStatistic=()=>({clone(data){assert.deepEqual(data.check.domains,['counteract-check']);return {check:{roll:async args=>{context=args;const receipt=await check({nonce:'use',dc:args.dc.value});await args.callback(receipt.roll,'criticalSuccess',receipt.message);}}};}});f.deps.rollCheck=undefined;let context;
 await f.create().executeUsage(f.context());assert.equal(context.token,f.healer);assert.deepEqual(context.target.getActiveTokens(true,true),[f.target]);assert.equal(context.target.uuid,f.patient.uuid);assert.equal(context.messageMode,'blind');assert.equal(context.dc.visible,false);assert.equal(context.dc.slug,'medicine');assert.equal(context.extraRollOptions.includes('counteract'),false);assert.equal(context.skipDialog,false);assert.equal(f.patient.items.has('condition'),false);
});
const nativePath=process.env.PF2E_NATIVE_BUNDLE??'';
const addonPath=process.env.FVTT_COUNTERACT_MAIN??'';
test('installed StatisticCheck applies Medicine-check modifiers, degree adjustment, fortune and hooks without Counteract addon contamination',{skip:!existsSync(nativePath)||!existsSync(addonPath)},async()=>{
 const source=readFileSync(nativePath,'utf8'),start=source.indexOf('StatisticCheck = class {'),end=source.indexOf(', StatisticDifficultyClass =',start),classCode=source.slice(start+'StatisticCheck = '.length,end);
 const f=fixture({degree:3}),nativeReceipt=f.deps.rollCheck;f.deps.rollCheck=undefined;const observed={before:0,after:0};
 const modifier=value=>({modifier:value,adjustments:[],clone(){return modifier(value);}});
 f.actor.isOfType=(...types)=>types.includes('creature');f.patient.isOfType=f.actor.isOfType;f.treat.isOfType=(...types)=>types.includes('feat');
 f.actor.synthetics={modifierAdjustments:{},rollNotes:{},rollTwice:{},rollSubstitutions:{}};f.actor.rules=[{beforeRoll(){observed.before++;},afterRoll(){observed.after++;}}];
 const env={o:Boolean,M:values=>[...new Set(values)],_loc:key=>key,objectHasKey:(obj,key)=>Object.hasOwn(obj,key),foundry:{utils:{mergeObject:(a,b)=>Object.assign(a,b)}},extractModifierAdjustments:()=>[],extractModifiers:(_s,domains)=>domains.includes('medicine-check')?[modifier(3)]:[],StatisticModifier:class{constructor(_label,mods){this.totalModifier=mods.reduce((sum,m)=>sum+m.modifier,0);}},CheckModifier:class{constructor(_slug,data,extra){this.modifiers=[...data.modifiers,...extra];}},CheckContext:class{constructor(data){this.data=data;}async resolve(){return {...this.data,options:new Set()};}},extractNotes:()=>[],extractDegreeOfSuccessAdjustments:()=>[{adjustments:{success:{amount:1}}}],extractRollTwice:()=> 'keep-higher',extractRollSubstitutions:()=>[{slug:'native-substitution',value:12}],CONFIG:{PF2E:{actionTraits:{healing:'Healing',manipulate:'Manipulate'}}},Math:Object.assign(Object.create(Math),{clamp:(v,min,max)=>Math.min(max,Math.max(min,v))}),sluggify:s=>s,game:f.game,Sa:{roll:async(check,context,_event,callback)=>{
  observed.context=context;assert.equal(check.modifiers.reduce((n,m)=>n+m.modifier,0),11);assert.equal(context.rollTwice,'keep-higher');assert.equal(context.substitutions[0].value,12);assert.equal(context.dosAdjustments[0].adjustments.success.amount,1);
  const addon=readFileSync(addonPath,'utf8'),begin=addon.indexOf('function pf2ecac_patchCounteractDialog('),finish=addon.indexOf('async function pf2ecac_onPTCButtonClick',begin),fn=new Function('game',`${addon.slice(begin,finish)};return pf2ecac_patchCounteractDialog;`)({user:{isGM:true}});
  fn({context},[{querySelector(){throw Error('Generic Counteract listener must not attach to this native check.');}}]);assert.deepEqual(context.dc,{value:21,visible:false,slug:'medicine'});
  const receipt=await nativeReceipt({nonce:'use',dc:21});await callback(receipt.roll,'criticalSuccess',receipt.message);return receipt.roll;
 }}};
 const NativeCheck=new Function(...Object.keys(env),`return (${classCode});`)(...Object.values(env));
 const statistic=domains=>{const parent={actor:f.actor,slug:'medicine',label:'Medicine',domains:['medicine','skill-check'],modifiers:[modifier(8)],createRollOptions:()=>new Set()};parent.check=new NativeCheck(parent,{domains:parent.domains,check:{type:'skill-check',domains}});parent.clone=({check})=>statistic([...domains,...check.domains]);return parent;};
 f.actor.getStatistic=()=>statistic(['medicine-check']);await f.create().executeUsage(f.context());assert.equal(observed.before,1);assert.equal(observed.after,1);assert.equal(observed.context.target.token,f.target);assert.equal(observed.context.domains.includes('counteract-check'),true);assert.equal(f.patient.items.has('condition'),false);
});
