import test from 'node:test';
import assert from 'node:assert/strict';
import {createRoaringSource} from '../scripts/roaring-lifecycle.mjs';
import {createRoaringEffects} from '../scripts/roaring-effects.mjs';
const ID='pf2e-third-party-automation';
function fixture(synthetic=false){
 const gm={id:'gm',active:true,isGM:true},users=new Map([[gm.id,gm]]);users.activeGM=gm;
 const game={user:gm,users,actors:new Map(),scenes:new Map()},actor={id:'target',uuid:synthetic?'Scene.scene.Token.target.Actor.target':'Actor.target',type:'npc',isToken:synthetic,flags:{},items:new Map()},writes=[];
 let scene,token,baseActor;if(synthetic){baseActor={id:'base',uuid:'Actor.base',type:'npc'};game.actors.set(baseActor.id,baseActor);scene={id:'scene',tokens:new Map()};token={id:'target',uuid:'Scene.scene.Token.target',documentName:'Token',actorId:baseActor.id,baseActor,actorLink:false,actor,parent:scene};scene.tokens.set(token.id,token);game.scenes.set(scene.id,scene);actor.token=token;}else game.actors.set(actor.id,actor);
 actor.update=async changes=>{writes.push('update');for(const [path,value]of Object.entries(changes)){const keys=path.split('.');let object=actor;for(const k of keys.slice(0,-1))object=object[k]??={};object[keys.at(-1)]=structuredClone(value);}return actor;};
 const turn={combatId:'combat',combatantId:'caster',actorUuid:'Actor.caster',tokenUuid:'Scene.scene.Token.caster',started:true,round:4,turn:0,lastTurnEnd:3,order:[{id:'caster',initiative:20,overridePriority:null}]};
 const state=createRoaringSource({sourceNonce:'source-one',castNonce:'cast-one',sourceId:'Compendium.pf2e.spells-srd.Item.czO0wbT1i320gcu9',itemUuid:'Actor.caster.Item.spell',entryUuid:'Actor.caster.Item.entry',rank:3,casterActorUuid:'Actor.caster',casterTokenUuid:'Scene.scene.Token.caster',targetActorUuid:actor.uuid,targetTokenUuid:synthetic?token.uuid:'Scene.scene.Token.target',originalMessageUuid:'ChatMessage.original',completedWorldTime:10,turn,finiteEnvelope:{start:{value:10,initiative:20},duration:{value:1,unit:'rounds',expiry:'turn-end',sustained:false}}});
 const context={userId:'owner',gmId:'gm',dc:21,paymentId:'cast-one',immunity:{checked:true,spell:false,slowed:false,fascinated:false,systemVersion:'8.5.1'}};return {game,gm,actor,scene,token,baseActor,writes,state,context};
}
for(const synthetic of [false,true])test(`original current ${synthetic?'synthetic':'world'} Actor can persist one source and repeat its claim without writing twice`,async()=>{const f=fixture(synthetic),effects=createRoaringEffects({game:f.game,fromUuid:async()=>f.actor});await effects.claim(f);await effects.claim(f);assert.deepEqual(f.writes,['update']);});
const changes=[['GM user object',f=>f.game.user={...f.gm}],['GM registry object',f=>f.game.users.set(f.gm.id,{...f.gm})],['GM inactive',f=>f.gm.active=false],['GM role',f=>f.gm.isGM=false]];
for(const synthetic of [false,true])for(const [label,change]of changes)test(`${synthetic?'synthetic':'world'} Roaring claim loses ${label} during pre-write await: no write`,async()=>{const f=fixture(synthetic);let reads=0;const effects=createRoaringEffects({game:f.game,fromUuid:async()=>{if(++reads===2)change(f);return f.actor}});await assert.rejects(effects.claim(f));assert.deepEqual(f.writes,[]);});
for(const [label,change]of [['Token',f=>f.scene.tokens.set(f.token.id,{...f.token})],['Scene',f=>f.game.scenes.set(f.scene.id,{...f.scene})],['base Actor',f=>f.game.actors.set(f.baseActor.id,{...f.baseActor})],['linked status',f=>f.token.actorLink=true],['synthetic Actor',f=>f.token.actor={...f.actor}]])test(`Roaring pre-write await replaces original synthetic ${label}: no stale source write`,async()=>{const f=fixture(true);let reads=0;const effects=createRoaringEffects({game:f.game,fromUuid:async()=>{if(++reads===2)change(f);return f.actor}});await assert.rejects(effects.claim(f));assert.deepEqual(f.writes,[]);});
test('Roaring durable write followed by GM loss stops without rewriting or retrying the source',async()=>{const f=fixture(),original=f.actor.update;f.actor.update=async changes=>{const result=await original(changes);f.gm.active=false;return result};const effects=createRoaringEffects({game:f.game,fromUuid:async()=>f.actor});await assert.rejects(effects.claim(f));assert.deepEqual(f.writes,['update']);assert.equal(effects.get(f.actor,'source-one').state.sourceNonce,'source-one');});
