import {createManualRecordBridge} from './manual-record.mjs';
import {createManualPoolCompletion} from './manual-pool-completion.mjs';
import {createManualPoolSources} from './manual-pool-source.mjs';
import {createManualPoolProof} from './manual-pool-proof.mjs';
import {createManualPoolApplication} from './manual-pool-application.mjs';
import {createLedgerSetup} from './setup.mjs';
import {createPatreonTimeCompletion} from './patreon-time-completion.mjs';
import {createPatreonManualImmunity} from './patreon-manual-immunity.mjs';
import {createPatreonManualImmunityOwner} from './patreon-manual-immunity-owner.mjs';
import {MODULE_ID,clone,normalizeNativeOwnerMap,captureRecoveryPreferences} from './schema.mjs';import {createDocumentStore,isActiveGM,requireGMRead} from './document-store.mjs';import {createLedger} from './ledger.mjs';import {createCapabilities} from './capabilities.mjs';import {createHpPools} from './hp-pool.mjs';import {createExplorationOwnerOperations} from './owner-operations.mjs';import {createNativeTreatment} from './native-treatment.mjs';import {createTreatmentProvider} from './treatment.mjs';import {createRefocusAdapter,createRefocusProvider,createFocusHealingProvider} from './refocus.mjs';import {createTimeEffects} from './time-effects.mjs';import {createClock} from './clock.mjs';import {chooseNext} from './policy.mjs';import {createCoordinator} from './coordinator.mjs';import {createManualEvents,registerWorkbenchObservation} from './manual-events.mjs';import {createRecoveryPanel} from './panel.mjs';import {getNativeActionEvents} from '../native-action-events.mjs';
export function createExplorationRuntime({game,Hooks,fromUuid,JournalEntry=globalThis.JournalEntry,nativeCasts,onError=console.error}){
 let clientNonce=crypto.randomUUID(),coordinator,panel,lastSessionId=null,registered=false,storageReady=false,activeGMId=game.users.activeGM?.id,configuredRoot=game.settings?.get?.(MODULE_ID,'explorationLedgerUUID')||'',diagnostic={status:'initializing'};
 const diagnosticMetadata={nativeVersion:String(game.system?.version??''),finiteResources:false,sharedOwnerBridge:'exploration-specific-authenticated-operation'};
 const runtimeIdentity=()=>({userId:game.user.id,clientNonce}),store=createDocumentStore({game,writerClientId:()=>clientNonce}),ledger=createLedger({...store,isAuthority:()=>isActiveGM(game),identity:runtimeIdentity}),setup=createLedgerSetup({game,store,ledger,writerClientId:()=>clientNonce}),hpPools=createHpPools({game,actorUpdateEvents:nativeCasts}),capabilities=createCapabilities({game,fromUuid,hpPools}),ownerOperations=createExplorationOwnerOperations({game,fromUuid,getHpPool:actor=>hpPools.discover(actor),ledger,runtimeIdentity,getDriverScope:id=>coordinator?.executionScope(id)});
 let manualPoolBundle,manualPoolIssuerScope;const workbenchProviders=new Map(),manualPoolMarkers=new WeakMap();
 const isPoolIssuer=()=>storageReady&&isActiveGM(game)&&manualPoolIssuerScope?.sessionId===lastSessionId&&manualPoolIssuerScope.clientNonce===clientNonce&&manualPoolIssuerScope.userId===game.user.id;
 async function beginManualPoolSource(method,args){
  const sources=manualPoolBundle?.sources,handle=await sources?.[method](...args),marker=sources?.poolMarker(handle);
  // Keep only denial metadata across replacement, including a pending begin ACK.
  if(handle&&marker)manualPoolMarkers.set(handle,Object.freeze({...marker}));return handle;
 }
 const manualPoolSources={...Object.fromEntries(['nativeCheck','nativeResult','workbenchCheck','workbenchResult'].map(key=>[key,(...args)=>manualPoolBundle?.sources[key](...args)])),beginNative:(...args)=>beginManualPoolSource('beginNative',args),beginWorkbench:(...args)=>beginManualPoolSource('beginWorkbench',args),poolMarker:handle=>{const marker=manualPoolMarkers.get(handle);return marker?{...marker}:null},observeWorkbenchProvider:witness=>{workbenchProviders.set(witness.macro,witness);manualPoolBundle?.sources.observeWorkbenchProvider(witness)}};
 const manualPoolProof={evidence:activity=>manualPoolBundle?.proof.evidence(activity)};
 const manualPoolApplication={captureFrame:(...args)=>manualPoolBundle?.application.captureFrame(...args)??null,observeCreate:(wrapped,...args)=>manualPoolBundle?manualPoolBundle.application.observeCreate(wrapped,...args):wrapped(...args),applyNativeDamage:(actor,params,native,frame)=>manualPoolBundle?manualPoolBundle.application.applyNativeDamage(actor,params,native,frame):native(params)};
 function resetManualPool(){manualPoolBundle?.sources.stop();manualPoolBundle?.completion.stop();manualPoolBundle?.application.stop();manualPoolBundle=null;if(!registered)return;
  const sources=createManualPoolSources({game,Hooks,ledger,fromUuid,hpPools,clientNonce,getSession:()=>storageReady?ledger.getSession(lastSessionId):null,isIssuer:isPoolIssuer,onEnroll:source=>manualEvents.observePoolSource(source),onSettled:id=>manualEvents.refreshPoolEvidence(id),onError});
  const completion=createManualPoolCompletion({game,ledger,fromUuid,hpPools,clientNonce,isIssuer:isPoolIssuer,resolveSource:sources.resolveSource,onSettled:request=>sources.onSettled(request),onError});
  manualPoolBundle={sources,completion,application:createManualPoolApplication({game,completion}),proof:createManualPoolProof({game,fromUuid,hpPools,resolveSource:sources.resolveSource})};for(const witness of workbenchProviders.values())sources.observeWorkbenchProvider(witness);sources.start(completion);completion.start();
 }
 const refocusAdapter=createRefocusAdapter({game,fromUuid,ownerOperations}),patreonTimeCompletion=createPatreonTimeCompletion({game,runtimeIdentity,getDriverScope:id=>coordinator?.executionScope(id)}),timeEffects=createTimeEffects({capabilities,completionAdapters:[patreonTimeCompletion]}),clock=createClock({game,Hooks,ledger,timeEffects,isAuthority:()=>isActiveGM(game)});
 const nativeActions=getNativeActionEvents({game}),patreonImmunity=createPatreonManualImmunity({game,fromUuid}),manualEvents=createManualEvents({game,Hooks,ledger,nativeActions,hpPools,manualPoolSources,manualPoolProof,patreonImmunity,observePatreonTerminal:false,bindRecordingSource:actorUUID=>patreonOwner.bindSource(actorUUID),fromUuid,sessionId:()=>storageReady?lastSessionId:null,onChange:()=>panel?.refresh(),reserveSource:(binding,intent)=>manualRecord.reserveSource(binding,intent),checkpointOptions:binding=>coordinator.manualCheckpointOptions(binding),onUnknownSource:id=>coordinator.stop(id,'unreserved-manual-source')});
 const manualRecord=createManualRecordBridge({game,fromUuid,getSession:()=>storageReady?ledger.getSession(lastSessionId):null,getActivities:async()=>storageReady?(await ledger.snapshot(lastSessionId)).activities:[],checkpointContext:()=>({sessionId:lastSessionId,worldTime:game.time.worldTime,...coordinator?.executionScope(lastSessionId)}),ownsSession:(...args)=>ledger.ownsSession(...args),enrollCheckpointActivity:(...args)=>ledger.enrollCheckpointActivity(...args),lookupCheckpointActivity:(...args)=>ledger.lookupCheckpointActivity(...args),observe:manualEvents.observe,reserveSource:(binding,intent,callerId)=>coordinator.reserveManualSource(binding,intent,callerId)});
 const patreonOwner=createPatreonManualImmunityOwner({game,fromUuid,patreonImmunity,getSession:()=>storageReady?ledger.getSession(lastSessionId):null,getActivity:id=>ledger.getActivity(id),record:proof=>manualEvents.observeNativeImmunity(proof),onError});
 const start=async config=>{if(!isActiveGM(game))throw Error('active-gm-required');const recovery=captureRecoveryPreferences(config),nativeOwnerByActor=normalizeNativeOwnerMap(config.nativeOwnerByActor,config.actorUUIDs,{manual:config.manual===true});config={...clone(config),nativeOwnerByActor,...recovery===undefined?{}:{recovery}};if((await refreshStorage()).state!=='ready')throw Error('exploration-ledger-setup-required');if(game.combat?.started&&!config.manual)throw Error('遭遇已经开始，请停止后再恢复。');if(!coordinator)throw Error('exploration-not-ready');if(game.system?.id!=='pf2e')throw Error('pf2e-system-required');const old=lastSessionId&&await ledger.getSession(lastSessionId);if(old&&['running','recording'].includes(old.status))throw Error('已有恢复会话，请先停止。');const s=await coordinator.start(config);lastSessionId=s.id;if(s.manual===true&&s.status==='recording'&&s.manualPoolIssuer?.userId===game.user.id&&s.manualPoolIssuer.clientNonce===clientNonce)manualPoolIssuerScope={sessionId:s.id,userId:game.user.id,clientNonce};await game.user.setFlag?.(MODULE_ID,'explorationSession',s.id);return s};
 function storageStatus(status){storageReady=status.state==='ready';diagnostic={...diagnostic,status:storageReady?'ready':'setup-required',ledger:status};return status}
 async function refreshStorage(){return readAsGM(async()=>storageStatus(await setup.status()))}
 async function readAsGM(operation){
  requireGMRead(game);const user=game.user,userId=user.id;
  try{return await operation()}
  finally{requireGMRead(game);if(game.user!==user||game.user.id!==userId)throw Error('exploration-user-changed')}
 }
 async function preparePanelContext(actorUUIDs){
  return readAsGM(async()=>{
  const caller=game.user,nonce=clientNonce,root=game.settings.get(MODULE_ID,'explorationLedgerUUID'),view=await setup.inspect(),id=lastSessionId,session=view.ledgerState?.sessions[id]??null;
  const uuids=[...new Set([...actorUUIDs,...session?.actorUUIDs??[]])],prepared=await capabilities.snapshot(uuids),actorsByUUID=new Map(prepared.map(actor=>[actor.actorUUID,actor]));
  const current=game.user===caller&&caller.isGM===true&&clientNonce===nonce&&game.settings.get(MODULE_ID,'explorationLedgerUUID')===root;
  const ledgerStatus=storageStatus(current||view.ledgerStatus.state==='blocked'?view.ledgerStatus:{state:'blocked',reason:'panel-context-changed'}),actors=actorUUIDs.map(uuid=>actorsByUUID.get(uuid));
  if(!current||!id||!view.ledgerState)return {actors,ledgerStatus,data:null};
  const state=view.ledgerState,data=clone({session,activities:Object.values(state.activities).filter(activity=>activity.sessionId===id),clocks:Object.values(state.clocks).filter(clock=>clock.sessionId===id)});
  return {actors,ledgerStatus,data:coordinator.describeSnapshot(data,(session?.actorUUIDs??[]).map(uuid=>actorsByUUID.get(uuid)),id)};
  });
 }
 function invalidate(reason){coordinator?.invalidate(reason);clientNonce=crypto.randomUUID();manualRecord.invalidate(reason);manualPoolIssuerScope=null;resetManualPool();clock.stop(reason);ownerOperations.invalidate?.(reason);timeEffects.invalidate(reason)}
 async function storageAction(action,options){if(!isActiveGM(game))throw Error('active-gm-required');const result=await setup[action](options);if(result.requiresReload)invalidate('revision-root-changed');await refreshStorage();panel?.refresh();return result}
 async function restoreCurrent(preferred=lastSessionId,{refreshPanel=true}={}){if(!isActiveGM(game)||!coordinator)return;const s=await coordinator.restore(preferred);if(s&&s.id!==lastSessionId){lastSessionId=s.id;if(s.manual===true&&s.status==='recording'&&s.manualPoolIssuer?.userId===game.user.id&&s.manualPoolIssuer.clientNonce===clientNonce)manualPoolIssuerScope={sessionId:s.id,userId:game.user.id,clientNonce};await game.user.setFlag?.(MODULE_ID,'explorationSession',s.id)}if(refreshPanel)panel?.refresh();return s}
 const gmAction=async(action,id,options)=>{if(!isActiveGM(game))throw Error('active-gm-required');if(!coordinator)throw Error('exploration-not-ready');if(action==='resume'&&(game.combat?.started||game.system?.id!=='pf2e'))throw Error('encounter-or-system-unavailable');const selected=id??lastSessionId,result=await coordinator[action](selected,action==='review'?{...options,userId:game.user.id}:options);if(action==='stop'){manualPoolIssuerScope=null;resetManualPool()}if(selected!==lastSessionId){lastSessionId=selected;await game.user.setFlag?.(MODULE_ID,'explorationSession',selected)}panel?.refresh();return result};
 async function bind({checkScope,damageGuard,salubriousKiss}){
  const nativeTreatment=createNativeTreatment({game,Hooks,fromUuid,ownerOperations,checkScope,damageGuard,hpPools});
  ownerOperations.registerOperation('treat-wounds',nativeTreatment.run);ownerOperations.registerOperation('treatment-extension',async(a,ctx)=>nativeTreatment.extend(a,ctx.extensionOriginal??await ledger.getActivity(a.options.extensionOf),ctx));
  const treatment=createTreatmentProvider({capabilities,nativeTreatment,ledger,ownerOperations}),refocus=createRefocusProvider({game,ledger,capabilities,refocusEvents:refocusAdapter,salubriousKiss,ownerOperations}),focus=createFocusHealingProvider({game,Hooks,fromUuid,ownerOperations,castEvents:nativeCasts,nativeTreatment});
  ownerOperations.registerOperation('refocus',refocus.complete);ownerOperations.registerOperation('focus-healing',focus.complete);focus.register();
  const providers=[treatment,{...refocus,complete:a=>ownerOperations.runActivityWithOwner(a,'refocus')},{...focus,complete:a=>ownerOperations.runActivityWithOwner(a,'focus-healing')}];
  coordinator=createCoordinator({game,fromUuid,getHpPool:actor=>hpPools.discover(actor),ledger,capabilities,providers,clock,policy:chooseNext,isAuthority:()=>isActiveGM(game),now:()=>game.time.worldTime,ownerOperations,onChange:()=>panel?.refresh(),manualEvents});
  const panelActions=Object.freeze({snapshot:id=>api.snapshot(id),stop:id=>api.stop(id),resume:id=>api.resume(id),takeover:id=>api.takeover(id),reconcile:id=>api.reconcile(id),review:(id,options)=>api.review(id,options),closeManualCheckpoint:(binding,options)=>api.closeManualCheckpoint(binding,options),openActivityCheckpoint:id=>api.openActivityCheckpoint(id),closeActivityCheckpoint:(binding,options)=>api.closeActivityCheckpoint(binding,options)});
  panel=createRecoveryPanel({game,coordinator:panelActions,capabilities,start,prepareContext:preparePanelContext,storage:{status:refreshStorage,provision:options=>storageAction('provision',options),initialize:options=>storageAction('initialize',options),select:options=>storageAction('select',options)},record:event=>api.record(event),getActivityCheckpoint:actorUUID=>api.getActivityCheckpoint(actorUUID),lookupCheckpointActivity:(...args)=>api.lookupCheckpointActivity(...args),getSessionId:()=>lastSessionId,onError});diagnostic={status:'initializing',...diagnosticMetadata};
  if(game.user?.isGM!==true){storageReady=false;lastSessionId=null;diagnostic.status='gm-read-required';return}
  const status=await refreshStorage(),previous=game.user.getFlag?.(MODULE_ID,'explorationSession');if(['ready','legacy','migration-required'].includes(status.state)){if(isActiveGM(game))await restoreCurrent(previous);else if(previous&&(await ledger.getSession(previous)))lastSessionId=previous}
 }
 async function register({socket}){if(registered)return;registered=true;resetManualPool();ownerOperations.register({socket});manualRecord.register(socket);manualEvents.start();patreonOwner.start();nativeActions.register();game.socket.on('disconnect',()=>invalidate('client-disconnected'));for(const event of ['userConnected','updateUser'])Hooks.on(event,()=>{const current=game.users.activeGM?.id;if(current!==activeGMId){activeGMId=current;invalidate('gm-changed')}if(game.user.active===false)invalidate('client-offline');if(isActiveGM(game)&&game.user.active)void restoreCurrent().catch(onError)});Hooks.on('updateSetting',setting=>{if(setting.key===`${MODULE_ID}.explorationLedgerUUID`){const next=game.settings.get(MODULE_ID,'explorationLedgerUUID')||'',previous=configuredRoot;configuredRoot=next;storageReady=false;if(previous&&next!==previous)invalidate('revision-root-changed');if(game.user?.isGM!==true){lastSessionId=null;diagnostic={status:'gm-read-required',...diagnosticMetadata};return}void refreshStorage().then(()=>panel?.refresh()).catch(onError)}});await registerWorkbenchObservation({game,Hooks,recorder:manualEvents}).catch(onError);Hooks.on('updateCombat',combat=>{if(combat.started&&lastSessionId&&isActiveGM(game))void coordinator.stop(lastSessionId,'encounter-started').catch(onError)});Hooks.on('pf2e.restForTheNight',actor=>{timeEffects.observeRest({actorUUID:actor.uuid});if(lastSessionId&&isActiveGM(game))void coordinator.stop(lastSessionId,'external-rest-time-authority').catch(onError)})}
 const api=Object.freeze({version:1,open:async uuids=>{if(!game.user.isGM){const selected=uuids??globalThis.canvas?.tokens?.controlled?.map(token=>token.actor?.uuid)??[];if(selected.length!==1)throw Error('请选择一个本人拥有的角色登记探索行动。');return panel.openActivityDeclaration(selected[0])}await refreshStorage();if(diagnostic.ledger.state!=='blocked')await restoreCurrent(lastSessionId,{refreshPanel:false});return panel.open(uuids)},start,stop:(id,reason)=>gmAction('stop',id,reason),takeover:id=>gmAction('takeover',id),resume:(id,options)=>gmAction('resume',id,options),reconcile:id=>gmAction('reconcile',id),review:(id,options)=>gmAction('review',id,options),snapshot:id=>readAsGM(()=>coordinator.snapshot(id??lastSessionId)),record:event=>manualRecord.record(event),openActivityCheckpoint:id=>gmAction('openActivityCheckpoint',id),getActivityCheckpoint:actorUUID=>manualRecord.getActivityCheckpoint(actorUUID),openActivityDeclaration:actorUUID=>panel.openActivityDeclaration(actorUUID),lookupCheckpointActivity:(...args)=>manualRecord.lookupCheckpointActivity(...args),closeActivityCheckpoint:async(binding,options)=>{if(!isActiveGM(game))throw Error('active-gm-required');const result=await coordinator.closeActivityCheckpoint(binding,options);panel?.refresh();return result},openManualCheckpoint:id=>gmAction('openManualCheckpoint',id),closeManualCheckpoint:async(binding,options)=>{if(!isActiveGM(game))throw Error('active-gm-required');const result=await coordinator.closeManualCheckpoint(binding,options);panel?.refresh();return result},reserveManualSource:(binding,intent)=>manualRecord.reserveSource(binding,intent),storage:Object.freeze({status:refreshStorage,provision:options=>storageAction('provision',options),initialize:options=>storageAction('initialize',options),select:options=>storageAction('select',options)}),diagnostic:()=>game.user?.isGM===true?{...diagnostic,time:timeEffects.diagnostic()}:{status:'gm-read-required',...diagnosticMetadata}});
 return {api,bind,register,hpPools,manualPoolApplication,ownerOperations,refocusAdapter,refocusSubscriber:{matchesActor:actor=>!!refocusAdapter.getCurrent(actor),onRefocus:event=>refocusAdapter.capture(event)}};
}
