import {createManualRecordBridge} from './manual-record.mjs';
import {createLedgerSetup} from './setup.mjs';
import {createPatreonTimeCompletion} from './patreon-time-completion.mjs';
import {MODULE_ID,clone,normalizeNativeOwnerMap} from './schema.mjs';import {createDocumentStore,isActiveGM} from './document-store.mjs';import {createLedger} from './ledger.mjs';import {createCapabilities} from './capabilities.mjs';import {createHpPools} from './hp-pool.mjs';import {createExplorationOwnerOperations} from './owner-operations.mjs';import {createNativeTreatment} from './native-treatment.mjs';import {createTreatmentProvider} from './treatment.mjs';import {createRefocusAdapter,createRefocusProvider,createFocusHealingProvider} from './refocus.mjs';import {createTimeEffects} from './time-effects.mjs';import {createClock} from './clock.mjs';import {chooseNext} from './policy.mjs';import {createCoordinator} from './coordinator.mjs';import {createManualEvents,registerWorkbenchObservation} from './manual-events.mjs';import {createRecoveryPanel} from './panel.mjs';import {getNativeActionEvents} from '../native-action-events.mjs';
export function createExplorationRuntime({game,Hooks,fromUuid,JournalEntry=globalThis.JournalEntry,nativeCasts,onError=console.error}){
 let clientNonce=crypto.randomUUID(),coordinator,panel,lastSessionId=null,registered=false,storageReady=false,activeGMId=game.users.activeGM?.id,configuredRoot=game.settings?.get?.(MODULE_ID,'explorationLedgerUUID')||'',diagnostic={status:'initializing'};
 const runtimeIdentity=()=>({userId:game.user.id,clientNonce}),store=createDocumentStore({game,writerClientId:()=>clientNonce}),ledger=createLedger({...store,isAuthority:()=>isActiveGM(game),identity:runtimeIdentity}),setup=createLedgerSetup({game,store,ledger,writerClientId:()=>clientNonce}),hpPools=createHpPools({game,actorUpdateEvents:nativeCasts}),capabilities=createCapabilities({game,fromUuid,hpPools}),ownerOperations=createExplorationOwnerOperations({game,fromUuid,getHpPool:actor=>hpPools.discover(actor),ledger,runtimeIdentity,getDriverScope:id=>coordinator?.executionScope(id)});
 const refocusAdapter=createRefocusAdapter({game,fromUuid,ownerOperations}),patreonTimeCompletion=createPatreonTimeCompletion({game,runtimeIdentity,getDriverScope:id=>coordinator?.executionScope(id)}),timeEffects=createTimeEffects({capabilities,completionAdapters:[patreonTimeCompletion]}),clock=createClock({game,Hooks,ledger,timeEffects,isAuthority:()=>isActiveGM(game)});
 const nativeActions=getNativeActionEvents({game}),manualEvents=createManualEvents({game,Hooks,ledger,nativeActions,hpPools,fromUuid,sessionId:()=>storageReady?lastSessionId:null,onChange:()=>panel?.refresh(),reserveSource:(binding,intent)=>manualRecord.reserveSource(binding,intent),checkpointOptions:binding=>coordinator.manualCheckpointOptions(binding),onUnknownSource:id=>coordinator.stop(id,'unreserved-manual-source')});
 const manualRecord=createManualRecordBridge({game,fromUuid,getSession:()=>storageReady?ledger.getSession(lastSessionId):null,observe:manualEvents.observe,reserveSource:(binding,intent,callerId)=>coordinator.reserveManualSource(binding,intent,callerId)});
 const start=async config=>{if(!isActiveGM(game))throw Error('active-gm-required');const nativeOwnerByActor=normalizeNativeOwnerMap(config.nativeOwnerByActor,config.actorUUIDs,{manual:config.manual===true});config={...clone(config),nativeOwnerByActor};if((await refreshStorage()).state!=='ready')throw Error('exploration-ledger-setup-required');if(game.combat?.started&&!config.manual)throw Error('遭遇已经开始，请停止后再恢复。');if(!coordinator)throw Error('exploration-not-ready');if(game.system?.version!=='8.5.1'&&!config.manual)throw Error('自动治疗尚未核验当前 PF2e 版本，请使用手动记录。');const old=lastSessionId&&await ledger.getSession(lastSessionId);if(old&&['running','recording'].includes(old.status))throw Error('已有恢复会话，请先停止。');const s=await coordinator.start(config);lastSessionId=s.id;await game.user.setFlag?.(MODULE_ID,'explorationSession',s.id);return s};
 async function refreshStorage(){const status=await setup.status();storageReady=status.state==='ready';diagnostic={...diagnostic,status:storageReady?'ready':'setup-required',ledger:status};return status}
 function invalidate(reason){clientNonce=crypto.randomUUID();clock.stop(reason);ownerOperations.invalidate?.(reason);timeEffects.invalidate(reason)}
 async function storageAction(action,options){if(!isActiveGM(game))throw Error('active-gm-required');const result=await setup[action](options);if(result.requiresReload)invalidate('revision-root-changed');await refreshStorage();panel?.refresh();return result}
 async function restoreCurrent(preferred=lastSessionId){if(!isActiveGM(game)||!coordinator)return;const s=await coordinator.restore(preferred);if(s&&s.id!==lastSessionId){lastSessionId=s.id;await game.user.setFlag?.(MODULE_ID,'explorationSession',s.id)}panel?.refresh();return s}
 const gmAction=async(action,id,options)=>{if(!isActiveGM(game))throw Error('active-gm-required');if(!coordinator)throw Error('exploration-not-ready');if(action==='resume'&&(game.combat?.started||game.system?.version!=='8.5.1'))throw Error('encounter-or-system-unavailable');const selected=id??lastSessionId,result=await coordinator[action](selected,action==='review'?{...options,userId:game.user.id}:options);if(selected!==lastSessionId){lastSessionId=selected;await game.user.setFlag?.(MODULE_ID,'explorationSession',selected)}panel?.refresh();return result};
 async function bind({checkScope,damageGuard,salubriousKiss}){
  const nativeTreatment=createNativeTreatment({game,Hooks,fromUuid,ownerOperations,checkScope,damageGuard,hpPools});
  ownerOperations.registerOperation('treat-wounds',nativeTreatment.run);ownerOperations.registerOperation('treatment-extension',async(a,ctx)=>nativeTreatment.extend(a,ctx.extensionOriginal??await ledger.getActivity(a.options.extensionOf),ctx));
  const treatment=createTreatmentProvider({capabilities,nativeTreatment,ledger,ownerOperations}),refocus=createRefocusProvider({game,ledger,capabilities,refocusEvents:refocusAdapter,salubriousKiss,ownerOperations}),focus=createFocusHealingProvider({game,Hooks,fromUuid,ownerOperations,castEvents:nativeCasts,nativeTreatment});
  ownerOperations.registerOperation('refocus',refocus.complete);ownerOperations.registerOperation('focus-healing',focus.complete);focus.register();
  const providers=[treatment,{...refocus,complete:a=>ownerOperations.runActivityWithOwner(a,'refocus')},{...focus,complete:a=>ownerOperations.runActivityWithOwner(a,'focus-healing')}];
  coordinator=createCoordinator({game,fromUuid,getHpPool:actor=>hpPools.discover(actor),ledger,capabilities,providers,clock,policy:chooseNext,isAuthority:()=>isActiveGM(game),now:()=>game.time.worldTime,ownerOperations,onChange:()=>panel?.refresh(),manualEvents});
  const panelActions=Object.freeze({snapshot:id=>api.snapshot(id),stop:id=>api.stop(id),resume:id=>api.resume(id),takeover:id=>api.takeover(id),reconcile:id=>api.reconcile(id),review:(id,options)=>api.review(id,options),closeManualCheckpoint:(binding,options)=>api.closeManualCheckpoint(binding,options)});
  panel=createRecoveryPanel({game,coordinator:panelActions,capabilities,start,storage:{status:refreshStorage,provision:options=>storageAction('provision',options),initialize:options=>storageAction('initialize',options),select:options=>storageAction('select',options)},record:event=>api.record(event),getSessionId:()=>lastSessionId,onError});diagnostic={status:'initializing',nativeVersion:'8.5.1',finiteResources:false,sharedOwnerBridge:'exploration-specific-authenticated-operation'};
  const status=await refreshStorage(),previous=game.user.getFlag?.(MODULE_ID,'explorationSession');if(['ready','legacy','migration-required'].includes(status.state)){if(isActiveGM(game))await restoreCurrent(previous);else if(previous&&(await ledger.getSession(previous)))lastSessionId=previous}
 }
 async function register({socket}){if(registered)return;registered=true;ownerOperations.register({socket});manualRecord.register(socket);manualEvents.start();nativeActions.register();game.socket.on('disconnect',()=>invalidate('client-disconnected'));for(const event of ['userConnected','updateUser'])Hooks.on(event,()=>{const current=game.users.activeGM?.id;if(current!==activeGMId){activeGMId=current;invalidate('gm-changed')}if(isActiveGM(game))void restoreCurrent().catch(onError)});Hooks.on('updateSetting',setting=>{if(setting.key===`${MODULE_ID}.explorationLedgerUUID`){const next=game.settings.get(MODULE_ID,'explorationLedgerUUID')||'',previous=configuredRoot;configuredRoot=next;storageReady=false;if(previous&&next!==previous)invalidate('revision-root-changed');void refreshStorage().then(()=>panel?.refresh()).catch(onError)}});await registerWorkbenchObservation({game,Hooks,recorder:manualEvents}).catch(onError);Hooks.on('updateCombat',combat=>{if(combat.started&&lastSessionId&&isActiveGM(game))void coordinator.stop(lastSessionId,'encounter-started').catch(onError)});Hooks.on('pf2e.restForTheNight',actor=>{timeEffects.observeRest({actorUUID:actor.uuid});if(lastSessionId&&isActiveGM(game))void coordinator.stop(lastSessionId,'external-rest-time-authority').catch(onError)})}
 const api=Object.freeze({version:1,open:async uuids=>{await refreshStorage();if(diagnostic.ledger.state!=='blocked')await restoreCurrent();return panel.open(uuids)},start,stop:(id,reason)=>gmAction('stop',id,reason),takeover:id=>gmAction('takeover',id),resume:(id,options)=>gmAction('resume',id,options),reconcile:id=>gmAction('reconcile',id),review:(id,options)=>gmAction('review',id,options),snapshot:id=>coordinator.snapshot(id??lastSessionId),record:event=>manualRecord.record(event),openManualCheckpoint:id=>gmAction('openManualCheckpoint',id),closeManualCheckpoint:async(binding,options)=>{if(!isActiveGM(game))throw Error('active-gm-required');const result=await coordinator.closeManualCheckpoint(binding,options);panel?.refresh();return result},reserveManualSource:(binding,intent)=>manualRecord.reserveSource(binding,intent),storage:Object.freeze({status:refreshStorage,provision:options=>storageAction('provision',options),initialize:options=>storageAction('initialize',options),select:options=>storageAction('select',options)}),diagnostic:()=>({...diagnostic,time:timeEffects.diagnostic()})});
 return {api,bind,register,hpPools,ownerOperations,refocusAdapter,refocusSubscriber:{matchesActor:actor=>!!refocusAdapter.getCurrent(actor),onRefocus:event=>refocusAdapter.capture(event)}};
}
