import {createManualRecordBridge} from './manual-record.mjs';
import {MODULE_ID} from './schema.mjs';import {createDocumentStore,isActiveGM} from './document-store.mjs';import {createLedger} from './ledger.mjs';import {createCapabilities} from './capabilities.mjs';import {createHpPools} from './hp-pool.mjs';import {createExplorationOwnerOperations} from './owner-operations.mjs';import {createNativeTreatment} from './native-treatment.mjs';import {createTreatmentProvider} from './treatment.mjs';import {createRefocusAdapter,createRefocusProvider,createFocusHealingProvider} from './refocus.mjs';import {createTimeEffects} from './time-effects.mjs';import {createClock} from './clock.mjs';import {chooseNext} from './policy.mjs';import {createCoordinator} from './coordinator.mjs';import {createManualEvents,registerWorkbenchObservation} from './manual-events.mjs';import {createRecoveryPanel} from './panel.mjs';import {getNativeActionEvents} from '../native-action-events.mjs';
export function createExplorationRuntime({game,Hooks,fromUuid,JournalEntry=globalThis.JournalEntry,nativeCasts,onError=console.error}){
 const store=createDocumentStore({game,JournalEntry,fromUuid}),ledger=createLedger({...store,isAuthority:()=>isActiveGM(game)}),hpPools=createHpPools({game,actorUpdateEvents:nativeCasts}),capabilities=createCapabilities({game,fromUuid,hpPools}),ownerOperations=createExplorationOwnerOperations({game,fromUuid,ledger});
 const refocusAdapter=createRefocusAdapter({game,fromUuid,ownerOperations}),timeEffects=createTimeEffects({capabilities}),clock=createClock({game,Hooks,ledger,timeEffects,isAuthority:()=>isActiveGM(game)});
 let coordinator,panel,lastSessionId=null,registered=false,diagnostic={status:'initializing'};
 const nativeActions=getNativeActionEvents({game}),manualEvents=createManualEvents({game,Hooks,ledger,nativeActions,hpPools,fromUuid,sessionId:()=>lastSessionId,onChange:()=>panel?.refresh()});
 const manualRecord=createManualRecordBridge({game,fromUuid,getSession:()=>ledger.getSession(lastSessionId),observe:manualEvents.observe});
 const start=async config=>{if(!isActiveGM(game))throw Error('active-gm-required');if(game.combat?.started&&!config.manual)throw Error('遭遇已经开始，请停止后再恢复。');if(!coordinator)throw Error('exploration-not-ready');if(game.system?.version!=='8.5.1'&&!config.manual)throw Error('自动治疗尚未核验当前 PF2e 版本，请使用手动记录。');const old=lastSessionId&&await ledger.getSession(lastSessionId);if(old&&['running','recording'].includes(old.status))throw Error('已有恢复会话，请先停止。');const s=await coordinator.start(config);lastSessionId=s.id;await game.user.setFlag?.(MODULE_ID,'explorationSession',s.id);return s};
 async function restoreCurrent(preferred=lastSessionId){if(!isActiveGM(game)||!coordinator)return;const s=await coordinator.restore(preferred);if(s&&s.id!==lastSessionId){lastSessionId=s.id;await game.user.setFlag?.(MODULE_ID,'explorationSession',s.id)}panel?.refresh();return s}
 const gmAction=async(action,id,options)=>{if(!isActiveGM(game))throw Error('active-gm-required');if(!coordinator)throw Error('exploration-not-ready');if(action==='resume'&&(game.combat?.started||game.system?.version!=='8.5.1'))throw Error('encounter-or-system-unavailable');const selected=id??lastSessionId,result=await coordinator[action](selected,action==='review'?{...options,userId:game.user.id}:options);if(selected!==lastSessionId){lastSessionId=selected;await game.user.setFlag?.(MODULE_ID,'explorationSession',selected)}panel?.refresh();return result};
 async function bind({checkScope,damageGuard,salubriousKiss}){
  const nativeTreatment=createNativeTreatment({game,Hooks,fromUuid,ownerOperations,checkScope,damageGuard,hpPools});
  ownerOperations.registerOperation('treat-wounds',nativeTreatment.run);ownerOperations.registerOperation('treatment-extension',async(a,ctx)=>nativeTreatment.extend(a,await ledger.getActivity(a.options.extensionOf),ctx));
  const treatment=createTreatmentProvider({capabilities,nativeTreatment,ledger,ownerOperations}),refocus=createRefocusProvider({game,ledger,capabilities,refocusEvents:refocusAdapter,salubriousKiss,ownerOperations}),focus=createFocusHealingProvider({game,Hooks,fromUuid,ownerOperations,castEvents:nativeCasts,nativeTreatment});
  ownerOperations.registerOperation('refocus',refocus.complete);ownerOperations.registerOperation('focus-healing',focus.complete);focus.register();
  const providers=[treatment,{...refocus,complete:a=>ownerOperations.runActivityWithOwner(a,'refocus')},{...focus,complete:a=>ownerOperations.runActivityWithOwner(a,'focus-healing')}];
  coordinator=createCoordinator({ledger,capabilities,providers,clock,policy:chooseNext,isAuthority:()=>isActiveGM(game),now:()=>game.time.worldTime,ownerOperations,onChange:()=>panel?.refresh()});
  panel=createRecoveryPanel({game,coordinator,capabilities,start,record:event=>api.record(event),getSessionId:()=>lastSessionId,onError});diagnostic={status:'ready',nativeVersion:'8.5.1',finiteResources:false,sharedOwnerBridge:'exploration-specific-authenticated-operation'};
  const previous=game.user.getFlag?.(MODULE_ID,'explorationSession');if(isActiveGM(game))await restoreCurrent(previous);else if(previous&&(await ledger.getSession(previous)))lastSessionId=previous;
 }
 async function register({socket}){if(registered)return;registered=true;ownerOperations.register({socket});manualRecord.register(socket);manualEvents.start();nativeActions.register();for(const event of ['userConnected','updateUser'])Hooks.on(event,()=>{if(isActiveGM(game))void restoreCurrent().catch(onError)});await registerWorkbenchObservation({game,Hooks,recorder:manualEvents}).catch(onError);Hooks.on('updateCombat',combat=>{if(combat.started&&lastSessionId&&isActiveGM(game))void coordinator.stop(lastSessionId,'encounter-started').catch(onError)});Hooks.on('pf2e.restForTheNight',actor=>{timeEffects.observeRest({actorUUID:actor.uuid});if(lastSessionId&&isActiveGM(game))void coordinator.stop(lastSessionId,'external-rest-time-authority').catch(onError)})}
 const api=Object.freeze({version:1,open:async uuids=>{await restoreCurrent();return panel.open(uuids)},start,stop:(id,reason)=>coordinator.stop(id,reason),resume:(id,options)=>gmAction('resume',id,options),reconcile:id=>gmAction('reconcile',id),review:(id,options)=>gmAction('review',id,options),snapshot:id=>coordinator.snapshot(id??lastSessionId),record:event=>manualRecord.record(event),diagnostic:()=>({...diagnostic,time:timeEffects.diagnostic()})});
 return {api,bind,register,hpPools,ownerOperations,refocusAdapter,refocusSubscriber:{matchesActor:actor=>!!refocusAdapter.getCurrent(actor),onRefocus:event=>refocusAdapter.capture(event)}};
}
