import test from 'node:test';
import assert from 'node:assert/strict';
import {GLIMPSE_SOURCES as S,resolveGlimpseSource,validateGlimpseSource,glimpseCandidates,glimpseEncounter} from '../scripts/glimpse-source.mjs';

import {fixture} from './glimpse-fixture.mjs';

test('binds the live source and actual encounter instead of the viewed encounter',async()=>{const f=fixture(),r=await resolveGlimpseSource({...f,actor:f.ally});assert.equal(r.verified,true);assert.equal(glimpseCandidates(r,f.game)[0].token,f.championToken);assert.equal(glimpseEncounter(f.championToken,f.game).epoch,'combat:1');assert.equal((await validateGlimpseSource({...f,snapshot:r.snapshot})).verified,true);});
test('native spell save damage uses its actual recipient and source author',async()=>{const f=fixture();f.item.type='spell';f.message.flags.pf2e.origin.type='spell';f.message.flags.pf2e.context.sourceType='save';delete f.message.flags.pf2e.context.target;delete f.message.flags.pf2e.strike;f.message.flags['pf2e-toolbelt']={targetHelper:{targets:[f.allyToken.uuid],saveVariants:{}}};assert.equal((await resolveGlimpseSource({...f,actor:f.ally})).verified,true);});
for(const[reason,mutate]of[
 ['no private roll context',f=>f.source=null],['unknown card',f=>f.source.messageId='missing'],['wrong target',f=>f.message.flags.pf2e.context.target.token='wrong'],['wrong source owner',f=>f.message.author={id:'other'}],['unproven origin',f=>f.message.flags.pf2e.origin.actor='wrong'],['no native attack',f=>delete f.message.flags.pf2e.strike],['merged attacks',f=>f.message.flags['pf2e-toolbelt']={betterChat:{mergeDamage:true}}],['numeric input',f=>f.params.damage=10],['healing',f=>f.roll.total=-10],['final application',f=>f.params.final=true],['skipped IWR',f=>f.params.skipIWR=true],['unrecorded target',f=>delete f.message.flags.pf2e.context.target],['persistent tick',f=>f.roll.options.evaluatePersistent=true],['spoofed token',f=>f.params.token={...f.allyToken}],['wrong native item',f=>f.params.item={...f.item,uuid:'wrong'}],
])test(`rejects ${reason}`,async()=>{const f=fixture();mutate(f);assert.equal((await resolveGlimpseSource({...f,actor:f.ally})).verified,false);});
test('source mutations invalidate snapshots but Toolbelt application receipts do not',async()=>{const f=fixture();f.message.flags['pf2e-toolbelt']={targetHelper:{targets:[f.allyToken.uuid]}};const r=await resolveGlimpseSource({...f,actor:f.ally});f.message.flags['pf2e-toolbelt'].targetHelper.applied={ally:{0:true}};assert.equal((await validateGlimpseSource({...f,snapshot:r.snapshot})).verified,true);f.roll.total=11;assert.equal((await validateGlimpseSource({...f,snapshot:r.snapshot})).verified,false);});
for(const[reason,mutate]of[
 ['suppressed aura',f=>f.championToken.auras.clear()],['enemy outside aura',f=>f.championToken.auras.get('champions-aura').containsToken=t=>t!==f.enemyToken],['ally outside aura',f=>f.championToken.auras.get('champions-aura').containsToken=t=>t!==f.allyToken],['cannot act',f=>f.champion.canAct=false],['missing canAct',f=>delete f.champion.canAct],['not enemy',f=>f.champion.isEnemyOf=()=>false],['not ally',f=>f.champion.isAllyOf=()=>false],['wrong source ability',f=>f.ability.sourceId='wrong'],['unsupported future feat',f=>f.champion.items.set('weight',{sourceId:S.weight})],['existing resistance workflow',f=>f.ally.items.set('resistance',{sourceId:S.resistance})],
])test(`candidate rejects ${reason}`,async()=>{const f=fixture(),r=await resolveGlimpseSource({...f,actor:f.ally});mutate(f);assert.deepEqual(glimpseCandidates(r,f.game),[]);});
test('ambiguous encounter is rejected and round changes alter the bound epoch',()=>{const f=fixture();f.game.combats.set('second',{...f.combat,id:'second'});assert.throws(()=>glimpseEncounter(f.championToken,f.game),/遭遇/);f.game.combats.delete('second');f.combat.turn=1;assert.equal(glimpseEncounter(f.championToken,f.game).epoch,'combat:2');});
