import test from 'node:test';
import assert from 'node:assert/strict';
import {glimpseExpiryFor,createGlimpseExpiry} from '../scripts/glimpse-expiry.mjs';
import {fixture} from './glimpse-fixture.mjs';
import {MODULE_ID as M} from '../scripts/rules.mjs';
function patch(doc,data){for(const [path,value] of Object.entries(data)){const ks=path.split('.');let at=doc;for(const k of ks.slice(0,-1))at=at[k]??={};at[ks.at(-1)]=structuredClone(value)}}
function setup(){const f=fixture(),warnings=[],deleted=[];f.game.time={worldTime:100};f.game.pf2e={ConditionManager:{conditions:new Map([['enfeebled',{uuid:'Condition.enfeebled'}]])}};f.combat.turns.forEach(c=>c.parent=f.combat);const expiry=glimpseExpiryFor(f.enemyToken,f.game),nonce='receipt';const effect={id:'effect',uuid:f.enemy.uuid+'.Item.effect',type:'effect',actor:f.enemy,flags:{},system:{slug:'tpa-glimpse-receipt',context:{origin:{actor:f.enemy.uuid,token:f.enemyToken.uuid}},duration:{unit:'rounds',value:1,expiry:'turn-end'},rules:[{key:'GrantItem',uuid:'Condition.enfeebled',inMemoryOnly:true,alterations:[{mode:'override',property:'badge-value',value:2}]}]},async update(data){patch(this,data)}};f.enemy.items.set(effect.id,effect);f.enemy.deleteEmbeddedDocuments=async(_kind,ids)=>{for(const id of ids){deleted.push(id);f.enemy.items.delete(id)}};const lifecycle=createGlimpseExpiry({game:f.game,onError:e=>warnings.push(e.message)});return {...f,lifecycle,effect,expiry,nonce,warnings,deleted}}
test('next end is this round before enemy turn, otherwise next round, regardless of viewed combat or initiative ties',()=>{const f=setup();assert.equal(f.expiry.endRound,3);f.combat.turn=2;assert.equal(glimpseExpiryFor(f.enemyToken,f.game).endRound,3);f.combat.turns.push(f.combat.turns.shift());f.combat.turn=0;f.combat.turns.forEach(c=>c.initiative=20);assert.equal(glimpseExpiryFor(f.enemyToken,f.game).endRound,2)});
test('arming preserves native GrantItem and exact token origin, then waits for actual end receipt',async()=>{const f=setup();await f.lifecycle.arm(f);assert.equal(f.effect.system.duration.unit,'unlimited');assert.equal(f.effect.system.rules[0].key,'GrantItem');f.combat.round=3;f.combat.turns[0].flags.pf2e={roundOfLastTurnEnd:2};await f.lifecycle.reconcile();assert.deepEqual(f.deleted,[]);f.combat.turns[0].flags.pf2e.roundOfLastTurnEnd=3;await f.lifecycle.reconcile();assert.deepEqual(f.deleted,['effect'])});
test('late creation after exact target end removes immediately and duplicate hooks do not delete twice',async()=>{const f=setup();f.combat.round=3;f.combat.turns[0].flags.pf2e={roundOfLastTurnEnd:3};await f.lifecycle.arm(f);await Promise.all([f.lifecycle.reconcile(),f.lifecycle.reconcile()]);assert.deepEqual(f.deleted,['effect'])});
test('a newly constructed manager recovers persistent expiry without private process memory',async()=>{const f=setup();await f.lifecycle.arm(f);f.combat.round=3;f.combat.turns[0].flags.pf2e={roundOfLastTurnEnd:3};await createGlimpseExpiry({game:f.game}).reconcile();assert.deepEqual(f.deleted,['effect'])});
for(const [name,change]of [['combat deleted',f=>f.game.combats.delete(f.combat.id)],['combat ended',f=>f.combat.started=false],['combatant deleted',f=>f.combat.turns.shift()],['token deleted',f=>f.scene.tokens.delete(f.enemyToken.id)],['round rollback',f=>f.combat.round=1],['turn rollback',f=>{f.combat.turn=2;f.expiry=glimpseExpiryFor(f.enemyToken,f.game)}]])test(`${name} restores finite native duration and reports once`,async()=>{const f=setup();if(name==='turn rollback'){change(f);await f.lifecycle.arm(f);f.combat.turn=0}else{await f.lifecycle.arm(f);change(f)}await f.lifecycle.reconcile();await f.lifecycle.reconcile();assert.equal(f.effect.system.duration.unit,'rounds');assert.equal(f.effect.system.duration.value,1);assert.equal(f.effect.system.start.value,100);assert.equal(f.effect.flags[M].glimpseExpiry.status,'fallback');assert.equal(f.warnings.length,1);assert.deepEqual(f.deleted,[])});
test('a later authentic end after a skipped target turn cannot leak an unlimited condition',async()=>{const f=setup();await f.lifecycle.arm(f);f.combat.round=4;f.combat.turns[1].flags.pf2e={roundOfLastTurnEnd:4};await f.lifecycle.reconcile();assert.equal(f.effect.system.duration.unit,'rounds');assert.equal(f.warnings.length,1)});
test('foreign conditions, mutated scope, and non-GM calls are not deleted',async()=>{const f=setup();await f.lifecycle.arm(f);f.combat.round=3;f.combat.turns[0].flags.pf2e={roundOfLastTurnEnd:3};f.effect.system.context.origin.token='other';await f.lifecycle.reconcile();assert.deepEqual(f.deleted,[]);f.effect.system.context.origin.token=f.enemyToken.uuid;f.game.user={id:'player'};await f.lifecycle.reconcile();assert.deepEqual(f.deleted,[])});
test('an already ended enemy moved behind the current actor cannot reuse its old receipt as the next end',()=>{const f=setup(),enemy=f.combat.turns.shift();f.combat.turns.push(enemy);enemy.flags.pf2e={roundOfLastTurnEnd:2};assert.throws(()=>glimpseExpiryFor(f.enemyToken,f.game),/已结束|无法证明/)});
for(const change of ['order','initiative'])test(`manual ${change} change after payment restores finite duration instead of trusting a stale next end`,async()=>{const f=setup();await f.lifecycle.arm(f);if(change==='order')f.combat.turns.push(f.combat.turns.shift());else f.combat.turns[0].initiative=99;await f.lifecycle.reconcile();assert.equal(f.effect.system.duration.unit,'rounds');assert.equal(f.warnings.length,1);assert.deepEqual(f.deleted,[])});
test('recovery includes scene-only synthetic enemy actors',async()=>{const f=setup();await f.lifecycle.arm(f);f.game.actors.delete(f.enemy.id);f.combat.round=3;f.combat.turns[0].flags.pf2e={roundOfLastTurnEnd:3};await createGlimpseExpiry({game:f.game}).reconcile();assert.deepEqual(f.deleted,['effect'])});
