import test from 'node:test';
import assert from 'node:assert/strict';
import {createGlimpseCompat,GLIMPSE_TRIGGER_ID,GLIMPSE_EVENT,glimpseGraph} from '../scripts/glimpse-compat.mjs';
import {GLIMPSE_SOURCES} from '../scripts/glimpse-source.mjs';
function setup(){
 const hooks=new Map(),Hooks={once:(k,f)=>hooks.set(k,f)},actor={uuid:'Actor.enemy',items:new Map(),async deleteEmbeddedDocuments(_t,ids){ids.forEach(id=>this.items.delete(id))}},token={uuid:'Scene.s.Token.enemy',actor};
 const user={id:'gm'},game={world:{id:'ujx5r8oipw7ercdr'},user,users:{activeGM:user},system:{id:'pf2e',version:'8.5.1'},modules:new Map([['trigger-engine',{active:true,version:'1.35.0'}],['pf2e-trigger-trove',{active:true,version:'2.3.5'}]]),pf2e:{ConditionManager:{conditions:new Map([['enfeebled',{uuid:'Condition.enfeebled'}]])}}};
 let backups=[],setting={enabled:['existing'],disabled:['untouched'],sources:[{id:'user'}]},nodeClass,creates=0;
 game.settings={get:(_m,key)=>key==='configurationBackups'?backups:setting,set:async(_m,key,next)=>{if(key==='configurationBackups')backups=next;else setting=next}};
 class TriggerNode{setOutputValue(k,v){this[k]=v}async executeNext(){creates++;for(let i=0;i<2;i++){const effect={id:`e${i}`,type:'effect',system:{slug:this.slug,context:{origin:{actor:actor.uuid,token:token.uuid}},duration:{value:1,unit:'rounds',expiry:'turn-end'},rules:[{key:'GrantItem',uuid:'Condition.enfeebled',inMemoryOnly:true,alterations:[{mode:'override',property:'badge-value',value:2}]}]}};actor.items.set(effect.id,effect)}return true}}
 const compat=createGlimpseCompat({game,fromUuid:async uuid=>uuid===GLIMPSE_SOURCES.resistance?{toObject:()=>({type:'effect',system:{rules:[{key:'Resistance',type:'all-damage',value:'@item.origin.level+2'}]}})}:null,api:()=>({TriggerNode}),verifyEngine:async()=>true,query:async data=>new nodeClass()._execute(data.args)});
 compat.register({Hooks});hooks.get('triggerEngine.registerNodes')((_m,_a,list)=>{nodeClass=list[0]});let graph;hooks.get('triggerEngine.registerTriggers')((_m,_a,list)=>graph=list[0]);hooks.get('triggerEngine.ready')();
 return {compat,game,actor,token,setting:()=>setting,backups:()=>backups,creates:()=>creates,graph:()=>graph,node:()=>new nodeClass()};
}
test('registers and proves only its own graph; private probe does not create a condition',async()=>{const f=setup();await f.compat.initialize();assert.equal(f.compat.ready(),true);assert.deepEqual(f.setting().enabled,['existing',GLIMPSE_TRIGGER_ID]);assert.deepEqual(f.setting().disabled,['untouched']);assert.deepEqual(f.setting().sources,[{id:'user'}]);assert.equal(f.creates(),0);assert.deepEqual(f.graph(),glimpseGraph());assert.equal(f.graph().nodes[0].type,GLIMPSE_EVENT);await f.node()._execute({key:'forged'});assert.equal(f.creates(),0)});
test('authenticated zero-damage followup executes the existing condition node once and removes exact internal retries',async()=>{const f=setup();await f.compat.initialize();const result=await f.compat.apply({nonce:'nonce',enemy:f.token,authorize:async()=>true});assert.equal(result.effectId,'e0');assert.equal(f.creates(),1);assert.equal(f.actor.items.size,1);await assert.rejects(f.compat.apply({nonce:'nonce',enemy:f.token,authorize:async()=>true}),/已存在/);assert.equal(f.creates(),1)});
test('failed scope authorization cannot enter condition creation',async()=>{const f=setup();await f.compat.initialize();await assert.rejects(f.compat.apply({nonce:'n',enemy:f.token,authorize:async()=>false}),/后续/);assert.equal(f.creates(),0)});
test('unknown versions and world override of module graph fail closed',async()=>{const f=setup();f.game.modules.get('trigger-engine').version='future';await assert.rejects(f.compat.initialize(),/版本/);const g=setup();g.setting().sources.push({id:GLIMPSE_TRIGGER_ID});await assert.rejects(g.compat.initialize(),/覆盖/)});
test('exact installed semver, valid native IDs, and setting delta backup are required',async()=>{const f=setup();assert.ok(/^[A-Za-z0-9]{16}$/.test(GLIMPSE_TRIGGER_ID));for(const node of glimpseGraph().nodes)assert.ok(/^[A-Za-z0-9]{16}$/.test(node.id));await f.compat.initialize();assert.equal(f.backups().length,1);assert.deepEqual(f.backups()[0].changes[0].before,['existing']);await f.compat.initialize();assert.equal(f.backups().length,1);const g=setup();g.game.modules.get('trigger-engine').version='1.35';await assert.rejects(g.compat.initialize(),/版本/)});
test('other worlds do not enable a graph or create a backup',async()=>{const f=setup();f.game.world.id='other';assert.equal(await f.compat.initialize(),false);assert.deepEqual(f.setting().enabled,['existing']);assert.deepEqual(f.backups(),[])});
test('ready binds the actual Game when Foundry replaces its module-loading bootstrap object',async()=>{const f=setup(),actual={...f.game};delete f.game.world;delete f.game.user;delete f.game.users;assert.equal(await f.compat.initialize({game:actual}),true);assert.equal(f.compat.ready(),true);assert.deepEqual(f.setting().enabled,['existing',GLIMPSE_TRIGGER_ID]);assert.equal(f.backups().length,1)});
