import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {nativeRollEvent,manualDamagePrivacy} from '../scripts/manual-native-roll.mjs';
import {withDamageMessageTarget} from '../scripts/damage-message-targets.mjs';
const ID='pf2e-third-party-automation',enemy='Scene.s.Token.enemy';
function extracted(file,startMarker,endMarker,environment){const source=fs.readFileSync(new URL('../scripts/'+file,import.meta.url),'utf8'),start=source.indexOf(startMarker),end=source.indexOf(endMarker,start);assert(start>=0&&end>start);return vm.runInNewContext('('+source.slice(start,end).trim()+')',environment)}
function damageRolls(){const cards=[];let rolls=0;class DamageRoll{constructor(formula){this.formula=formula}async evaluate(){rolls++;this.total=8;return this}async toMessage(data,options){cards.push({data,options});return data}}return {DamageRoll,cards,get rolls(){return rolls}}}
for(const setting of [false,true])test(`campaign Strike and damage each preserve native acceptance with preference ${setting}`,async()=>{
 const events=[],game={user:{settings:{showCheckDialogs:setting,showDamageDialogs:setting}}},target={uuid:enemy,actor:{uuid:'Actor.enemy',hasCondition:()=>false},object:{}},weapon={uuid:'Actor.pc.Item.weapon',isMelee:true};
 const strike={ready:true,item:weapon,variants:[{async roll(options){events.push(options.event);await options.callback({options:{degreeOfSuccess:2}},'success',{id:'check',flags:{pf2e:{context:{}}}});return {total:20}}}],damage:async options=>{events.push(options.event);return {total:8}}};
 const run=extracted('campaign-feats.mjs','async function compositeStrike(','async function linkDamageCard(',{game,MODULE_ID:ID,oneTarget:async()=>target,values:c=>[...c],pick:async()=> '0:0',requireMeleeTarget(){},nextOwnTurnTiming:()=>null,nativeRollEvent,saveFlag:async()=>{},opts:()=>[]});await run({actor:{uuid:'Actor.pc',system:{actions:[strike]}},item:{},message:{id:'use'},user:{},action:'campaign:slam'});assert.equal(events.length,2);for(const event of events)assert.equal(event.shiftKey,!setting);
});
test('campaign Battle Medicine cancellation preserves its real native skill check window',async()=>{
 const target={actor:{items:[]}},stat={rank:1,check:{async roll(options){assert.equal(options.skipDialog,false);assert.equal(options.event,null);return null}}};
 const run=extracted('campaign-feats.mjs','async function battleMedicine(','async function processCheck(',{MODULE_ID:ID,oneTarget:async()=>target,distance:()=>5,values:x=>[...x],hasSource:()=>false,own:()=>({}),BM_IMMUNITY:'immunity',pick:async()=> '1'});await assert.rejects(run({actor:{uuid:'Actor.pc',items:[],skills:{medicine:stat}},item:{},message:{id:'use'},user:{}}),/取消/);
});
test('bear support waits for native damage confirmation and a close keeps its attack claimed without publishing',async()=>{
 const f=damageRolls(),master={uuid:'Actor.master',flags:{'pf2e-ranged-combat':{animalCompanionId:'bear'}},testUserPermission:()=>true},companion={uuid:'Actor.bear',items:[{uuid:'Actor.bear.Item.support',sourceId:'support',system:{traits:{}}}]},target={uuid:enemy,actor:{uuid:'Actor.enemy'}},bear={uuid:'Scene.s.Token.bear',actor:companion},effect={flags:{[ID]:{masterUuid:master.uuid,processed:[],startedAt:0,companionTokenUuid:bear.uuid}},async update(update){this.flags[ID].processed=update['flags.'+ID+'.processed']}};let close;const pending=new Promise(resolve=>close=resolve);
 const run=extracted('companion-automation.mjs','async function handleAttack(','async function expire(',{MODULE_ID:ID,RANGED:'pf2e-ranged-combat',SOURCE:{support:'support'},game:{actors:new Map([['master',master],['bear',companion]]),users:new Map([['owner',{id:'owner'}]])},authority:()=>true,ownFlags:i=>i.flags?.[ID]??{},linkedMaster:()=>master,serial:(_key,callback)=>callback(),supports:()=>[effect],isExpired:()=>false,fromUuid:async uuid=>uuid===enemy?target:bear,inReach:()=>true,values:c=>[...c],sourceOf:i=>i.sourceId,CONFIG:{Dice:{rolls:[f.DamageRoll]}},ChatMessage:{getSpeaker:()=>({actor:'bear'})},manualDamageRoll:async()=>{await pending;return null},manualDamagePrivacy,withDamageMessageTarget});
 const attack={id:'attack',isCheckRoll:true,timestamp:1,speaker:{actor:'master'},author:{id:'owner'},flags:{pf2e:{origin:{type:'weapon',actor:master.uuid},context:{type:'attack-roll',outcome:'success',target:{actor:target.actor.uuid,token:target.uuid},options:[]}}}},result=run(attack);await new Promise(resolve=>setImmediate(resolve));try{assert.equal(f.rolls,0);assert.equal(f.cards.length,0)}finally{close();await result}assert.deepEqual(Array.from(effect.flags[ID].processed),['attack']);await run(attack);assert.equal(f.cards.length,0);
});

for(const change of ['gm','effect','attack','target-actor'])test(`bear support cannot publish its manual roll after the original ${change} changes`,async()=>{
 const f=damageRolls(),gm={id:'gm',active:true},master={uuid:'Actor.master',flags:{'pf2e-ranged-combat':{animalCompanionId:'bear'}},testUserPermission:()=>true},support={uuid:'Actor.bear.Item.support',sourceId:'support',system:{traits:{}}},companion={uuid:'Actor.bear',items:[support]},target={uuid:enemy,actor:{uuid:'Actor.enemy'}},bear={uuid:'Scene.s.Token.bear',actor:companion},effect={flags:{[ID]:{masterUuid:master.uuid,processed:[],startedAt:0,companionTokenUuid:bear.uuid}},async update(update){this.flags[ID].processed=update['flags.'+ID+'.processed']}},effects=[effect],game={user:gm,actors:new Map([['master',master],['bear',companion]]),users:new Map([['owner',{id:'owner'}]]),messages:new Map()};let accept;const wait=new Promise(resolve=>accept=resolve);
 const run=extracted('companion-automation.mjs','async function handleAttack(','async function expire(',{MODULE_ID:ID,RANGED:'pf2e-ranged-combat',SOURCE:{support:'support'},game,authority:()=>true,ownFlags:i=>i.flags?.[ID]??{},linkedMaster:()=>master,serial:(_key,callback)=>callback(),supports:()=>effects,isExpired:()=>false,fromUuid:async uuid=>uuid===enemy?target:bear,inReach:()=>true,values:c=>[...c],sourceOf:i=>i.sourceId,CONFIG:{Dice:{rolls:[f.DamageRoll]}},ChatMessage:{getSpeaker:()=>({actor:'bear'})},manualDamageRoll:async({roll})=>{await wait;return roll.evaluate()},manualDamagePrivacy,withDamageMessageTarget});
 const attack={id:'attack',isCheckRoll:true,timestamp:1,speaker:{actor:'master'},author:{id:'owner'},flags:{pf2e:{origin:{type:'weapon',actor:master.uuid},context:{type:'attack-roll',outcome:'success',target:{actor:target.actor.uuid,token:target.uuid},options:[]}}}};game.messages.set(attack.id,attack);const pending=run(attack);await new Promise(resolve=>setImmediate(resolve));if(change==='gm')game.user={id:'new'};else if(change==='effect')effects.length=0;else if(change==='attack')game.messages.delete(attack.id);else target.actor={uuid:'Actor.rebound'};accept();await assert.rejects(pending,/来源|主GM/);assert.equal(f.cards.length,0);assert.deepEqual(Array.from(effect.flags[ID].processed),['attack']);
});
