import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
import {manualDamageRoll,nativeRollEvent} from '../scripts/manual-native-roll.mjs';
const enabled=!!(process.env.FVTT_NATIVE_APP&&process.env.PF2E_NATIVE_BUNDLE);
const foundryClient=enabled?await readFile(path.join(process.env.FVTT_NATIVE_APP,'public/scripts/foundry.mjs'),'utf8'):'';
async function fixture(){
 const hooks=new Map(),apps=[];let sequence=0,evaluations=0,publications=0;
 const Hooks={on(event,fn){const id=++sequence;hooks.set(id,{event,fn});return id},off(_event,id){hooks.delete(id)},call(event,...args){let allowed=true;for(const {event:name,fn}of hooks.values())if(name===event&&fn(...args)===false)allowed=false;return allowed}};
 const groupBy=(items,key)=>{const grouped=new Map();for(const item of items){const k=key(item);if(!grouped.has(k))grouped.set(k,[]);grouped.get(k).push(item)}return grouped};
 const context=vm.createContext({console,structuredClone,deepClone:structuredClone,_loc:s=>s,ErrorPF2e:Error,tupleHasValue:(a,v)=>a.includes(v),N:v=>!!v&&typeof v==='object'&&!Array.isArray(v),v:x=>!!x&&typeof x==='object',o:x=>x!==null&&x!==undefined,M:a=>[...new Set(a)],k:(obj,keys)=>Object.fromEntries(Object.entries(obj).filter(([key])=>!keys.includes(key))),z:(obj,keys)=>Object.fromEntries(keys.map(key=>[key,obj[key]])),u:(arr,key)=>[...arr].sort((a,b)=>key(a)-key(b)),f:(arr,key)=>arr.reduce((n,item)=>n+key(item),0),groupBy,ve:(arr,key)=>Object.fromEntries(groupBy(arr,key)),Ht:{CRITICAL_FAILURE:0,FAILURE:1,SUCCESS:2,CRITICAL_SUCCESS:3},Ut:['criticalFailure','failure','success','criticalSuccess'],en:{DOUBLE_ON_CRIT:null,CRITICAL_ONLY:true,DONT_DOUBLE_ON_CRIT:false},Kt:['precision','splash','persistent'],Yt:[4,6,8,10,12]});
 vm.runInContext(`globalThis.foundry={dice:{terms:{}},utils:{deepClone},applications:{},appv1:{api:{Application:class {render(){apps.push(this);return this}close(){}}}}};globalThis.CONFIG={debug:{},Dice:{rolls:[],terms:{},termTypes:{},fulfillment:{methods:{},defaultMethod:'random'},randomUniform:()=>0.5},ChatMessage:{modes:{public:'public',blind:'blind'}},PF2E:{damageTypes:{electricity:'Electricity',slashing:'Slashing',bludgeoning:'Bludgeoning',force:'Force',fire:'Fire',cold:'Cold',vitality:'Vitality',untyped:'Untyped'},actionTraits:{},damageRollFlavors:{},materialDamageEffects:{}}};Number.isNumeric=n=>typeof n==='number'&&Number.isFinite(n);Math.clamp=(n,a,b)=>Math.min(Math.max(n,a),b);`,context);
 context.apps=apps;context.game={user:{id:'owner',settings:{showDamageDialogs:false}},messages:new Map(),settings:{get:()=> 'public'},pf2e:{settings:{metagame:{breakdowns:true}}},users:new Map()};
 for(const [file,name]of [['roll.mjs','Roll'],['terms/term.mjs','RollTerm'],['terms/numeric.mjs','NumericTerm'],['terms/operator.mjs','OperatorTerm'],['terms/dice.mjs','DiceTerm'],['terms/die.mjs','Die'],['terms/function.mjs','FunctionTerm'],['terms/pool.mjs','PoolTerm']]){
  const source=(await readFile(path.join(process.env.FVTT_NATIVE_APP,'client/dice',file),'utf8')).replace(/^import .*?;\r?\n/gm,'').replace('export default class '+name,'globalThis.'+name+'=class '+name);vm.runInContext(source,context,{filename:file});if(name!=='Roll')vm.runInContext(`foundry.dice.terms.${name}=${name};CONFIG.Dice.termTypes.${name}=${name};`,context);
 }
 const parser=(await readFile(path.join(process.env.FVTT_NATIVE_APP,'client/dice/parser.mjs'),'utf8')).replace(/^import .*?;\r?\n/gm,'').replace('export default class RollParser','globalThis.RollParser=class RollParser');vm.runInContext(parser,context);vm.runInContext('CONFIG.Dice.parser=RollParser;',context);
 context.foundry.utils.isSubclass=(child,parent)=>child===parent||child.prototype instanceof parent;
 const grammarStart=foundryClient.indexOf('var Parser = // @generated by Peggy'),grammarEnd=foundryClient.indexOf('\n;',foundryClient.indexOf('    parse: peg$parse,',grammarStart));assert.ok(grammarStart>0&&grammarEnd>grammarStart);vm.runInContext(foundryClient.slice(grammarStart,grammarEnd+2)+';foundry.dice.RollGrammar=Parser;',context);context.getType=value=>value?.constructor?.name??typeof value;
 const source=await readFile(process.env.PF2E_NATIVE_BUNDLE,'utf8'),slice=(start,end)=>{const a=source.indexOf(start),b=source.indexOf(end,a);assert.ok(a>=0&&b>a);return source.slice(a,b)};
 vm.runInContext('var '+slice('Zt = {','}, Qt = {')+'};'+slice('var an = {','function applyBaseDamageAlterations'),context);
 vm.runInContext(slice('function createDamageFormula','var tn = foundry.dice.terms'),context);
 vm.runInContext(slice('var tn = foundry.dice.terms','function nextDamageDieSize'),context);
 vm.runInContext(slice('function applyDamageDiceOverrides','function processBaseDamage'),context);
 vm.runInContext(slice('var sn = foundry.dice.terms','var un = class PersistentDamageEditor'),context);await vm.runInContext('Promise.resolve()',context);
 vm.runInContext(`CONFIG.Dice.rolls=[Roll,cn,ln];CONFIG.Dice.terms.d=Die;for(const C of [nn,rn,IntermediateDie,InstancePool])CONFIG.Dice.termTypes[C.name]=C;`,context);
 vm.runInContext('var DamageModifierDialog='+slice('DamageModifierDialog = class','}, K = class').slice('DamageModifierDialog = '.length)+'};',context);
 context.K={createActionOptions:()=>{throw Error('no item actions may be consulted')}};
 vm.runInContext(slice('function isRelevantEvent','function eventToMessageMode'),context);
 vm.runInContext(slice('async function augmentInlineDamageRoll','function resolveRollData'),context);
 context.ui={windows:{}};context.ChatMessagePF2e={getSpeaker:()=>({})};context.Z=class {};context.ActorSheetPF2e=class {};context.ItemSheetPF2e=class {};context.fromUuidSync=()=>{throw Error('actor lookup forbidden')};context.objectHasKey=(o,k)=>Object.hasOwn(o,k);context.splitListString=s=>(s??'').split(',').filter(Boolean);context.htmlClosest=(target,selector)=>selector==='a'?target:null;
 context.DamagePF2e={async roll(template,ctx){evaluations++;const roll=await template.damage.roll.evaluate({allowInteractive:false});const message={author:'owner',flags:{pf2e:{context:{...ctx,options:[...ctx.options]}}},rolls:[roll]};if(Hooks.call('preCreateChatMessage',message))publications++;return roll}};
 const TextEditor=vm.runInContext('(class NativeTextEditor { '+slice('static async _onClickInlineRoll(e)','static processUserVisibility').trim()+' })',context);
 const document={createElement(){return {dataset:{},parentElement:null}}};return {game:context.game,Hooks,apps,document,TextEditor,DamageRoll:context.cn,eventToRollParams:context.eventToRollParams,get counts(){return {evaluations,publications}},hooks};
}
for(const formula of ['{6d6[electricity]}','{(2d8 + 30)[healing]}','{(4d4 + 4)[force]}','{1d8[slashing]}'])test(`actual native inline window preserves ${formula} without an actor or item`,{skip:!enabled},async()=>{
 const f=await fixture(),original=globalThis.document;globalThis.document=f.document;
 try{const originalRoll=new f.DamageRoll(formula),pending=manualDamageRoll({game:f.game,roll:originalRoll,Hooks:f.Hooks,TextEditor:f.TextEditor});await new Promise(resolve=>setImmediate(resolve));assert.equal(f.apps.length,1);assert.deepEqual(f.counts,{evaluations:0,publications:0});const app=f.apps[0];assert.equal(app.context.self,null);assert.equal(app.formulaData.modifiers.length,0);assert.equal(app.formulaData.dice.length,0);app.isRolled=true;await app.close();const rolled=await pending;assert.equal(rolled._evaluated,true);assert.equal(originalRoll._evaluated,false);const input=originalRoll.instances.map(i=>({type:i.type,kinds:[...i.kinds],dice:i.dice.map(d=>[d.number,d.faces])})),output=rolled.instances.map(i=>({type:i.type,kinds:[...i.kinds],dice:i.dice.map(d=>[d.number,d.faces])}));assert.deepEqual(output,input);assert.equal(rolled.total,formula.includes('30')?38:formula.includes('4d4')?12:formula.includes('6d6')?18:4);assert.equal(f.counts.publications,0);assert.equal(f.hooks.size,0)}finally{globalThis.document=original}
});
test('actual native damage close returns null with no dice or intermediate message',{skip:!enabled},async()=>{
 const f=await fixture(),original=globalThis.document;globalThis.document=f.document;
 try{const roll=new f.DamageRoll('{2d8[healing]}'),pending=manualDamageRoll({game:f.game,roll,Hooks:f.Hooks,TextEditor:f.TextEditor});await new Promise(resolve=>setImmediate(resolve));assert.equal(f.apps.length,1);await f.apps[0].close();assert.equal(await pending,null);assert.equal(roll._evaluated,false);assert.deepEqual(f.counts,{evaluations:0,publications:0});assert.equal(f.hooks.size,0)}finally{globalThis.document=original}
});
for(const setting of [true,false,undefined,null])test(`manual event uses actual native preference parser with preference ${setting}`,{skip:!enabled},async()=>{const f=await fixture();f.game.user.settings.showDamageDialogs=setting;f.game.user.settings.showCheckDialogs=setting;for(const type of ['check','damage'])assert.equal(f.eventToRollParams(nativeRollEvent(f.game,type),{type}).skipDialog,false)});
