import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {createMedicActions} from '../scripts/medic-actions.mjs';
const M='pf2e-third-party-automation';
function doc(data){return Object.assign(data,{async update(changes){for(const [path,value]of Object.entries(changes)){const keys=path.split('.');let at=this;for(const key of keys.slice(0,-1))at=at[key]??={};at[keys.at(-1)]=structuredClone(value);}return this;}});}
function fixture({degree=2,branch='treat-condition',rollMutation=()=>{},facts={dc:21,restricted:false,continuous:false}}={}){
 const gm={id:'gm',isGM:true,active:true},owner={id:'owner',active:true},users=new Map([[gm.id,gm],[owner.id,owner]]);users.activeGM=gm;
 const feat=(id,source)=>doc({id,uuid:`Actor.healer.Item.${id}`,type:'feat',_stats:{compendiumSource:`Compendium.pf2e.feats-srd.Item.${source}`},system:{traits:{value:[]}}});
 const treat=feat('treat','rfnEcjxIFqwlJwJT'),visit=feat('visit','1fBHZpM3Z3MQtzvi'),bm=feat('bm','wYerMk6F1RZb0Fwt');
 const actor=doc({id:'healer',uuid:'Actor.healer',type:'character',items:new Map(),flags:{},handsFree:1,system:{attributes:{},movement:{speeds:{land:{value:25}}}},testUserPermission:u=>u===owner||u===gm});
 for(const item of [treat,visit,bm,{id:'kit',type:'equipment',_stats:{compendiumSource:'Compendium.pf2e.equipment-srd.Item.s1vB3HdXjMigYAnY'},system:{quantity:1,equipped:{carryType:'worn'}}}]){item.actor=actor;actor.items.set(item.id,item);}
 const patient=doc({id:'patient',uuid:'Actor.patient',type:'character',items:new Map(),flags:{}});
 const condition=doc({id:'condition',uuid:'Actor.patient.Item.condition',actor:patient,type:'condition',slug:'clumsy',system:{value:{value:2}},async delete(){patient.items.delete(this.id);}});patient.items.set(condition.id,condition);
 const healer={id:'h',uuid:'Scene.scene.Token.h',documentName:'Token',actor,parent:{id:'scene'},x:0,y:0};
 const target={id:'t',uuid:'Scene.scene.Token.t',documentName:'Token',actor:patient,parent:healer.parent,x:100,y:0};
 actor.getActiveTokens=()=>[{document:healer}];
 const game={user:gm,users,messages:new Map(),combat:{id:'fight',started:true,round:1,turn:0,combatant:{actor}},modules:new Map()};
 const records={rolls:0,delegated:[],commits:[]};
 const entities=new Map([actor,patient,healer,target,treat,visit,condition].map(x=>[x.uuid,x]));
 const deps={game,fromUuid:async uuid=>entities.get(uuid),choose:async({choices})=>choices.find(c=>c.value===branch)?.value??choices[0]?.value,requestFacts:async()=>facts,distance:()=>5,commitActivity:async x=>records.commits.push(x.cost),delegateTreatment:async x=>{records.delegated.push([x.branch,x.actor.uuid,x.target.uuid,x.user.id]);return {status:'delegated'};},rollCheck:async({nonce,dc})=>{
  records.rolls++;await rollMutation({condition,game,actor,target});
  const roll={total:25,options:{degreeOfSuccess:degree}};
  const check=doc({id:`check${records.rolls}`,uuid:`ChatMessage.check${records.rolls}`,speaker:{actor:actor.id},author:gm,rolls:[roll],flags:{pf2e:{context:{type:'skill-check',options:[`${M}:medic:${nonce}`],dc:{value:dc},outcome:['criticalFailure','failure','success','criticalSuccess'][degree],target:{actor:patient.uuid,token:target.uuid}}}}});game.messages.set(check.id,check);return {roll,message:check};
 }};
 const api=createMedicActions(deps);
 function message(item=treat,id='use',nonce=id){const m=doc({id,uuid:`ChatMessage.${id}`,author:owner,speaker:{actor:actor.id,scene:'scene',token:'h'},flags:{pf2e:{origin:{uuid:item.uuid,type:'feat'}},[M]:{usageInput:{actualUse:true,targetUuids:[target.uuid]},medicInput:{nonce}}}});game.messages.set(id,m);return m;}
 const context=(m=message(),item=treat)=>({actor,item,message:m,user:owner,action:item===visit?'medic:doctors-visitation':'medic:treat-condition'});
 return {api,deps,game,actor,patient,condition,healer,target,treat,visit,records,message,context,owner};
}
for(const [degree,want] of [[0,3],[1,2],[2,1],[3,null]])test(`applies native degree ${degree} to the selected embedded condition only`,async()=>{const f=fixture({degree});await f.api.executeUsage(f.context());assert.equal(f.patient.items.get('condition')?.system.value.value??null,want);assert.equal(f.records.rolls,1);});
test('two clients/recreated provider cannot replay one original card or cloned nonce',async()=>{const f=fixture();const ctx=f.context();await Promise.all([f.api.executeUsage(ctx),createMedicActions(f.deps).executeUsage(ctx)]);assert.equal(f.condition.system.value.value,1);assert.equal(f.records.rolls,1);await assert.rejects(()=>f.api.executeUsage(f.context(f.message(f.treat,'copy','use'))));assert.equal(f.records.rolls,1);});
test('condition changed during native dialog is not overwritten',async()=>{const f=fixture({rollMutation:({condition})=>condition.system.value.value=4});await assert.rejects(()=>f.api.executeUsage(f.context()));assert.equal(f.condition.system.value.value,4);});
test('rerolled native receipt is rejected',async()=>{const f=fixture();const original=f.deps.rollCheck;f.deps.rollCheck=async a=>{const r=await original(a);r.message.flags.pf2e.context.isReroll=true;return r;};await assert.rejects(()=>createMedicActions(f.deps).executeUsage(f.context()));assert.equal(f.condition.system.value.value,2);});
for(const [name,change]of [['non-owner',f=>f.owner.active=false],['draft/send',f=>f.ctx.message.flags[M].usageInput.actualUse=false],['foreign actor',f=>f.ctx.message.speaker.actor='other'],['inactive GM',f=>f.game.users.activeGM={id:'elsewhere'}]])test(`rejects ${name} before rolling`,async()=>{const f=fixture();f.ctx=f.context();change(f);await assert.rejects(()=>f.api.executeUsage(f.ctx));assert.equal(f.records.rolls,0);});
for(const [branch,cost]of [['battle-medicine',1],['treat-poison',1],['administer-first-aid',2],['treat-condition',2]])test(`Visitation ${branch} commits ${cost} actions once and waits for native movement`,async()=>{const f=fixture({branch});const m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));assert.deepEqual(f.records.commits,[cost]);assert.equal(f.records.rolls,0);await assert.rejects(()=>f.api.continueUsage(m,f.owner));await f.api.recordMovement(f.healer,{id:'move',passed:{cost:10,waypoints:[{action:'walk'}]}},{},f.owner);await f.api.continueUsage(m,f.owner);await f.api.continueUsage(m,f.owner);assert.equal(f.records.rolls,branch==='treat-condition'?1:0);assert.equal(f.records.delegated.length,branch==='treat-condition'?0:1);if(branch!=='treat-condition')assert.deepEqual(f.records.delegated[0],[branch,'Actor.healer','Scene.scene.Token.t','owner']);});
test('cancel after movement keeps flourish committed and rejects a second Visitation in the turn',async()=>{const f=fixture();const m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));await f.api.recordMovement(f.healer,{id:'move',passed:{cost:10,waypoints:[{action:'walk'}]}},{},f.owner);await f.api.continueUsage(m,f.owner,{cancel:true});await assert.rejects(()=>f.api.executeUsage(f.context(f.message(f.visit,'second'),f.visit)));assert.equal(f.records.rolls,0);assert.deepEqual(f.records.commits,[2]);});
test('continuation revalidates tools and turn after movement',async()=>{const f=fixture();const m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));await f.api.recordMovement(f.healer,{id:'move',passed:{cost:10,waypoints:[{action:'walk'}]}},{},f.owner);f.actor.handsFree=0;await assert.rejects(()=>f.api.continueUsage(m,f.owner));assert.equal(f.records.rolls,0);f.actor.handsFree=1;f.game.combat.round=2;await assert.rejects(()=>f.api.continueUsage(m,f.owner));assert.equal(f.records.rolls,0);});
test('teleport or wrong-owner movement never authorizes Stride continuation',async()=>{const f=fixture();const m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));await f.api.recordMovement(f.healer,{id:'move',passed:{cost:10,waypoints:[{action:'teleport'}]}},{},f.owner);await assert.rejects(()=>f.api.continueUsage(m,f.owner));assert.equal(f.records.rolls,0);});
test('a full copied finished card cannot impersonate its original durable receipt',async()=>{const f=fixture();const original=f.message();await f.api.executeUsage(f.context(original));const copy=f.message(f.treat,'copy','use');copy.flags[M].medic=structuredClone(original.flags[M].medic);await assert.rejects(()=>f.api.executeUsage(f.context(copy)));assert.equal(f.records.rolls,1);});
test('a check reconstructed by native ChatMessage creation retains its valid result',async()=>{const f=fixture();const original=f.deps.rollCheck;f.deps.rollCheck=async args=>{const r=await original(args);r.message.rolls=[structuredClone(r.roll)];return r;};await createMedicActions(f.deps).executeUsage(f.context());assert.equal(f.condition.system.value.value,1);});
test('inconsistent native outcome and roll degree never apply a condition',async()=>{const f=fixture();const original=f.deps.rollCheck;f.deps.rollCheck=async args=>{const r=await original(args);r.message.flags.pf2e.context.outcome='criticalFailure';return r;};await assert.rejects(()=>createMedicActions(f.deps).executeUsage(f.context()));assert.equal(f.condition.system.value.value,2);});
test('another native flourish in this turn blocks Visitation',async()=>{const f=fixture();const prior=f.message(f.treat,'prior');prior.flags[M].medicObservedFlourishTurn='fight:1:0';prior.flags.pf2e.origin.rollOptions=['origin:action:slug:use-action','origin:item:trait:flourish'];await assert.rejects(()=>f.api.executeUsage(f.context(f.message(f.visit),f.visit)));assert.deepEqual(f.records.commits,[]);});
test('copying a movement card cannot steal its original continuation',async()=>{const f=fixture();const m=f.message(f.visit);await f.api.executeUsage(f.context(m,f.visit));await f.api.recordMovement(f.healer,{id:'move',passed:{cost:10,waypoints:[{action:'walk'}]}},{},f.owner);const copied=f.message(f.visit,'copy','use');copied.flags[M].medic=structuredClone(m.flags[M].medic);await assert.rejects(()=>f.api.continueUsage(copied,f.owner));assert.equal(f.records.rolls,0);});
test('default native Medicine clone preserves its check pipeline, pins target and avoids generic Counteract state',async()=>{const f=fixture({degree:3});const check=f.deps.rollCheck;f.actor.getStatistic=()=>({clone(data){assert.deepEqual(data.check.domains,['counteract-check']);return {check:{roll:async args=>{context=args;const receipt=await check({nonce:'use',dc:args.dc.value});await args.callback(receipt.roll,'criticalSuccess',receipt.message);}}};}});f.deps.rollCheck=undefined;let context;
 await createMedicActions(f.deps).executeUsage(f.context());assert.equal(context.token,f.healer);assert.deepEqual(context.target.getActiveTokens(true,true),[f.target]);assert.equal(context.target.uuid,f.patient.uuid);assert.equal(context.messageMode,'blind');assert.equal(context.dc.visible,false);assert.equal(context.dc.slug,'medicine');assert.equal(context.extraRollOptions.includes('counteract'),false);assert.equal(context.skipDialog,false);assert.equal(f.patient.items.has('condition'),false);
});
const nativePath=process.env.PF2E_NATIVE_BUNDLE??'';
const addonPath=process.env.FVTT_COUNTERACT_MAIN??'';
test('installed StatisticCheck applies Medicine-check modifiers, degree adjustment, fortune and hooks without Counteract addon contamination',{skip:!existsSync(nativePath)||!existsSync(addonPath)},async()=>{
 const source=readFileSync(nativePath,'utf8'),start=source.indexOf('StatisticCheck = class {'),end=source.indexOf(', StatisticDifficultyClass =',start),classCode=source.slice(start+'StatisticCheck = '.length,end);
 const f=fixture({degree:3}),nativeReceipt=f.deps.rollCheck;f.deps.rollCheck=undefined;const observed={before:0,after:0};
 const modifier=value=>({modifier:value,adjustments:[],clone(){return modifier(value);}});
 f.actor.isOfType=(...types)=>types.includes('creature');f.patient.isOfType=f.actor.isOfType;f.treat.isOfType=(...types)=>types.includes('feat');
 f.actor.synthetics={modifierAdjustments:{},rollNotes:{},rollTwice:{},rollSubstitutions:{}};f.actor.rules=[{beforeRoll(){observed.before++;},afterRoll(){observed.after++;}}];
 const env={o:Boolean,M:values=>[...new Set(values)],_loc:key=>key,objectHasKey:(obj,key)=>Object.hasOwn(obj,key),foundry:{utils:{mergeObject:(a,b)=>Object.assign(a,b)}},extractModifierAdjustments:()=>[],extractModifiers:(_s,domains)=>domains.includes('medicine-check')?[modifier(3)]:[],StatisticModifier:class{constructor(_label,mods){this.totalModifier=mods.reduce((sum,m)=>sum+m.modifier,0);}},CheckModifier:class{constructor(_slug,data,extra){this.modifiers=[...data.modifiers,...extra];}},CheckContext:class{constructor(data){this.data=data;}async resolve(){return {...this.data,options:new Set()};}},extractNotes:()=>[],extractDegreeOfSuccessAdjustments:()=>[{adjustments:{success:{amount:1}}}],extractRollTwice:()=> 'keep-higher',extractRollSubstitutions:()=>[{slug:'native-substitution',value:12}],CONFIG:{PF2E:{actionTraits:{healing:'Healing',manipulate:'Manipulate'}}},Math:Object.assign(Object.create(Math),{clamp:(v,min,max)=>Math.min(max,Math.max(min,v))}),sluggify:s=>s,game:f.game,Sa:{roll:async(check,context,_event,callback)=>{
  observed.context=context;assert.equal(check.modifiers.reduce((n,m)=>n+m.modifier,0),11);assert.equal(context.rollTwice,'keep-higher');assert.equal(context.substitutions[0].value,12);assert.equal(context.dosAdjustments[0].adjustments.success.amount,1);
  const addon=readFileSync(addonPath,'utf8'),begin=addon.indexOf('function pf2ecac_patchCounteractDialog('),finish=addon.indexOf('async function pf2ecac_onPTCButtonClick',begin),fn=new Function('game',`${addon.slice(begin,finish)};return pf2ecac_patchCounteractDialog;`)({user:{isGM:true}});
  fn({context},[{querySelector(){throw Error('Generic Counteract listener must not attach to this native check.');}}]);assert.deepEqual(context.dc,{value:21,visible:false,slug:'medicine'});
  const receipt=await nativeReceipt({nonce:'use',dc:21});await callback(receipt.roll,'criticalSuccess',receipt.message);return receipt.roll;
 }}};
 const NativeCheck=new Function(...Object.keys(env),`return (${classCode});`)(...Object.values(env));
 const statistic=domains=>{const parent={actor:f.actor,slug:'medicine',label:'Medicine',domains:['medicine','skill-check'],modifiers:[modifier(8)],createRollOptions:()=>new Set()};parent.check=new NativeCheck(parent,{domains:parent.domains,check:{type:'skill-check',domains}});parent.clone=({check})=>statistic([...domains,...check.domains]);return parent;};
 f.actor.getStatistic=()=>statistic(['medicine-check']);await createMedicActions(f.deps).executeUsage(f.context());assert.equal(observed.before,1);assert.equal(observed.after,1);assert.equal(observed.context.target.token,f.target);assert.equal(observed.context.domains.includes('counteract-check'),true);assert.equal(f.patient.items.has('condition'),false);
});
