import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {getNativeActionEvents} from '../scripts/native-action-events.mjs';
import {createRoaringSource,reduceRoaringSource} from '../scripts/roaring-lifecycle.mjs';

const module=await import('../scripts/roaring-sustain.mjs').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return {}});
const create=module.createRoaringSustain,copy=structuredClone;
const SOURCE='Compendium.pf2e.spells-srd.Item.czO0wbT1i320gcu9';
class Message {constructor(data){Object.assign(this,data);this.documentName='ChatMessage'} }
globalThis.CONFIG={ChatMessage:{documentClass:Message}};
function fixture({mode,choice,onError}={}){
 assert.equal(typeof create,'function','Sustain consumer must exist');
 const users=new Map(['gm','player','stranger'].map(id=>[id,{id,active:true,isGM:id==='gm'}]));users.activeGM=users.get('gm');
 const caster={id:'caster',uuid:'Actor.caster',type:'character',canAct:true,isDead:false,testUserPermission:u=>['gm','player'].includes(u.id)},target={id:'target',uuid:'Actor.target',type:'npc'};
 const scene={id:'scene',tokens:new Map()},token={id:'casterToken',uuid:'Scene.scene.Token.casterToken',documentName:'Token',actor:caster,parent:scene};scene.tokens.set(token.id,token);caster.getActiveTokens=()=>[token];
 const combatant={id:'casterCombatant',actor:caster,token,initiative:20,flags:{pf2e:{roundOfLastTurnEnd:4}}},enemy={id:'enemy',initiative:20,flags:{pf2e:{roundOfLastTurnEnd:4}}},combat={id:'combat',scene,started:true,round:5,turn:0,turns:[combatant,enemy]};
 function frame(){return {combatId:'combat',combatantId:combatant.id,actorUuid:caster.uuid,tokenUuid:token.uuid,started:true,round:combat.round,turn:combat.turn,order:combat.turns.map(c=>({id:c.id,initiative:c.initiative,overridePriority:null})),lastTurnEnd:combatant.flags.pf2e.roundOfLastTurnEnd,latestTurnEndRound:Math.max(...combat.turns.map(c=>c.flags.pf2e.roundOfLastTurnEnd))}}
 const initial={...frame(),round:4,lastTurnEnd:3,latestTurnEndRound:3};
 let state=createRoaringSource({sourceNonce:'source-one',castNonce:'cast-one',sourceId:SOURCE,itemUuid:'Actor.caster.Item.spell',entryUuid:'Actor.caster.Item.entry',casterActorUuid:caster.uuid,casterTokenUuid:token.uuid,targetActorUuid:target.uuid,targetTokenUuid:'Scene.scene.Token.target',originalMessageUuid:'ChatMessage.original',rank:3,completedWorldTime:100,turn:initial,finiteEnvelope:{start:{value:100,initiative:20},duration:{value:1,unit:'rounds',expiry:'turn-end',sustained:false}}});
 state=reduceRoaringSource(state,{type:'save-confirmed',sourceNonce:state.sourceNonce,revision:1,receiptId:'save-one',outcome:'failure',observation:{worldTime:100,turn:initial}}).source;
 const record={revision:1,state,context:{gmId:'gm',userId:'player',immunity:{spell:false,slowed:false,fascinated:false}},effects:{status:'created'}},messages=new Map(),docs=new Map([[caster.uuid,caster],[target.uuid,target],[token.uuid,token]]);
 const original=new Message({id:'original',uuid:'ChatMessage.original',author:users.get('player'),speaker:{actor:caster.id,token:token.id,scene:scene.id},rolls:[],blind:false,whisper:[]});messages.set(original.id,original);docs.set(original.uuid,original);
 const clients={},events=[],errors=[],trace=[],rpc=[];let serial=0,calls=0,lastResult;
 const provider={listSources:()=>[{actor:target,record:copy(record)}],lookupSource:m=>m===original&&record.state.status==='active'?{sourceNonce:record.state.sourceNonce,...record.state.source,gmId:record.context.gmId}:null,
  applyLifecycleEvent:async({actor,nonce,event})=>{assert.equal(actor,target);assert.equal(nonce,'source-one');events.push(copy(event));const out=reduceRoaringSource(record.state,{...event,sourceNonce:nonce,observation:{worldTime:clients.gm.game.time.worldTime,turn:frame()}});record.state=out.source;record.revision++;return out}};
 for(const id of ['gm','player']){
  const game={world:{id:'ujx5r8oipw7ercdr'},system:{id:'pf2e',version:'8.5.1'},user:users.get(id),users,actors:new Map([[caster.id,caster],[target.id,target]]),scenes:new Map([[scene.id,scene]]),combats:new Map([[combat.id,combat]]),messages,time:{worldTime:106},pf2e:{actions:new Map()}};
  const action={slug:'sustain',cost:1,traits:['concentrate'],variants:new Map(),toActionVariant(){return {slug:'sustain',cost:1,traits:['concentrate'],use:async(params={})=>{
   calls++;trace.push('native');if(mode==='throw')throw Error('native throw');
   let message=new Message({id:`use${++serial}`,uuid:`ChatMessage.use${serial}`,author:users.get(id),speaker:{actor:caster.id,scene:scene.id,token:token.id},rolls:[],blind:false,whisper:[]});
   if(mode==='wrong-author')message.author=users.get('stranger');if(mode==='wrong-speaker')message.speaker.token='other';if(mode==='private')message.whisper=['gm'];
   if(mode!=='draft'&&params.message?.create!==false){messages.set(message.id,message);docs.set(message.uuid,message)}
   if(mode==='old-card')message=original;if(mode==='veto')message=undefined;if(mode==='turn-change')combat.turn=1;if(mode==='gm-change')users.activeGM=users.get('stranger');
   if(mode==='incap-after')caster.canAct=false;
   lastResult=[{actor:mode==='wrong-actor'?target:caster,effect:undefined,message}];return lastResult;
  }}}};game.pf2e.actions.set('sustain',action);game.user.getActiveTokens=()=>[token];
  const actionEvents=getNativeActionEvents({game}),hooks=new Map(),handlers=new Map();
  actionEvents.addMiddleware((_s,next)=>{trace.push('prayer');return next()});
  const socket={register:(n,fn)=>handlers.set(n,fn),executeAsUser:async(n,to,p)=>{rpc.push({from:id,to,name:n});return clients[to].handlers.get(n).call({socketdata:{userId:id}},copy(p))}};
  const Hooks={on:(n,fn)=>{hooks.set(n,fn);return n},off:n=>hooks.delete(n)};
  const consumer=create({game,provider,fromUuid:async u=>docs.get(u),actionEvents,choose:async p=>{trace.push('choose');return typeof choice==='function'?choice({game,action,...p}):choice===undefined?p.choices.find(c=>c.value==='source-one')?.value:choice},onError:onError??(e=>errors.push(e)),randomId:()=>`nonce-${++serial}`});
  consumer.register({Hooks,socket});clients[id]={consumer,game,action,actionEvents,hooks,handlers,Hooks,socket};
 }
 return {clients,provider,record,users,caster,target,token,combat,combatant,original,messages,docs,events,errors,trace,rpc,frame,run:params=>clients.player.action.toActionVariant().use(params??{actors:[caster]}),calls:()=>calls,result:()=>lastResult,cleanup:()=>Object.values(clients).forEach(c=>{c.consumer.cleanup();c.actionEvents.cleanup()})};
}
const useOf=f=>Object.values(f.record.state.sustainUses)[0];
const settle=(f,terminal='completed')=>f.clients.gm.consumer.adjudicate({sourceNonce:'source-one',useNonce:useOf(f)?.useNonce,terminal});

test('branded player Use records one pending fact after Prayer and returns exact native rows',async t=>{const f=fixture();t.after(f.cleanup);const rows=await f.run();assert.equal(rows,f.result());assert.equal(f.calls(),1);assert.deepEqual(f.trace,['prayer','choose','native']);assert.equal(f.events.length,1);assert.equal(f.events[0].type,'sustain-use');assert.equal(useOf(f).status,'use-recorded');assert.equal(f.record.state.timing.deadline.endRound,5);assert.ok(f.rpc.some(r=>r.from==='gm'&&r.to==='player'&&r.name.endsWith(':proof')));});
test('GM completion extends only frozen Use turn; same-turn second completion never adds a round',async t=>{const f=fixture();t.after(f.cleanup);await f.run();await settle(f);assert.equal(f.record.state.timing.deadline.endRound,6);await f.run();const use=Object.values(f.record.state.sustainUses).at(-1);await f.clients.gm.consumer.adjudicate({sourceNonce:'source-one',useNonce:use.useNonce,terminal:'completed'});assert.equal(f.record.state.timing.deadline.endRound,6);assert.equal(f.calls(),2);});
test('late GM completion does not resurrect source after its actual next end',async t=>{const f=fixture();t.after(f.cleanup);await f.run();f.combat.turn=1;f.combatant.flags.pf2e.roundOfLastTurnEnd=5;await settle(f);assert.equal(f.record.state.status,'ended');assert.equal(f.record.state.timing.deadline.endRound,5);});
test('GM disrupted ends source without a second native Use or payment',async t=>{const f=fixture();t.after(f.cleanup);await f.run();await settle(f,'disrupted');assert.equal(f.record.state.termination.reason,'sustain-disrupted');assert.equal(f.calls(),1);assert.deepEqual(f.events.map(e=>e.type),['sustain-use','sustain-settled']);});
for(const mode of ['draft','veto','wrong-author','wrong-speaker','wrong-actor','private','turn-change','gm-change'])test(`${mode} native return never records Use or renews`,async t=>{const f=fixture({mode});t.after(f.cleanup);await f.run();assert.equal(f.calls(),1);assert.equal(f.events.length,0);assert.equal(f.record.state.timing.deadline.endRound,5);});
test('native throw preserves original failure and never records/retries',async t=>{const f=fixture({mode:'throw'});t.after(f.cleanup);await assert.rejects(f.run(),/native throw/);assert.equal(f.calls(),1);assert.equal(f.events.length,0);});
test('incapacitation after native Use does not invent disruption or invalidate the recorded fact',async t=>{const f=fixture({mode:'incap-after'});t.after(f.cleanup);await f.run();assert.equal(f.events.length,1);await settle(f);assert.equal(f.record.state.timing.deadline.endRound,6);});
test('cancel never calls native; other-effect choice preserves native with no managed fact',async t=>{const f=fixture({choice:null}),g=fixture({choice:'manual'});t.after(f.cleanup);t.after(g.cleanup);assert.equal(await f.run(),undefined);assert.equal(f.calls(),0);await g.run();assert.equal(g.calls(),1);assert.equal(g.events.length,0);});
test('draft original input and unrelated branded action stay original',async t=>{const f=fixture();t.after(f.cleanup);await f.run({actors:[f.caster],message:{create:false}});assert.deepEqual(f.trace,['native']);assert.equal(f.events.length,0);f.clients.player.action.slug='other';await f.run();assert.equal(f.calls(),2);assert.equal(f.events.length,0);});
test('source actor cannot start managed Use when dead or incapacitated',async t=>{const f=fixture();t.after(f.cleanup);f.caster.canAct=false;await assert.rejects(f.run());assert.equal(f.calls(),0);assert.equal(f.events.length,0);});
test('player cannot adjudicate and forged claim without native scope cannot mutate source',async t=>{const f=fixture();t.after(f.cleanup);await f.run();await assert.rejects(f.clients.player.consumer.adjudicate({sourceNonce:'source-one',useNonce:useOf(f).useNonce,terminal:'completed'}));const handler=[...f.clients.gm.handlers].find(([n])=>n.endsWith(':record'))[1];const r=await handler.call({socketdata:{userId:'stranger'}},{useNonce:'forged',sourceNonce:'source-one'});assert.equal(r.ok,false);assert.equal(f.events.length,1);});
test('unknown verdict does nothing; duplicate exact verdict is harmless; conflicting verdict refuses',async t=>{const f=fixture();t.after(f.cleanup);await f.run();await settle(f,'unknown');assert.equal(f.events.length,1);await settle(f);await settle(f);assert.equal(f.record.state.timing.deadline.endRound,6);await assert.rejects(settle(f,'disrupted'));assert.equal(f.record.state.status,'active');});
test('deleted Use card and GM handoff cannot adjudicate old controls',async t=>{const f=fixture();t.after(f.cleanup);await f.run();f.messages.delete(useOf(f).messageUuid.split('.').at(-1));await assert.rejects(settle(f));assert.equal(f.events.length,1);});

test('native return of an already existing card cannot prove a new Use',async t=>{const f=fixture({mode:'old-card'});t.after(f.cleanup);await f.run();assert.equal(f.events.length,0);assert.equal(f.calls(),1);});
test('action changed during source chooser is rejected before native Use',async t=>{const f=fixture({choice:({action})=>{action.cost=2;return 'source-one'}});t.after(f.cleanup);await assert.rejects(f.run());assert.equal(f.calls(),0);});
test('reporter failure cannot replace a successful native return or retry it',async t=>{const f=fixture({mode:'draft',onError:()=>{throw Error('report failed')}});t.after(f.cleanup);assert.equal(await f.run(),f.result());assert.equal(f.calls(),1);});

function element(tag='div',doc){
 const e={tag,children:[],dataset:{},listeners:{},ownerDocument:doc,textContent:'',append(n){this.children.push(n);n.parent=this},remove(){this.parent.children=this.parent.children.filter(c=>c!==this)},querySelector(selector){if(selector==='[data-roaring-controls]')return this.children.find(c=>Object.hasOwn(c.dataset,'roaringControls'));return null},addEventListener(n,fn){this.listeners[n]=fn}};return e;
}
function html(){const doc={createElement:tag=>element(tag,doc)};return element('root',doc)}
const click=async button=>{button.listeners.click({preventDefault(){},stopPropagation(){}});for(let i=0;i<12;i++)await Promise.resolve()};
test('original-card GM controls bind exact Use; player sees no verdict buttons',async t=>{const f=fixture();t.after(f.cleanup);await f.run();const root=html();f.clients.gm.hooks.get('renderChatMessageHTML')(f.original,root);f.clients.gm.hooks.get('renderChatMessageHTML')(f.original,root);assert.equal(root.children.length,1);const buttons=root.children[0].children.filter(e=>e.tag==='button');assert.equal(buttons.length,3);await click(buttons.find(b=>b.textContent.includes('已完成')));assert.equal(f.record.state.timing.deadline.endRound,6);const player=html();f.clients.player.hooks.get('renderChatMessageHTML')(f.original,player);assert.equal(player.children[0].children.filter(e=>e.tag==='button').length,0);});
test('end-own-fascination button records tombstone only and never dismisses source',async t=>{const f=fixture();t.after(f.cleanup);f.record.state.result.outcome='criticalFailure';const root=html();f.clients.gm.hooks.get('renderChatMessageHTML')(f.original,root);const button=root.children[0].children.find(e=>e.tag==='button'&&e.textContent==='结束本源迷魂');assert.ok(button);await click(button);assert.equal(f.record.state.status,'active');assert.ok(f.record.state.tombstones.fascinated);assert.equal(f.record.state.tombstones.slowed,null);assert.deepEqual(f.events.map(e=>e.type),['end-fascination']);f.clients.gm.hooks.get('renderChatMessageHTML')(f.original,root);assert.equal(root.children[0].children.some(e=>e.textContent==='结束本源迷魂'),false);});
for(const immune of ['spell','fascinated'])test(`${immune} immunity never claims a Fascinated condition in source controls`,async t=>{const f=fixture();t.after(f.cleanup);f.record.state.result.outcome='criticalFailure';f.record.context.immunity[immune]=true;const root=html();f.clients.gm.hooks.get('renderChatMessageHTML')(f.original,root);assert.equal(root.children[0].children.some(e=>e.textContent==='结束本源迷魂'),false);await assert.rejects(f.clients.gm.consumer.endFascination('source-one'));if(immune==='spell')assert.equal(root.children[0].children.some(e=>e.textContent.startsWith('禁反应')),false);assert.equal(f.events.length,0);});
test('known hard cap reached before selection cannot consume another managed native Use',async t=>{const f=fixture();t.after(f.cleanup);f.clients.player.game.time.worldTime=700;await assert.rejects(f.run());assert.equal(f.calls(),0);});

for(const field of ['source','turn','gmId','messageUuid'])test(`tampered native proof ${field} cannot record a Use`,async t=>{const f=fixture();t.after(f.cleanup);const [name,fn]=[...f.clients.player.handlers].find(([name])=>name.endsWith(':proof'));f.clients.player.handlers.set(name,async function(p){const r=await fn.call(this,p);if(r.ok){if(field==='source')r.value.source.castNonce='other';else if(field==='turn')r.value.turn.round=99;else r.value[field]='other'}return r});await f.run();assert.equal(f.calls(),1);assert.equal(f.events.length,0);});
test('lost response after recorded Use never repeats native or replays registration',async t=>{const f=fixture();t.after(f.cleanup);const call=f.clients.player.socket.executeAsUser;f.clients.player.socket.executeAsUser=async(...args)=>{const r=await call(...args);if(args[0].endsWith(':record'))throw Error('lost reply');return r};await f.run();assert.equal(f.calls(),1);assert.equal(f.events.length,1);assert.equal(useOf(f).status,'use-recorded');assert.equal(f.errors.length,1);await settle(f);assert.equal(f.record.state.timing.deadline.endRound,6);});
test('same-GM re-registration may adjudicate a persisted Use but cannot revive its local proof',async t=>{const f=fixture();t.after(f.cleanup);await f.run();const c=f.clients.gm;c.consumer.cleanup();c.consumer.register({Hooks:c.Hooks,socket:c.socket});await settle(f);assert.equal(f.record.state.timing.deadline.endRound,6);const proof=[...f.clients.player.handlers].find(([n])=>n.endsWith(':proof'))[1];const result=await proof.call({socketdata:{userId:'gm'}},{sourceNonce:'source-one',useNonce:useOf(f).useNonce});assert.equal(result.ok,false);});
test('GM handoff rejects an old pending control without giving a new deadline',async t=>{const f=fixture();t.after(f.cleanup);await f.run();f.users.activeGM=f.users.get('stranger');await assert.rejects(settle(f));assert.equal(f.events.length,1);});
test('stale original-card control cannot adjudicate a changed persisted Use',async t=>{const f=fixture();t.after(f.cleanup);await f.run();const root=html();f.clients.gm.hooks.get('renderChatMessageHTML')(f.original,root);const button=root.children[0].children.find(e=>e.textContent==='确认这次维持已完成');useOf(f).turn.round=99;await click(button);assert.equal(f.events.length,1);assert.equal(f.record.state.timing.deadline.endRound,5);assert.equal(f.errors.length,1);});
test('tombstone with exact child still present shows incomplete deletion without another button',async t=>{const f=fixture();t.after(f.cleanup);f.record.state.result.outcome='criticalFailure';f.record.state.tombstones.fascinated={reason:'gm-fascination-ended',receiptId:'one'};f.record.effects.parentId='parent';f.record.effects.children={fascinated:{id:'child',uuid:'Actor.target.Item.child'}};f.target.items=new Map([['child',{id:'child',uuid:'Actor.target.Item.child'}]]);const root=html();f.clients.gm.hooks.get('renderChatMessageHTML')(f.original,root);assert.ok(root.children[0].children.some(e=>e.textContent.includes('条件尚未清除')));assert.equal(root.children[0].children.some(e=>e.textContent==='结束本源迷魂'),false);f.target.items.clear();f.clients.gm.hooks.get('renderChatMessageHTML')(f.original,root);assert.equal(root.children[0].children.some(e=>e.textContent.includes('条件尚未清除')),false);});
test('manual finite timing forbids renewal but still permits exact GM disruption fact',async t=>{const f=fixture();t.after(f.cleanup);await f.run();f.record.state.timing.mode='manual-finite';await assert.rejects(settle(f));await settle(f,'disrupted');assert.equal(f.record.state.status,'ended');assert.equal(f.record.state.termination.reason,'sustain-disrupted');});
test('actual item deletion refreshes original-card cleanup status without lifecycle replay',async t=>{const f=fixture();t.after(f.cleanup);const old=globalThis.ui,refreshed=[];globalThis.ui={chat:{updateMessage:m=>refreshed.push(m)}};t.after(()=>{globalThis.ui=old});f.clients.gm.hooks.get('deleteItem')?.({actor:f.target});await Promise.resolve();await Promise.resolve();assert.deepEqual(refreshed,[f.original]);assert.equal(f.events.length,0);});

const nativePath=process.env.PF2E_NATIVE_BUNDLE??'';
test('actual PF SimpleAction Sustain returns a new live actor/card row and native veto stays unrecorded',{skip:!nativePath},async t=>{
 const f=fixture();t.after(f.cleanup);const source=readFileSync(nativePath,'utf8'),start=source.indexOf('var BaseActionVariant = class {'),end=source.indexOf('function toRollNoteSource',start);assert.ok(start>=0&&end>start);
 let cards=0,veto=false;
 class NativeMessage extends Message {static async create(data){if(veto)return undefined;const m=new NativeMessage({id:`native${++cards}`,uuid:`ChatMessage.native${cards}`,author:f.users.get('player'),rolls:[],blind:false,whisper:[],...data});f.messages.set(m.id,m);f.docs.set(m.uuid,m);return m}}
 const config={PF2E:{actionTraits:{concentrate:'Concentrate'},traitsDescriptions:{}}},foundry={applications:{handlebars:{renderTemplate:async()=>'<native flavor>'}}};
 const SimpleAction=new Function('Collection','sluggify','getActionGlyph','_loc','CONFIG','foundry','ChatMessagePF2e','ChatMessage','getSelectedActors',`${source.slice(start,end)};return SimpleAction;`)(Map,s=>s.toLowerCase().replaceAll(' ','-'),()=>1,s=>s,config,foundry,NativeMessage,{getSpeaker:({actor})=>({actor:actor.id,scene:f.token.parent.id,token:f.token.id})},()=>[f.caster]);
 const code=source.match(/hm = new SimpleAction\(\{[\s\S]*?slug: `sustain`,[\s\S]*?\}\)/)?.[0];assert.ok(code);const action=new Function('SimpleAction',`return ${code.slice('hm = '.length)}`)(SimpleAction),c=f.clients.player;c.game.pf2e.actions.set('sustain',action);c.actionEvents.register();
 const rows=await action.use({actors:[f.caster]});assert.equal(cards,1);assert.equal(rows[0].actor,f.caster);assert.equal(rows[0].message,f.messages.get('native1'));assert.equal(useOf(f).messageUuid,'ChatMessage.native1');assert.equal(f.record.state.timing.deadline.endRound,5);
 await action.toMessage();assert.equal(f.events.length,1);veto=true;await action.use({actors:[f.caster]});assert.equal(f.events.length,1);assert.equal(f.record.state.timing.deadline.endRound,5);
});
