import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {registerRoaringReactionCompatibility} from '../scripts/roaring-reaction-compat.mjs';
const MOD='pf2e-reaction',BUNDLE='4a81322796ce1c6ed545edc09e1aa3a96a9c8a96dfd034403bf657068ed7036c',CALLBACK='5d2a14c36862e10b963978b68ed7b5d5741993ef83169202658220eef18319b1';
const KEYS=['state','hydra-heads','triple-opportunity','combat-reflexes','tactical-reflexes','inexhaustible-countermoves','reflexive-riposte','quick-shield-block'];
function fixture(){
 const actor={id:'actor',uuid:'Actor.actor',name:'Target',itemTypes:{condition:[]}},combat={id:'combat',combatants:new Map(),turns:[]},raw=Object.fromEntries(KEYS.map(k=>[k,k==='state'?true:2]));
 const calls={query:[],native:[],notices:[],writes:[],update:[],delete:[],post:[]},registrations=new Map(),listeners=new Set(),module={active:true,version:'1.4.3'};
 const combatant={id:'member',_id:'member',actor,parent:combat,token:{name:'Target'},getFlag(...args){calls.native.push({receiver:this,args});return args[0]===MOD?raw[args[1]]:73},async setFlag(scope,key,value){calls.writes.push({scope,key,value});raw[key]=value}};combat.turns=[combatant];combat.combatants.set(combatant.id,combatant);
 const flags={cId:'member',uuid:'Actor.actor.Item.reaction',actionName:'shield-block',count:1,reactions:1};
 const message={id:'card',uuid:'ChatMessage.card',permission:3,flags:{[MOD]:flags},getFlag:(s,k)=>message.flags[s]?.[k],async update(change){calls.update.push(change)},async delete(){calls.delete.push(message.id)}};
 const game={world:{id:'ujx5r8oipw7ercdr'},system:{id:'pf2e',version:'8.5.1'},release:{generation:14},modules:new Map([[MOD,module]]),combats:new Map([[combat.id,combat]]),combat,messages:new Map([[message.id,message]]),user:{id:'gm',isGM:true},i18n:{format:()=> 'text'}};
 const root={messageId:'card',parentElement:null},middle={parentElement:root},inner={parentElement:middle},button={parentElement:inner,closest:selector=>selector==='.reaction-check'?button:null};
 const document={addEventListener:(n,fn,capture)=>{assert.equal(n,'click');assert.equal(capture,true);listeners.add(fn)},removeEventListener:(n,fn,capture)=>{assert.equal(capture,true);listeners.delete(fn)},contains:el=>el===button};
 function $(node){return {parent:()=>$(node.parentElement),data:key=>key==='message-id'?node.messageId:undefined}};
 const original=async function originalReactionClick(){},entry={type:'click',origType:'click',selector:'.reaction-check',namespace:'',guid:12,handler:original},entries=[entry];$._data=(d,k)=>d===document&&k==='events'?{click:entries}:undefined;
 let serial=0,status='clear';
 const libWrapper={register(module,path,wrapper,type){const id=++serial;registrations.set(id,{module,path,wrapper,type});return id},unregister(module,id){assert.equal(registrations.get(id)?.module,module);registrations.delete(id)}};
 const query=a=>{calls.query.push(a);return {status}},notify=x=>calls.notices.push(x);
 const options={game,document,jQuery:$,libWrapper,query,notify,fetchSource:async()=> 'bundle',hashSource:async value=>value==='bundle'?BUNDLE:CALLBACK};
 const install=extra=>registerRoaringReactionCompatibility({...options,...extra});
 const get=(scope=MOD,key='state',...extra)=>{const r=[...registrations.values()][0];return r?r.wrapper.call(combatant,combatant.getFlag.bind(combatant),scope,key,...extra):combatant.getFlag(scope,key,...extra)};
 const event=()=>({target:button,stopped:false,prevented:false,stopImmediatePropagation(){this.stopped=true},preventDefault(){this.prevented=true}});
 async function click(){const e=event();for(const fn of listeners)fn(e);if(!e.stopped)await entry.handler.call(button);return e}
 return {actor,combat,combatant,raw,calls,game,module,message,flags,entry,entries,document,$,button,root,libWrapper,registrations,listeners,options,install,get,event,click,setStatus:v=>{status=v}};
}
test('verified registration is idempotent and disposes only its own wrapper/listener',async()=>{const f=fixture(),original=f.entry.handler,[a,b]=await Promise.all([f.install(),f.install()]);assert.equal(a,b);assert.equal(a.status,'installed');assert.equal(a.ready(),true);assert.equal(f.registrations.size,1);assert.equal(f.listeners.size,1);const foreign=()=>{};f.listeners.add(foreign);f.registrations.set(99,{module:'foreign'});a.dispose();a.dispose();assert.equal(a.ready(),false);assert.equal(f.registrations.size,1);assert.equal(f.listeners.has(foreign),true);assert.equal(f.entry.handler,original)});
test('restricted masks exactly eight keys without writing raw state; manual preserves reads',async()=>{const f=fixture();await f.install();const before=structuredClone(f.raw);f.setStatus('restricted');for(const key of KEYS)assert.equal(f.get(MOD,key),key==='state'?false:0);assert.deepEqual(f.raw,before);assert.equal(f.calls.writes.length,0);f.setStatus('manual');for(const key of KEYS)assert.equal(f.get(MOD,key),before[key]);f.setStatus('clear');assert.equal(f.get(),true)});
test('unrelated getFlag preserves receiver, argument list and return without querying',async()=>{const f=fixture();await f.install();assert.equal(f.get('other','state','default'),73);assert.equal(f.get(MOD,'other'),undefined);assert.equal(f.calls.query.length,0);assert.equal(f.calls.native[0].receiver,f.combatant);assert.deepEqual(f.calls.native[0].args,['other','state','default']);const foreign={...f.combatant};assert.equal([...f.registrations.values()][0].wrapper.call(foreign,()=>42,MOD,'state'),42)});
for(const status of ['restricted','manual'])test(`${status} old card is stopped synchronously before native handler`,async()=>{const f=fixture();let native=0;f.entry.handler=async()=>native++;await f.install();f.setStatus(status);const e=await f.click();assert.equal(e.stopped,true);assert.equal(e.prevented,true);assert.equal(native,0);assert.equal(f.calls.notices.length,1);assert.match(f.calls.notices[0],/GM/)});
test('clear old card leaves native handler, click event and nonActor item references untouched',async()=>{const f=fixture();f.flags.uuid='Compendium.pf2e.feats-srd.Item.any';let receiver;f.entry.handler=async function(){receiver=this};await f.install();const e=await f.click();assert.equal(e.stopped,false);assert.equal(e.prevented,false);assert.equal(receiver,f.button);assert.equal(f.calls.notices.length,0)});
for(const [name,mutate]of Object.entries({missingCard:f=>f.game.messages.clear(),wrongViewed:f=>f.game.combat={...f.combat},detachedMember:f=>f.combat.combatants.delete('member'),ambiguous:f=>{const c={id:'other',combatants:new Map(),turns:[]},m={...f.combatant,parent:c};c.turns=[m];c.combatants.set(m.id,m);f.game.combats.set(c.id,c)},unknownCid:f=>f.flags.cId='missing'}))test(`ambiguous or missing native routing is manual: ${name}`,async()=>{const f=fixture();await f.install();mutate(f);const e=await f.click();assert.equal(e.stopped,true);assert.equal(f.calls.notices.length,1)});
for(const [name,mutate]of Object.entries({world:f=>f.game.world.id='other',system:f=>f.game.system.version='future',version:f=>f.module.version='future',inactive:f=>f.module.active=false,duplicate:f=>f.entries.push({...f.entry}),handlerProfile:f=>f.entry.origType='keydown'}))test(`unverified ${name} installs nothing`,async()=>{const f=fixture();mutate(f);const r=await f.install();assert.equal(r.status,'unsupported');assert.equal(f.listeners.size,0);assert.equal(f.registrations.size,0)});
for(const which of ['bundle','callback'])test(`wrong ${which} hash installs nothing`,async()=>{const f=fixture();const r=await f.install({hashSource:async s=>(s==='bundle')===(which==='bundle')?'wrong':s==='bundle'?BUNDLE:CALLBACK});assert.equal(r.status,'unsupported');assert.equal(f.listeners.size,0);assert.equal(f.registrations.size,0)});
test('handler identity changing while verification awaits cannot install',async()=>{const f=fixture();const r=await f.install({fetchSource:async()=>{f.entry.handler=()=>{};return 'bundle'}});assert.equal(r.status,'unsupported');assert.equal(f.registrations.size,0)});
test('runtime handler/module identity loss disables readiness and masking',async()=>{const f=fixture(),r=await f.install();f.setStatus('restricted');f.entry.handler=()=>{};assert.equal(r.ready(),false);assert.equal(f.get(),true);r.dispose()});
test('unknown or throwing query preserves native reads but sends old clicks to GM review',async()=>{for(const query of [()=>undefined,()=>({status:'future'}),()=>{throw Error('unavailable')}]){const f=fixture();await f.install({query});assert.equal(f.get(),true);assert.equal((await f.click()).stopped,true);assert.equal(f.calls.notices.length,1)}});
test('module identity replacement cannot retain a ready adapter',async()=>{const f=fixture(),r=await f.install();f.setStatus('restricted');f.game.modules.set(MOD,{...f.module});assert.equal(r.ready(),false);assert.equal(f.get(),true);r.dispose()});

const nativePath=process.env.FVTT_REACTION_BUNDLE??'';
test('actual audited Ma/R/Na/q and delegated click preserve costs or stop before all native side effects',{skip:!nativePath},async()=>{
 const bundle=readFileSync(nativePath,'utf8'),sha=s=>createHash('sha256').update(s).digest('hex');assert.equal(sha(bundle),BUNDLE);
 const slice=(start,end)=>bundle.slice(bundle.indexOf(start),bundle.indexOf(end,bundle.indexOf(start)));
 const ma=slice('function Ma(','let qa='),rr=slice('function R(','function x('),na=slice('async function Na(','function Oa('),oa=slice('function Oa(','function Ma('),qq=slice('async function q(','async function La('),click=slice('async function(){var a=$(this).parent().parent().parent().data("message-id")','),$(document).on("click",".reaction-cancel"');assert.equal(sha(click),CALLBACK);
 for(const status of ['clear','restricted','manual'])for(const skip of [false,true])for(const post of [false,true])for(const count of [1,2]){
  const f=fixture(),w={postMessage:post,addReactionEffect:false,allReactionEffect:false};let qCalls=0,posts=0;const item={system:{frequency:{value:2}},async update(c){this.system.frequency.value=c['system.frequency.value']},async toMessage(){posts++}};
  const getFeat=(_a,slug)=>['combat-reflexes','quick-shield-block'].includes(slug)?{}:null;
  const native=Function('S','qa','I','p','F','i','H','Ja','ui','w','Ga','La','xa','Aa',ma+rr+na+oa+qq+';return {Ma,R,Na,q};')(MOD,['orc-ferocity'],()=>false,()=>false,()=>null,()=>null,getFeat,()=>true,{notifications:{warn:()=>{}}},w,()=>null,()=>assert.fail('unexpected effect'),'effect','all');
  f.entry.handler=Function('$','game','S','q','w','fromUuid','renderTemplate','k',`return (${click})`)(f.$,f.game,MOD,async(...args)=>{qCalls++;return native.q(...args)},w,async()=>item,async()=> 'rendered',{_sendRequest:()=>assert.fail('unexpected socket')});
  const r=await f.install({fetchSource:async()=>bundle,hashSource:async s=>sha(s)});assert.equal(r.status,'installed');f.setStatus(status);f.flags.skipReaction=skip;f.flags.count=count;f.flags.reactions=count;const original=f.combatant.getFlag;f.combatant.getFlag=(...args)=>[...f.registrations.values()][0].wrapper.call(f.combatant,original.bind(f.combatant),...args);
  for(const kind of [undefined,'reactive-strike','attack-of-opportunity','opportune-riposte','shield-block','orc-ferocity']){assert.equal(native.Ma(f.combatant,kind)>0,status!=='restricted');assert.equal(native.R(f.combatant,kind),status!=='restricted')}
  const before=structuredClone(f.raw);const e=await f.click();if(status==='clear'){assert.equal(e.stopped,false);assert.equal(qCalls,skip?0:1);assert.equal(f.calls.delete.length,count===1?1:0);assert.equal(f.calls.update.length,count===2?1:0);if(count===2){assert.equal(f.calls.update[0]['flags.pf2e-reaction.count'],1);assert.equal(f.calls.update[0]['flags.pf2e-reaction.reactions'],1)}assert.equal(f.raw['quick-shield-block'],skip?2:1);assert.equal(f.raw.state,true);assert.equal(posts,post?1:0);assert.equal(item.system.frequency.value,post?1:2)}else{assert.equal(e.stopped,true);assert.equal(qCalls,0);assert.equal(f.calls.delete.length,0);assert.equal(f.calls.update.length,0);assert.equal(posts,0);assert.equal(item.system.frequency.value,2);assert.deepEqual(f.raw,before)}
  f.raw.state=false;await native.Na(f.combatant,true);assert.equal(f.raw.state,true);f.setStatus('clear');assert.equal(f.combatant.getFlag(MOD,'state'),true);r.dispose();
 }
});
