import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture as base} from './glimpse-fixture.mjs';
import {spiritualScarExpiryFor} from '../scripts/spiritual-scar-expiry.mjs';
import {SPIRITUAL_SCAR_SOURCE} from '../scripts/spiritual-scar-native.mjs';
const M='pf2e-third-party-automation';
let api={};try{api=await import('../scripts/spiritual-scar-followup.mjs')}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e}
function patch(doc,data){for(const[path,value]of Object.entries(data)){const parts=path.split('.');let at=doc;for(const k of parts.slice(0,-1))at=at[k]??={};at[parts.at(-1)]=structuredClone(value)}}
function fixture(){
 assert.equal(typeof api.createSpiritualScarFollowup,'function');const f=base(),calls={rolls:[],created:[],errors:[]};let allowed=true,degree=1,mutate=()=>{},seq=0;
 const events=new Map(),Hooks={on(e,fn){const id=++seq;events.set(id,{e,fn});return id},off(_e,id){events.delete(id)},call(e,...args){for(const v of events.values())if(v.e===e&&v.fn(...args)===false)return false;return true}};
 f.game.world={id:'ujx5r8oipw7ercdr'};f.game.system={id:'pf2e',version:'8.5.1'};f.game.time={worldTime:100};f.ally.classDC={dc:21};f.enemy.system.traits.value=['fiend'];
 const ability={id:'scar',uuid:f.ally.uuid+'.Item.scar',actor:f.ally,type:'action',sourceId:SPIRITUAL_SCAR_SOURCE,img:'scar.webp',system:{traits:{value:['concentrate']}}};f.ally.items.set(ability.id,ability);f.docs.set(ability.uuid,ability);
 const claim={nonce:'original-scar',itemUuid:ability.uuid,actorUuid:f.ally.uuid,tokenUuid:f.allyToken.uuid,source:{sourceActorUuid:f.enemy.uuid,sourceTokenUuid:f.enemyToken.uuid},expiry:spiritualScarExpiryFor(f.allyToken,f.game)};
 const damageMessage=f.message;damageMessage.flags.pf2e.appliedDamage={isReverted:false};damageMessage.update=async data=>{patch(damageMessage,data);return damageMessage};
 f.enemy.getStatistic=name=>name==='will'?{async roll(options){
  calls.rolls.push(options);const roll={total:12,_evaluated:true,options:{degreeOfSuccess:degree},toJSON:()=>({evaluated:true})};
  const card={id:'save-'+(++seq),author:f.user,isCheckRoll:true,actor:f.enemy,speaker:{actor:f.enemy.id,scene:f.scene.id,token:f.enemyToken.id},rolls:[roll],blind:false,whisper:[],flags:{pf2e:{origin:{actor:f.ally.uuid,uuid:ability.uuid},context:{type:'saving-throw',action:options.action,options:[...options.extraRollOptions],origin:{actor:f.ally.uuid,token:f.allyToken.uuid},target:{actor:f.enemy.uuid,token:f.enemyToken.uuid},dc:{slug:'class',value:21},outcome:['criticalFailure','failure','success','criticalSuccess'][degree]}}},updateSource(data){patch(this,data)}};
  mutate(card);if(Hooks.call('preCreateChatMessage',card,{}, {},f.user.id)===false)return null;f.game.messages.set(card.id,card);await options.callback(roll,card.flags.pf2e.context.outcome,card);return roll;
 }}:null;
 f.enemy.createEmbeddedDocuments=async(type,data)=>{assert.equal(type,'Item');calls.created.push(...structuredClone(data));const items=data.map((d,i)=>({id:'effect-'+i,uuid:f.enemy.uuid+'.Item.effect-'+i,actor:f.enemy,...structuredClone(d)}));for(const item of items)f.enemy.items.set(item.id,item);return items};
 const expiry={async settle(){}};const executor=api.createSpiritualScarFollowup({game:f.game,fromUuid:f.fromUuid,Hooks,expiry,onError:e=>calls.errors.push(e)});
 const context={claim,actor:f.ally,fiend:f.enemy,fiendToken:f.enemyToken,privacy:{blind:true,whisper:['u']},damageMessage,authorize:async()=>allowed};
 return {...f,ability,claim,damageMessage,executor,context,calls,Hooks,events,allowed:v=>allowed=v,degree:v=>degree=v,mutate:fn=>mutate=fn};
}
test('original native Will uses class statistic, final degree, exact privacy and one independent Slowed grant',async()=>{
 const f=fixture();assert.equal(f.executor.ready(),true);const result=await f.executor.apply(f.context);assert.equal(result.status,'done');assert.equal(f.calls.rolls.length,1);const roll=f.calls.rolls[0];assert.deepEqual(roll.dc,{slug:'class'});assert.equal(roll.createMessage,true);assert.equal(roll.item,f.ability);assert.equal(roll.origin,f.ally);assert.equal(roll.token,f.enemyToken);assert.equal(f.calls.created.length,1);
 const data=f.calls.created[0];assert.equal(data.system.rules[0].inMemoryOnly,true);assert.equal(data.system.rules[0].alterations[0].value,1);assert.equal(data.system.context.origin.token,f.allyToken.uuid);assert.equal(data.flags[M].spiritualScarExpiry.endRound,2);const card=f.game.messages.get(result.messageId);assert.equal(card.blind,true);assert.deepEqual(card.whisper,['u']);assert.equal(f.events.size,0);
});
for(const degree of [0,1,2,3])test(`native final degree ${degree} grants Slowed only on failure`,async()=>{const f=fixture();f.degree(degree);await f.executor.apply(f.context);assert.equal(f.calls.created.length,degree<2?1:0)});
test('concurrent completion and reload of a finished receipt never roll or create twice',async()=>{const f=fixture();const results=await Promise.all([f.executor.apply(f.context),f.executor.apply(f.context)]);assert.equal(results[0].messageId,results[1].messageId);await api.createSpiritualScarFollowup({game:f.game,fromUuid:f.fromUuid,Hooks:f.Hooks,expiry:{settle:async()=>{}}}).apply(f.context);assert.equal(f.calls.rolls.length,1);assert.equal(f.calls.created.length,1)});
test('unconfirmed native save remains uncertain and is never automatically rerolled',async()=>{const f=fixture();f.mutate(c=>c.flags.pf2e.context.outcome='success');await assert.rejects(f.executor.apply(f.context));await assert.rejects(f.executor.apply(f.context));assert.equal(f.calls.rolls.length,1);assert.equal(f.calls.created.length,0);assert.equal(f.events.size,0)});
test('a missing save marker cannot leak an automatic default-public card',async()=>{const f=fixture();f.mutate(c=>c.flags.pf2e.context.options=[]);await assert.rejects(f.executor.apply(f.context));assert.equal(f.game.messages.size,1);assert.equal(f.calls.created.length,0);assert.equal(f.events.size,0)});
test('native effect creation with an uncertain response cannot be repeated',async()=>{const f=fixture();const create=f.enemy.createEmbeddedDocuments;f.enemy.createEmbeddedDocuments=async(...args)=>{await create(...args);throw Error('lost reply')};await assert.rejects(f.executor.apply(f.context));await assert.rejects(f.executor.apply(f.context));assert.equal(f.calls.created.length,1);assert.equal(f.calls.rolls.length,1)});
test('authority loss, undo, missing action or missing class DC stops before a die',async()=>{for(const change of [f=>f.allowed(false),f=>f.damageMessage.flags.pf2e.appliedDamage.isReverted=true,f=>f.ally.items.delete(f.ability.id),f=>delete f.ally.classDC]){const f=fixture();change(f);await assert.rejects(f.executor.apply(f.context));assert.equal(f.calls.rolls.length,0);assert.equal(f.calls.created.length,0)}});
test('GM handoff after the save never creates a condition or replays the save',async()=>{const f=fixture();f.mutate(()=>f.game.users.activeGM={id:'new-gm',isGM:true});await assert.rejects(f.executor.apply(f.context));assert.equal(f.calls.created.length,0);assert.equal(f.events.size,0)});
test('changing or dropping the actual native target is rejected',async()=>{for(const mutate of [c=>c.flags.pf2e.context.target.token='other',c=>c.speaker.actor='other',c=>c.flags.pf2e.origin.uuid='other']){const f=fixture();f.mutate(mutate);await assert.rejects(f.executor.apply(f.context));assert.equal(f.calls.created.length,0)}});
test('an existing higher Slowed remains untouched by this independent grant',async()=>{const f=fixture(),other={id:'slowed',type:'condition',system:{slug:'slowed',value:{value:3}}};f.enemy.items.set(other.id,other);await f.executor.apply(f.context);assert.equal(f.enemy.items.get('slowed'),other);assert.equal(other.system.value.value,3)});
